gerbera/gerbera

- src/storage/mysql/mysql_storage.h
- src/storage/sql_storage.h
- src/storage/sqlite3/sqlite3_storage.h
On 32-bit systems w/64-bit time_t's (like the x32 ABI) we fail to build:
../src/storage/sql_storage.cc: In member function 'virtual void SQLStorage::autoscanUpdateLM(zmm::Ref<AutoscanDirectory>)':
../src/storage/sql_storage.cc:2139:81: error: call of overloaded 'quote(time_t)' is ambiguous
<< " SET " << TQ("last_modified") << '=' << quote(adir->getPreviousLMT())
Handle long long types explicitly to fix that.
> fix storage quoting with long long values

- .gitignore
- CMakeLists.txt
- src/storage.h
- src/storage/sql_storage.cc
- src/storage/sql_storage.h
- src/upnp_xml.cc
beyond the cover art work we've been discussing in the forum, I added some tweaks to the Cmake configuration
I definitely appreciate the cmake work - a huge improvement!
however it was stomping on cflags [the -Wall] and broke solaris support, both of which I've fixed
also wee tweak to .gitignore FTW
to build under OmniOS with Joyent packages and a locally built libupnp, FWIW, this worked:
env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig cmake CMakeLists.txt  -DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS=-m64 -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=0 -DWITH_JS=0 -DWITH_TAGLIB=1 -DWITH_AVCODEC=0 -DWITH_DVDNAV=0 -DWITH_EXIF=1 -DWITH_LASTFM=0
More tweaks may be needed for JS; once i verify this is running stably, i'll try that...
> Changes for Cover Art [folder, track] support, Solaris support too

- CMakeLists.txt
- src/logger.cc
- src/logger.h
- src/main.cc
- The -D/--debug command line option flipped its sense when
TOMBDEBUG was defined. Now it behaves consistently.
- Removed the redundant DEBUG_LOG_ENABLED (replaced with TOMBDEBUG)
> Fix handling of the --debug command line option

- .gitignore
- CMakeLists.txt
- src/main.cc
This fell on the floor during the cmake migration
autodetecting [an attempt] to enable on X86 platforms. 
The real intent is not to detect X86, but to detect
and not enable on ARM, according to old README
...also a .gitignore tweak you can ignore, if you insist
> Re-support SIGHUP

- src/server.cc
Super simple - e4c0f5c769ed313fbf5fe95c983ee7251fb7b6eb left the un-commented "event is ok" message, which will crap up one's log rather quickly.  
I assume that was an unintended side-effect.
Just re-commenting it back out.
> re-silence "event is ok" info message

- src/main.cc
Recent changes broke my build; some things not defined by default.
Particularly because the ISO defines aren't necessarily standard, i put them in an ifdef block.
If you feel they're safe for everyone, by all means pull them out.
> Add includes for solaris for USHRT_MAX and signal handling

- src/main.cc
...,but note that this all reveals that perhaps zmm::String should be replaced with std::string, and
anyway, why is zmm::String.length() not a size_t?
> Avoid warning by explict casting

- CMakeLists.txt
While this ad9eefc77a7ac9ce2f9211841b1f59ad755dfd69 updated the man page, nothing was installing it.
Fixed
> Install man page

- src/storage/sql_storage.cc
This improves UPnP browsing speed quite a lot on MySQL.
It does not change the current behavior, which is providing folder.jpg as container image.
Resolves: https://github.com/v00d00/gerbera/issues/75
> Remove useless subselect when fetching cover art

- CMakeLists.txt
- src/scripting/duktape/README.duktape
- src/scripting/duktape/duk_config.h
duktape.o was always built even when WITH_JS unset, and this would fail since duktape.c is actually C++ but the compile switch was only done in the WITH_JS branch.
Cleanup duktape README.  
Quick patch for OmniOS/Solaris to duk_config.h, pending upstream patch svaarala/duktape#1514
for extra hilarity, committing a change to the duktape git repo triggers a git fsck bug on OmniOS; had to do that from Ubuntu
> Fix broken build when WITH_JS=0, duktape patch for OmniOS/Solaris

- src/timer.cc
- src/timer.h
Hello, here is round 2 for #86.  C++ won round 1.  Thanks to @gburca for suggestion on solution.
I was able to run **gerbera** locally, watch a few movies & listen to music.  The subscribers were cleaned up as expected when new web sessions were created, and timed out.  No obvious memory leaks after running for a few hours.
The only item **NOT** tested is the `element.isOnce()` condition.  Not sure how to test that directly?
Let me know what you think.  Any guidance on C++ convention and standard is appreciated. 👍
> Fix #86 - SessionManager checkTimer deadlock

- src/storage/sql_storage.cc
I've now found the use-case, using eg foobar2000, where Virtual Folder cover art isn't returned.
the cover.jpg/etc artwork was implemented to work when using "PC Filesystem" mode in
DLNA clients.  Browsing via for example "Audio" then "Artists" was not working,
as the virtual root didn't match the physical.  Now both cases properly return
file-based cover art.
In case #75 reappears for MySQL folk, there is currently a define `ONLY_REAL_FOLDER_ART ` to disable this addition.
I note that in my scenario [six thousand albums] returning "Audio/Albums" hits the network timeout for
foobar2000 mobile, whether or not `ONLY_REAL_FOLDER_ART` is enabled.  With Sqllite, peformance
is otherwise fine in either case.
> Re-enable Virtual Folder album art

- src/web_request_handler.h
This was in one of Debian's mediatomb patches so it seemed sensible to submit it upstream so that patch can be dropped.
> Fix minor spelling mistake

- scripts/install-lastfm.sh
Completes #107 
Similar to any other install script in the `scripts/` directory, run it using bash. It requires a c++ compiler, libcurl, make, pkg-config and wget to run.
> lastfmlib install script

- src/config_manager.cc
- src/config_manager.h
- src/main.cc
* Use throughout port 0 as default unassinged port which is documented in
the original config.xml for the server as well as the MySQL storage
backend.
* Re-read port from ConfigManager in main.cc to print out eventually
changed port in error cases.
This cleans up inconsistensions from dynamically assigned, command line provided or config.xml provided server port. Proper, consistent port is reflected in log output.
> Fix port number confusion

- src/config_manager.cc
Compiling gerbera with mysql support enabled, exit with the above error as there was a ; in the wrong place
> Fixing "error: expected ‘,’ or ‘;’ before ‘if’" at compile time

- CMakeLists.txt
- cmake/GenCompileInfo.cmake
- src/main.cc
I added a few new definitions to include the git information.
Testing consisted of running for about 1 hour, watched a few movies..
Here is a sample output for compile info:
```
/d/g/build> ./gerbera --compile-info
Gerbera UPnP Server version 1.1.0_alpha - http://gerbera.io/
===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2
Copyright 2016-2017 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info:
-------------
WITH_MAGIC=1
WITH_MYSQL=1
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=1 …
```
> Fix #43 - Add compile information and git revision

- src/tools.cc
The changes to support "native uuid" once again broke Solaris/OmniOS
This should fix that
> Fix native-uuid for Solaris/OmniOS

- cmake/FindINotify.cmake
- cmake/FindLibMagic.cmake
For libinotify and libmagic wrong lib file paths in found messsages are
echoed.
Situation before:
-- Looking for BSD native UUID - found
-- Found UPnP: /usr/local/gerbera/lib/libupnp-1.8.so (found version "1.8.2")
-- Found EXPAT: /usr/local/lib/libexpat.so (found version "2.2.1")
-- Found Sqlite3: /usr/local/lib/libsqlite3.so
-- Found INOTIFY: /usr/local/gerbera/include
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.55.1")
-- Found MAGIC: /usr/include
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mosipov/Projekte/gerbera/build
Situation after:
-- Looking for BSD native UUID
-- Looking for BSD native UUID - found
-- Found UUID: TRUE
-- Looking for native LFS support
-- Looking for …
> Fix wrong found messages from CMake files

- src/process.cc
Tested with simple Active Item that hit a shell script.  Files generated OK in `/tmp` and cleaned up afterward.
> Fixes #157 - Open /tmp using O_EXCL to avoid race condition

- cmake/FindFFMPEG.cmake
avformat depends on avcodec so it should be added first otherwise static
linking will fail
> Fix static linking with ffmpeg

- cmake/COPYING-CMAKE-SCRIPTS
- cmake/FindLibraryWithDebug.cmake
FindLibraryWithDebug is used to find taglib library if taglib-config is
not found however this cmake function is only available in KDE so add
FindLibraryWithDebug.cmake to gerbera
Also, add COPYING-CMAKE-SCRIPTS as it is referenced by
FindLibraryWithDebug.cmake but also by FindTagLib.cmake and
FindSQLite3.cmake
> Add FindLibraryWithDebug.cmake

- web/assets/theme/gerbera.css
The initial layout was haphazard as I did not spend time to calculate the proper heights of all elements.
This update includes consistent calculation for all UI static elements.  Both the **tree** and **items** height line up.  The view has a gutter of about `5vh` to allow for some movement between different resolutions.
> Update Gerbera UI layout for full height display

- gerbera-web/mock-api/items/oversize-error-msg.json
- gerbera-web/mock-api/items/tests/toast.spec.json
- gerbera-web/test/e2e/page/home.page.js
- gerbera-web/test/e2e/toast.spec.js
- web/assets/theme/gerbera.css
When the system suffers a catastrophic error, the toast will show the entire message.  This causes elements to go off-screen and be unreadable.  This fix also applies to **tasks** which show at the top of the screen.
> There is presently no standard CSS way to easily do _multi-line_ wrapped ellipsis. (requires -webkit, etc)
> Improve consistent toast size for error messages

- gerbera-web/test/client/jquery.gerbera.items.spec.js
- web/js/jquery.gerbera.items.js
A simple change to manually remove the item table row `<tr>` on click...which removes possibility of double clicking, while waiting for items to refresh from server.
> Fixes #201 - Remove row on click, instead of waiting for refresh

- .travis.yml
- gerbera-web/test/e2e/toast.spec.js
Add environment variable which decides whether to run Gerbera UI tests, including Karma client-side tests and Selenium e2e tests.
1. Install NodeJS and Google Chrome dependencies using `apt`
2. Run `npm install` to download all dependencies from default registry **(npmjs.com)**
3. Run `npm run test` for a single matrix'd build
4. Run `npm run test:e2e` for a single matrix'd build
The client-side unit tests run using the [PhantomJS](http://phantomjs.org/) webkit headless browser.  These tests are fully isolated from a gerbera runtime server.
The end-to-end tests run using a **mock server** which mimics the API expected from a server runtime.  The mock server runs using [express-js](https://expressjs.com/) and does not rely on a gerbera server runtime.  
The selenium tests require **xvfb** …
> Fix #205 - Add Gerbera UI tests to Travis CI

- src/storage/sql_storage.cc
Fix for  #238
"this time for sure"
Since it appears MySQL also still doesn't support subquery LIMITS, this is only used when the sqlite3 driver is active.  I realized this can't be safely determined strictly from cmake as ultimately this is a runtime choice from config files.
Perhaps someone running MySQL can investigate further - creating a subtable or otherwise purpose-optimizing this query would likely still be useful on mysql for performance.  Ultimately the cover art mechanism could use a refactor.
Cheers
> Only enable MAX_ART_CONTAINERS when sqlite3 driver is in use

- src/autoscan_inotify.cc
- src/content_manager.cc
- src/content_manager.h
Dear gerbera maintainers,
I added an overload to the ContentManager::addFile method, allowing for passing a container's root path as additional parameter. Using this method from within the event handling code in AutoscanInotify::threadProc should fix the problem of undefined object_script_path values in import.js as described in https://github.com/gerbera/gerbera/issues/227.
Cheers --
Torsten
> #227 Pass rootpath to import.js on Inotify event

- README.md
- doc/install.rst
Entware links [update](https://github.com/Entware/entware#entware-ng-3x-and-entware-ng-merged-to-become-entware).
> Entware-ng/-3x merged into Entware

- gerbera-web/test/client/fixtures/index.html
- gerbera-web/test/client/fixtures/toast.html
- gerbera-web/test/client/gerbera.app.spec.js
- gerbera-web/test/client/gerbera.autoscan.spec.js
- gerbera-web/test/client/gerbera.trail.spec.js
- gerbera-web/test/client/gerbera.updates.spec.js
- gerbera-web/test/client/jquery.gerbera.toast.spec.js
- gerbera-web/test/e2e/delete.item.spec.js
Change UI test suite to support new UI toast message:
* Fix method assertions for `GERBERA.Updates.showMessage`
* Add new `toast` object to toast tests
* Update test HTML fixtures with **id** and **class** attributes
* Update E2E assertions for delete --> remove
> Update test assertions for new UI toast

- src/content_manager.cc
Dear gerbera maintainers,
I still encountered some problems regarding null values for object_script_path when renaming whole directories in inotify-watched sub-trees. I introduced some further code changes which seemed to have solved the problem.
Hope that helps!
Cheers --
Torsten
> 227 rootpath still missing in js

- doc/config-overview.rst
- doc/run.rst
* Make `Generating Configuration` a sub-topic of `Configuration Overview`
* Add link from `First Time Run` back to `Generating Configuration`
> Improve documentation following elimination of automatic configuration generation
> First run documentation now mentions config generation

- test/test_server/fixtures/mock-help.out
- test/test_server/fixtures/mock-version.out
- test/test_server/test_main.cc
Fixes #293 
Initially objective was to cover the ability for the server to startup following configuration geneator changes in the `main.cc` class.  The signal to update version numbers via unit test validation is rather inconvenient.
Updated the tests to only validate Help Content.  I think this is a valid signal, so developers don't forget to include/modify help output.
Let me know if you think another approach would be more appropriate.
Thanks,
Eamonn
> Fix unit tests to be repeatable across versions

- src/string_converter.cc
- src/string_converter.h
i2i function is used in atrailers_service.cc but this function is
defined only if defined(HAVE_JS) || defined(HAVE_TAGLIB) ||
defined(YOUTUBE) || defined(HAVE_LIBMP4V2) as a result compilation
fails if HAVE_CURL is set but HAVE_JS and HAVE_TAGLIG are not.
As youtube and libmp4v2 support have been dropped, replace those by
ATRAILERS in this list.
> Fix atrailers build

- README.md
zlib was optional but highly recommended in mediatomb. In gerbera, this
is a mandatory dependency as zlib is used by sqlite3 storage which is
mandatory.
> Readme.md: specify that zlib is required

- src/config/config_generator.cc
The method code **does** use native UUID, but the import did not.
> Fix #310 - Config Generator to use native BSD UUID when available

- .travis.yml
- gerbera-web/test/e2e/add.object.spec.js
- gerbera-web/test/e2e/autoscan.spec.js
- gerbera-web/test/e2e/delete.item.spec.js
- gerbera-web/test/e2e/items.spec.js
- gerbera-web/test/e2e/login.spec.js
- gerbera-web/test/e2e/logout.spec.js
- gerbera-web/test/e2e/menu.spec.js
- gerbera-web/test/e2e/overlay.spec.js
- gerbera-web/test/e2e/toast.spec.js
- gerbera-web/test/e2e/trail.spec.js
The E2E suite used Xvfb to hide the Chrome window when running in Travis CI.
Chrome Headless is now the common testing tool for the E2E and Unit Test suites.
------------
* Use Chrome Headless for E2E
* Remove Xvfb in favor of Chrome Headless
> Use Chrome Headless for E2E Suite

- src/config/config_generator.cc
- src/metadata_handler.h
- test/test_config/fixtures/mock-config-all.xml
- test/test_config/fixtures/mock-config-minimal.xml
- test/test_config/fixtures/mock-import-magic-js-online.xml
- test/test_config/fixtures/mock-import-magic-js.xml
- test/test_config/fixtures/mock-import-mappings.xml
- test/test_config/fixtures/mock-import-none.xml
Fixes #324 - Improve defaults for DSD file types.
> Add DSD configuration

- src/config_manager.cc
- test/test_config/test_configmanager.cc
Utilize `home` variable and improve inline message format using `std::ostringstream`
Fixes #329 
**Example**
```
The server configuration file could not be found in: ~/.config/gerbera
Gerbera could not find a default configuration file.
Try specifying an alternative configuration file on the command line.
For a list of options run: gerbera -h
```
> Improve accuracy of error message for missing config

- src/config/config_generator.cc
- test/test_config/fixtures/mock-config-all.xml
- test/test_config/fixtures/mock-config-minimal.xml
- test/test_config/fixtures/mock-import-magic-js-online.xml
- test/test_config/fixtures/mock-import-magic-js.xml
- test/test_config/fixtures/mock-import-mappings.xml
- test/test_config/fixtures/mock-import-none.xml
Seemed like this should be there by default given that all other supported file-types are.
> Adds WavPack file extension to config

- scripts/js/import.js
- src/scripting/script.cc
- test/test_script/mock/script_test_fixture.cc
- test/test_script/mock/script_test_fixture.h
- test/test_script/test_import_script.cc
- test/test_script/test_import_struct_script.cc
Looks like this was a pending todo in the code. Primarily useful for dealing with Stereo & Multichannel audio in your collection.
Only part I was not too sure about was `res = obj->getResource(0);`. I only found one resource to ever be used and didn't know how key collisions should be handled so left it as is. 
Let me know if I should change it.
> Adds Resource Attributes to scripting.

- doc/config-online.rst
Add examples for `<AppleTrailers>` and `<SopCast>`
> Currently working on documentation for `<streaming>` configuration that will appear in the next PR!
> Fix #328 - Add online content examples

- config/config2.xsd
- doc/config-extended.rst
Fixes #347 - Add `<cache-dir>` to `config2.xsd` and to documentation.
> Update cache-dir documentation for thumbnails

- .travis.yml
- scripts/install-duktape.sh
- scripts/install-googletest.sh
- scripts/install-lastfm.sh
- scripts/install-pupnp18.sh
- scripts/install-taglib111.sh
- scripts/search.sh
Hey everybody,
I just recently tried to install gerbera on a fresh FreeBSD Jail and the installation script failed because I did not had sudo installed. So I just changed the scripts. Also this is my first pull request ever so please be kind ;)
Remove the sudo dependecy in the install scripts and added a
if-statement to check if the script is run with superuser access to
perform the install.
This removes the need to have sudo installed and also has a better
error-handeling if the user types in the root password wrong 3 times.
Fixed shellcheck warnings which should result in robuster code.
> Removing sudo dependecy and fixing shellcheck warnings

- doc/config-server.rst
- doc/daemon.rst
Remove invalid startup information from documentation, including:
* UDN generation
* Daemon startup
Fixes #350
> Update UDN startup doc, cleanup other startup info

- scripts/install-googletest.sh
Fixes #354 
Continue use of GoogleTest master, adding `-std=c++14` to the build flags
> Build GoogleTest with c++14 standard

- gerbera-web/mock-api/auth/config.json
- gerbera-web/test/client/fixtures/config.json
- gerbera-web/test/client/fixtures/converted-config.json
- gerbera-web/test/client/gerbera.app.spec.js
- gerbera-web/test/client/gerbera.menu.spec.js
- gerbera-web/test/e2e/menu.spec.js
- gerbera-web/test/e2e/page/home.page.js
- src/web/auth.cc
- web/js/gerbera.app.js
- web/js/gerbera.menu.js
Support ability to show configured server name in the Web UI. Includes:
* Show in the Home menu option
* Show as the web page title
Defaults to CMake Project Name(_Gerbera_) when not defined in `config.xml`
Fixes #363
> Add Server Name to Web UI Menu & Title

- gerbera-web/test/e2e/add.object.spec.js
- gerbera-web/test/e2e/autoscan.spec.js
- gerbera-web/test/e2e/delete.item.spec.js
- gerbera-web/test/e2e/login.spec.js
- gerbera-web/test/e2e/page/home.page.js
- gerbera-web/test/e2e/page/login.page.js
Instead of waiting 5 seconds for the toast message to close, the tests now close it manually.
> This removes any warning alerts in test output for tests steps running > 5 seconds.
> Close toast manually to speed up UI tests

- .travis.yml
The Trusty Ubuntu 14.04 build works well, it is nearing the end-of-life in April 2019 _see: [Ubuntu Releases](https://wiki.ubuntu.com/Releases)_
The Travis CI system supports Xenial, updating to that allows for recent improvements.
https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images
> This is only tech currency related improvements and is low priority for merge.
> Update to xenial distribution in Travis

- .travis.yml
- gerbera-web/.gitignore
- gerbera-web/package-lock.json
Travis supports use of `package-lock.json` and contains default installs of NodeJS on Trusty.
```
Pre-installed Node.js versions
v4.8.7
v6.12.0
v6.12.3
v8.9
v8.9.1
v8.9.4
```
* Add `package-lock.json` to improve secure package download
* Remove unnecessary installs for apt-get in Travis
> I ran `npm audit` to ensure the packages have no known vulnerabilties (as identified by npmjs.org)
```
added 816 packages from 1379 contributors in 8.125s
[+] no known vulnerabilities found [5303 packages audited]
```
> Improve NodeJS - Add package-lock, remove unused package installs

- CMakeLists.txt
It is not compiling with older versions (it failed with 3.7)
> The "Compile Features" functionality is now aware of C++ 17. 
https://cmake.org/cmake/help/v3.8/release/3.8.html
> Set required CMake version to 3.8

- src/main.cc
Following changes to CXXOpts, Gerbera does not compile on macOS due to variadic non-trivial type being passed to `log_debug`
https://github.com/gerbera/gerbera/commit/6cf290d725a98b7d9b4f3d09db1e94ea66c35258#diff-ddaa7d6e643bc0d374add600b02445beR188
```bash
[ 98%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
/gerbera/src/main.cc:185:54: error: cannot pass object of non-trivial 
type 'std::__1::optional<std::__1::basic_string<char> >::value_type' 
(aka 'std::__1::basic_string<char>')
through variadic function; call will abort at runtime [-Wnon-pod-varargs]
log_debug("Home detected as: %s\n", home.value());
^
1 error generated.
```
> Fix variadic non-trivial type in macOS

- src/layout/fallback_layout.cc
`<upnp:date>` is now supported in:
* `import.js`
* `import-structured.js`
* `fallback_layout`
> Add upnp:date to fallback layout

- .travis.yml
Use a docker image to build on travis-ci.
Compilers, GCC7, GCC8 and Clang7 are baked in, along with all our deps except gtest, which is downloaded each time.
The image is available on docker hub as [gerbera/gerbera-ci-base](https://cloud.docker.com/u/gerbera/repository/docker/gerbera/gerbera-ci-base).
The Dockerfile is on github at https://github.com/gerbera/gerbera-ci-base-docker
> Dockerised CI

- gerbera-web/test/client/gerbera.app.spec.js
- gerbera-web/test/client/gerbera.menu.spec.js
- web/js/gerbera.app.js
Adjust AJAX calls to have no client-side cache.  Cache-Control header allows repeated requests to always be directly to the server, rather than returned from browser cache.
> Applies `no-cache` to all AJAX calls.
Allows long-polling and tree navigation to work properly when re-visiting folders.
> Set Cache-Control on all AJAX calls

- scripts/js/playlists.js
- test/test_script/mock/common_script_mock.h
- test/test_script/mock/duk_helper.cc
- test/test_script/mock/duk_helper.h
- test/test_script/mock/script_test_fixture.cc
- test/test_script/mock/script_test_fixture.h
- test/test_script/test_internal_m3u_playlist.cc
- test/test_script/test_internal_pls_playlist.cc
Add `copyObject` and `getCdsObject` to playlist script, including test fixtures.
Resolves failures in #407.
> Playlist meta support

- scripts/js/import.js
First of all a huge "Thank you" for reviving this project. I had been using MT in the past until updating my LTS Ubuntu became to painful because of the libmoz issue. As a classical music lover I like the scripting facilities very much. Here is a small fix of an old bug that did survive until now:
If an audio file comes without a description tag, import.js gathers some information in order to compose a description like "artist, album, title, date, genre" but fails to write it to the proper field.
> UPNP Description field does not get populated

- cmake/FindFFMPEG.cmake
Add ogg to FFMPEG_LIBRARIES in FindFFMPEG.cmake otherwise static
linking will fail as ogg is a dependency of vorbis
Fixes:
- http://autobuild.buildroot.org/results/2b99fabd798db84a0fce26ad696c58e54c6ff626
> cmake/FindFFMPEG.cmake: fix static linking with vorbis

- cmake/FindFFMPEG.cmake
ffmpeg has too many optional dependencies (opus, openssl, ...) instead
of trying to find them all one by one, use pkg-config to get them and
fallback on current mechanism
Fixes:
- http://autobuild.buildroot.org/results/2b99fabd798db84a0fce26ad696c58e54c6ff626
- http://autobuild.buildroot.org/results/95e410e5ab34c6d4626a58f97c0d2d5e6829a300
> cmake/FindFFMPEG.cmake: use pkgconfig

- src/file_request_handler.cc
Fixes #430 
* Does not set content length to `-1` and instead uses the file size calculated from the FileHandler
This tested OK, although it was definitely written hastily.....a second opinion is worth the time before merging.  I did not reconcile if setting `UpnpFileInfo_set_FileLength` explicitly has any consequences in underlying libupnp?
> Set file size for file handler

- cmake/FindFFMPEG.cmake
> cmake/FindFFMPEG: fix dynamic linking with pkg-config

- cmake/FindLibUpnp.cmake
Fix static linking with an openssl enabled upnp:
- remove libupnp-1.8 from pkg_check_modules call otherwise test will
fail if libupnp-1.8.pc is not found
- add PC_UPNP_LIBRARIES to UPNP_LIBRARIES
Fixes:
- http://autobuild.buildroot.org/results/10098c8972725d54b717ddc8ea41f4de5e5b066d
> cmake/FindLibUpnp.cmake: fix static linking

- src/config/config_generator.cc
- test/test_config/fixtures/mock-config-all.xml
- test/test_config/fixtures/mock-config-minimal.xml
Fix #446 
Prepend the `XML_HEADER` declaration on the `gerbera --create-config` option.
This was previously cut when configuration generator was pushed via #282
> Generate config.xml with XML Declaration

- src/main.cc
CLI `interface` option parsing is broken after changes in 6cf290d725a98b7d9b4f3d09db1e94ea66c35258. This fixes interface value assignment to correct variable.
> main: bugfix `interface` CLI option

- src/metadata/exiv2_handler.cc
With latest exiv2 0.27.1 there is a build error
`exiv2_handler.cc:179:21: error: 'AnyError' in namespace 'Exiv2' does not name a type`
The issue was detected during buildroot autobuild tests after the bump of exiv2 to version 0.27.1
http://autobuild.buildroot.net/results/3831acf7f4c5a9f1a404e0ced3d6bec7a2249601/
http://autobuild.buildroot.net/results/de0545462c6017fe54acc284b914b9fa8b0172d8/
> Use exiv2 header that include all headers

- src/upnp_xml.cc
Proposal to fix #459  
It seems logical to render the resource with full URL.
> Although not sure how this correlates to Docker...
The method could use rework to support multiple resource types through method abstraction + TDD...however, that is a larger scale effort at this time.
> Add virtualUrl to AlbumArt resource for consistent resource URIs

- cmake/FindFFMPEG.cmake
gerbera does print some configuration status messages, e.g. _"Found TagLib: ..."_, _"Found ZLIB: ..."_, but it does not so for FFmpeg. To make the status message behaviour more consistent, do not quieten the log messages from pkg-config module.
On my system, this prints:
```
-- Checking for modules 'libavformat;libavutil'
--   Found libavformat, version 57.83.100
--   Found libavutil, version 55.78.100
```
> cmake/FindFFMPEG: do not quieten messages when using pkg-config

- gerbera-web/mock-api/auth/config.json
- gerbera-web/test/client/fixtures/config.json
- gerbera-web/test/client/fixtures/converted-config.json
- gerbera-web/test/e2e/menu.spec.js
- gerbera-web/test/e2e/page/home.page.js
- src/web/auth.cc
- web/index.html
- web/js/gerbera.menu.js
Fixes #468 
Add the Gerbera Server version to the UI menu bar.
> Presently gerbera does not support pulling server info, unless a Session ID has been established.  This shows only after login is complete.
> Add Gerbera version to UI

- cmake/FindTaglib.cmake
When cross-compiling Gerbera CMakes `find_program()` will search for
binaries on the host. This is typically correct, e.g. when search for
compilers or shells.
When cross-compiling searching for `taglib-config` should not find the
binary on the host, instead it should find the binary in the sysroot
directory, as the host `taglib-config` will output the wrong host paths
and libs, whereas the sysroot `taglib-config` will output the correct sysroot
paths and libs.
Therefore, use the `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` variable when
cross-compiling. This variable controls whether the `CMAKE_FIND_ROOT_PATH`
and `CMAKE_SYSROOT` are used by find_program().
> Fix find_program taglib-config when cross-compiling

- CMakeLists.txt
- src/common.h
- src/device_description_handler.cc
- src/device_description_handler.h
- src/server.cc
- src/server.h
- src/upnp_xml.cc
- src/upnp_xml.h
- test/test_upnp/test_upnp_xml.cc
This is currently not used, but will be needed when we switch to the
newer `UpnpRegisterRootDeviceX` methods.
It serves the device description XML as generated by
`renderDeviceDescription()` at `<serverpath>/content/description.xml`
> Add DeviceDescriptionHandler

- .travis.yml
Update the travis CI build to define `language: cpp`
* Solves issue where Travis gives `trusty` when `language` is not defined
* Solves `dpkg` support for new Chrome packaging by using `xenial`
Travis builds with `xenial`
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
Travis builds with each different C++ version
```
[  0%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
/usr/bin/g++-7  -DATRAILERS
```
```
[  0%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
/usr/bin/g++-8  -DATRAILERS
```
```
[  0%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
/usr/bin/clang++-7  -DATRAILERS
```
> Set language to support xenial & latest chrome

- src/string_converter.cc
- src/string_converter.h
i2i function is used in matroska_handler.cc but this function is defined
only if defined(HAVE_JS) || defined(HAVE_TAGLIB) || defined(ATRAILERS)
as a result compilation fails if HAVE_MATROSKA is set but HAVE_JS,
HAVE_TAGLIG or ATRAILERS are not.
> fix matroska build without js, taglib or atrailers

- cmake/FindLibUpnp.cmake
As upstream no longer slot 1.8x releases, they are unlikely to be found
in those paths anyway.
Plus, 1.8 is now in pretty much every distro by default
This means we will still find the old way, but prefer the new.
> CMake: LibUPnP: Prefer non -1.8 suffixed

- src/search_handler.cc
- src/search_handler.h
- src/storage/sql_storage.cc
- test/test_searchhandler/test_searchhandler.cc
as a result of the change from String class to std::string, we can now simplify search_handler.h/cc
> simpliy search_handler.h/cc: replace std::make_shared<std::string> with std::string

- CMakeLists.txt
On some architectures, atomic binutils are provided by the libatomic
library from gcc. Linking with libatomic is therefore necessary,
otherwise the build fails with:
```
[100%] Linking CXX executable gerbera
/home/fabrice/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/7.4.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: CMakeFiles/libgerbera.dir/src/zmm/object.cc.o: undefined reference to symbol '__atomic_fetch_add_4@@LIBATOMIC_1.0'
/home/fabrice/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/7.4.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: /home/fabrice/buildroot/output/host/sparc-buildroot-linux-uclibc/sysroot/lib/libatomic.so.1: error adding symbols: DSO missing from command line
```
This is often for …
> CMakeLists.txt: check for atomic library

- CMakeLists.txt
- test/test_config/CMakeLists.txt
- test/test_handler/CMakeLists.txt
- test/test_runtime/CMakeLists.txt
- test/test_script/CMakeLists.txt
- test/test_searchhandler/CMakeLists.txt
- test/test_server/CMakeLists.txt
- test/test_upnp/CMakeLists.txt
seems more logical: make libgerbera STATIC and reuse it for gerbera + all test binaries
> link test binaries against libgerbera

- src/main.cc
- src/web/web_autoscan.cc
> Fix basic_string::_M_construct null not valid in autoscan

- src/autoscan.cc
- src/autoscan_inotify.cc
- src/cds_objects.cc
- src/cds_resource.cc
- src/config/config_manager.cc
- src/content_manager.cc
- src/file_request_handler.cc
- src/iohandler/process_io_handler.cc
- src/metadata/fanart_handler.cc
- src/metadata/libexif_handler.cc
- src/metadata/matroska_handler.cc
- src/metadata/taglib_handler.cc
- src/scripting/script.cc
- src/server.cc
- src/storage/sql_storage.cc
- src/transcoding/transcoding.cc
- src/transcoding/transcoding_process_executor.cc
- src/upnp_cds.cc
- src/upnp_xml.cc
- src/util/process_executor.cc
- src/util/task_processor.cc
- src/util/xml_to_json.cc
- src/web/auth.cc
- src/web/containers.cc
- src/web/items.cc
- src/web/session_manager.cc
- src/web/tasks.cc
- src/web/web_autoscan.cc
Found with modernize-loop-convert, performance-for-range-copy
>  [clang-tidy] use range based loops

- src/config/config_generator.cc
- src/iohandler/io_handler.cc
- src/layout/js_layout.cc
- src/onlineservice/online_service_helper.cc
- src/scripting/import_script.cc
- src/scripting/playlist_parser_script.cc
- src/transcoding/transcoding.cc
- src/util/task_processor.cc
Found with modernize-use-equals-default
> [clang-tidy] use = default

- src/config/config_generator.cc
- src/config/config_manager.cc
- src/util/tools.cc
- src/web/web_request_handler.cc
Found with modernize-use-raw-string-literal
> [clang-tidy] use raw string literals

- src/metadata/taglib_handler.cc
- src/upnp_xml.cc
Found with performance-faster-string-find
> [clang-tidy] use '' with single character

- src/util/tools.cc
error: invalid operands to binary expression ('const char [21]' and
'const fs::path') [clang-diagnostic-error]
throw std::runtime_error("could not open file " + avi_filename + ": " +
mt_strerror(errno))
> tools: fix compilation with newer clang.

- src/cds_objects.cc
Found with modernize-use-bool-literals.
> [clang-tidy] use bool literals

- src/autoscan_inotify.cc
- src/content_manager.cc
- src/storage/sql_storage.cc
- src/web/session_manager.cc
Found with readability-container-size-empty
> [clang-tidy] use empty instead of comparing size

- src/config/config_manager.cc
- src/file_request_handler.cc
- src/util/tools.cc
Found with modernize-use-emplace
> [clang-tidy] use emplace_back

- src/util/jpeg_resolution.cc
Found with modernize-use-using
> [clang-tidy] use using insead of typedef

- src/content_manager.cc
- src/scripting/js_functions.cc
- src/storage/sqlite3/sqlite3_storage.cc
- src/util/tools.cc
- src/web/web_request_handler.cc
Found with readability-redundant-string-init
> [clang-tidy] remove redundant string initializations

- src/config/config_manager.cc
- src/content_manager.cc
- src/metadata/matroska_handler.cc
- src/server.cc
- src/upnp_mrreg.cc
- src/util/tools.cc
Found with modernize-use-nullptr
> [clang-tidy] use nullptr

- src/web/pages.cc
- src/web/session_manager.cc
- src/web/web_request_handler.cc
Found with llvm-namespace-comment
> [clang-tidy] fix namespace comments

- src/iohandler/curl_io_handler.cc
Found with hicpp-static-assert
> [clang-tidy] replace assert with static_assert

- src/cds_objects.cc
Found with bugprone-parent-virtual-call
> [clang-tidy] call proper overriden method

- src/storage/sql_storage.cc
Found with bugprone-macro-parentheses
> [clang-tidy] add parentheses to macro

- src/storage/sqlite3/sqlite3_storage.cc
Found with readability-redundant-control-flow
> [clang-tidy] remove continue statement at end of loop

- src/onlineservice/atrailers_content_handler.cc
- src/upnp_cds.cc
- src/upnp_xml.cc
Found with performance-inefficient-string-concatenation
> [clang-tidy] use .append for strings

- src/metadata/matroska_handler.cc
Found with modernize-redundant-void-arg
> [clang-tidy] remove pointless void argument

- src/file_request_handler.cc
- src/util/tools.cc
Found with bugprone-suspicious-string-compare
> [clang-tidy] fix wrong strncmp usage

- src/cds_resource.cc
- src/upnp_cds.cc
Found with readability-redundant-string-cstr
> [clang-tidy] remove redundant c_str method

- src/autoscan_inotify.h
- src/content_manager.h
- src/file_request_handler.h
- src/iohandler/curl_io_handler.h
- src/metadata/matroska_handler.h
- src/metadata/taglib_handler.h
- src/scripting/import_script.h
- src/storage/sql_storage.h
- src/storage/sqlite3/sqlite3_storage.h
- src/util/tools.h
Found with readability-inconsistent-declaration-parameter-name
> [clang-tidy] fix function defenitions

- src/autoscan_inotify.cc
- src/config/config_manager.cc
- src/content_manager.cc
- src/file_request_handler.cc
- src/main.cc
- src/metadata/metadata_handler.cc
- src/storage/sql_storage.cc
- src/transcoding/transcode_ext_handler.cc
- src/util/tools.cc
- src/web/add_object.cc
Found with misc-unused-alias-decls
> [clang-tidy] remove unused using declarations

- src/autoscan.cc
- src/autoscan_inotify.cc
- src/config/config_manager.cc
- src/content_manager.cc
- src/file_request_handler.cc
- src/iohandler/io_handler_buffer_helper.cc
- src/iohandler/process_io_handler.cc
- src/metadata/taglib_handler.cc
- src/search_handler.cc
- src/storage/sql_storage.cc
- src/storage/sqlite3/sqlite3_storage.cc
- src/transcoding/transcode_dispatcher.cc
- src/upnp_cds.cc
- src/url_request_handler.cc
- src/util/mt_inotify.cc
- src/util/task_processor.cc
- src/util/tools.cc
- src/web/edit_load.cc
- src/web/edit_save.cc
- src/web/session_manager.cc
- src/web/web_request_handler.cc
Found with readability-else-after-return
> [clang-tidy] don't use else after return

- src/iohandler/io_handler_buffer_helper.cc
- src/iohandler/io_handler_chainer.cc
- src/iohandler/process_io_handler.cc
- src/layout/fallback_layout.cc
- src/layout/js_layout.cc
- src/storage/sqlite3/sqlite3_storage.cc
Found with readability-redundant-member-init
> [clang-tidy] remove redundant member initializations

- src/cds_objects.cc
- src/cds_objects.h
Found with performance-unnecessary-value-param
This required manual editing.
> [clang-tidy] fix last performance issue

- src/metadata/matroska_handler.cc
- src/metadata/taglib_handler.cc
- src/scripting/playlist_parser_script.cc
[clang-tidy] use dynamic_cast instead of static_cast
Found with cppcoreguidelines-pro-type-cstyle-cast
Found with cppcoreguidelines-pro-type-static-cast-downcast
>  [clang-tidy] use dynamic_cast instead of static_cast

- src/config/config_manager.cc
- src/content_manager.cc
- src/iohandler/buffered_io_handler.cc
- src/iohandler/curl_io_handler.cc
- src/iohandler/io_handler_buffer_helper.cc
- src/iohandler/io_handler_chainer.cc
- src/iohandler/mem_io_handler.cc
- src/layout/fallback_layout.cc
- src/metadata/libexif_handler.cc
- src/metadata/taglib_handler.cc
- src/onlineservice/online_service_helper.cc
- src/scripting/playlist_parser_script.cc
- src/scripting/script.cc
- src/server.cc
- src/storage/mysql/mysql_storage.cc
- src/storage/sqlite3/sqlite3_storage.cc
- src/transcoding/transcode_ext_handler.cc
- src/update_manager.cc
- src/url.cc
- src/util/jpeg_resolution.cc
- src/util/mt_inotify.cc
- src/util/string_converter.cc
- src/util/task_processor.cc
- src/util/thread_executor.cc
- src/util/timer.cc
- src/util/tools.cc
Found with google-readability-casting
> [clang-tidy] replace C casts with C++ ones

- src/metadata/taglib_handler.cc
- src/server.cc
- src/util/jpeg_resolution.cc
- src/util/string_converter.cc
- src/util/tools.cc
Found with google-readability-casting
Required manual editing.
> [clang-tidy] fix remaining cast issues

- src/autoscan_inotify.h
- src/config/config_generator.h
- src/config/config_manager.cc
- src/config/config_manager.h
- src/content_manager.h
- src/file_request_handler.cc
- src/layout/fallback_layout.h
- src/main.cc
- src/metadata/fanart_handler.cc
- src/metadata/fanart_handler.h
- src/metadata/matroska_handler.cc
- src/metadata/matroska_handler.h
- src/metadata/taglib_handler.cc
- src/metadata/taglib_handler.h
- src/onlineservice/online_service_helper.h
- src/search_handler.h
- src/server.h
- src/storage/sql_storage.h
- src/storage/sqlite3/sqlite3_storage.h
- src/upnp_cds.cc
- src/upnp_cds.h
- src/upnp_cm.cc
- src/upnp_cm.h
- src/upnp_mrreg.cc
- src/upnp_mrreg.h
- src/upnp_xml.h
- src/web/pages.h
- src/web/web_request_handler.h
Found with readability-convert-member-functions-to-static
Found with readability-static-accessed-through-instance
> [clang-tidy] convert member functions to static

- src/iohandler/curl_io_handler.cc
Found with modernize-unary-static-assert
> [clang-tidy] use newer single argument C++17 static_assert

- src/metadata/matroska_handler.cc
Found with hicpp-explicit-conversions
> [clang-tidy] add explicit to single argument constructors

- src/web/auth.cc
Avoids bogus hicpp-member-init warning.
> [clang-tidy] convert get_time to std::chrono

- src/config/config_manager.cc
- src/iohandler/file_io_handler.cc
- src/storage/sqlite3/sqlite3_storage.cc
Found with clang's -Wextra-semi-stmt
> remove extra semicolon in statements

- src/scripting/runtime.cc
Found with clang's -Wmissing-noreturn
> add suggested noreturn

- src/config/config_manager.cc
While booting this project for the first time, I ran into the following error:
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
```
It appears this has been addressed before (8ac412a) but that commit did not discover these two areas in the configuration code where the same error arises.
> fix std::string with nullptr in MySQL code

- src/cds_objects.h
- src/config/config_options.h
- src/content_manager.h
- src/layout/fallback_layout.h
- src/scripting/import_script.h
- src/storage/mysql/mysql_storage.h
- src/storage/sql_storage.h
- src/storage/sqlite3/sqlite3_storage.h
- src/web/session_manager.h
> remove virtual from overriden functions

- CMakeLists.txt
- src/main.cc
- src/metadata/fanart_handler.cc
Greetings.  Lots has changed since last I peeked, fancy C++ idioms and long link times...
Three fixes in order of priority:
1.  This most recent master was completely broken for me, removing almost all my media.  I saw errors thrown, saying "/folder.jpg" was a filesystem exception.  The problem is twofold.  First, the check for fanart shouldn't throw an exception.  Second, the fanart path was bogus.  The `/` operator isn't just "+ for paths", it has semantics, and the leading "/" in the two `names` blows away the base path if it is rooted.  I've lost track of how "fanart" differs from associating images with albums; if this code is still important it could stand a more diverse set of names and some case-insensitive matching, but at least now it doesn't kill a scan.
2. The spdlog I'm using …
> spdlog build path improvement, fanart semantic and exception fix, and spdlog flushing

- src/config/config_manager.cc
Child elements of the <transcoding> node in the .xml were not being parsed correctly (<transcode> and <profile> elements were parsed as direct descendents of <transcoding>, not as children of <mimetype-profile-mappings> and <profiles> respectively.
Prior to this, I noticed gerbera did not find any of my transcoding profiles; upon further investigation I discovered this was causing profiles to be ignored.
> Fix config parsing for <transcoding> parameters

- src/util/tools.cc
If building without FFmpeg support there was a compilation error -
MALLOC() instead of malloc() in one place. (see e373740)
> fix compilation error

- src/upnp_xml.cc
- src/upnp_xml.h
- test/test_upnp/test_upnp_xml.cc
Apparently VLC requires a full URL to load subtitle properly
(treating as local path otherwise).
Add sec:CaptionInfoEx tag unconditionally as other UPNP servers do.
> Return full URL of the subtitle (#744)

- CMakeLists.txt
- src/file_request_handler.cc
- src/util/tools.cc
- src/util/tools.h
- src/util/upnp_headers.cc
- src/util/upnp_headers.h
- src/web/web_request_handler.cc
- test/test_handler/test_http_protocol_helper.cc
- use dictionary for headers (uniqueness of key)
- simplify unit-test (sequence does no longer matter)
- readHeaders function can later be reused
> improve util upnp headers

- CONTRIBUTING.md
- src/metadata/ffmpeg_handler.cc
- src/metadata/matroska_handler.cc
- src/metadata/matroska_handler.h
- src/metadata/taglib_handler.cc
Minor refactoring to build without warnings with Gcc 9 and latest
libraries.
Fixed undefined behavior in matroska_handler and taglib_handler.
> Warnings-free build with gcc 9.

- src/metadata/matroska_handler.cc
- src/metadata/matroska_handler.h
- src/metadata/taglib_handler.cc
- src/metadata/taglib_handler.h
- src/onlineservice/atrailers_service.cc
- src/onlineservice/atrailers_service.h
- src/onlineservice/online_service.h
- src/onlineservice/sopcast_service.cc
- src/onlineservice/sopcast_service.h
- src/storage/mysql/mysql_storage.h
- src/upnp_xml.cc
const allows the compiler to optimize these functions better.
> Change several other functions to const manually

- src/upnp_xml.cc
Seems this got lost during some refactoring.
Only set composer, conductor, orchestra and date data if we have that
information.
> Set creator on musicAlbum (again)

- src/util/tools.cc
- test/test_util/CMakeLists.txt
- test/test_util/test_tools.cc
Not sure whether limit should be 999 or just 99 for 2-digit formatting...
> Replaced snprintf which caused a warning with fmt

- gerbera-web/test/client/fixtures/external-url.json
- gerbera-web/test/client/gerbera.items.spec.js
- gerbera-web/test/client/jquery.gerbera.editor.spec.js
- web/js/jquery.gerbera.editor.js
Seems a straightforward change in Javascript code. Server code seems capable of changing mime type.
Code is backward compatible with Gerbera 1.4.0
> Enable editing mime-type for externalUrl (fixes #790)

- src/layout/fallback_layout.cc
saw this when fixing issue #692. I see no benefit of passing last subdir of added location to virtual path too.
**Example:**
config.xml:
```
...
<autoscan use-inotify="auto">
<directory location="/home/.../Videos" mode="inotify" level="full" recursive="yes" hidden-files="no"/>
</autoscan>
...
```
Before virtual path: /Video/Directories/**Videos**/Action/...`
With change: /Video/Directories/Action/...
> shortten virtual path to videos

- CMakeLists.txt
- scripts/install-spdlog.sh
Finding fmt explicitly is not needed since it's handled by spdlog's
CMake files.
Fixes: #691.
> Don't override interface flags for spdlog.

- src/upnp_cds.cc
when you think long enough about something, sometimes you find the correct solution :-)
I have verified the specs and they are providing the encoding, even in the example codes...
> fix: #807 add missing UTF-8 encoding

- src/content_manager.cc
This avoids gaps and handles the initial state as well.  Fixes https://github.com/gerbera/gerbera/issues/763
> Always scan inotify autoscan locations after startup

- src/upnp_cds.cc
- src/util/upnp_quirks.cc
- src/util/upnp_quirks.h
Namespace is still used in UpnpXMLBuilder::renderCaptionInfo for videos.
> Ensure all xml-namespaces are declared (fixes #819)

- src/scripting/script.cc
- src/util/tools.cc
If tracknumber starts with an non-digit character std::stoi throws an std::invalid_argument exception.
Moved the check to the existing tools function "stoi_string" making it available for other places with same issues.
> Avoid server abort when tracknumber starts with non-digit character

- src/storage/sql_storage.cc
replaced more std::stoi by stoi_string to avoid exception when reading unformatted data. May be a bit slower but is much safer
> avoid exceptions

- src/metadata/matroska_handler.cc
More resiliency for badly constructed files.
> Check the other dynamic_casts in matroska_handler

- src/transcoding/transcode_ext_handler.cc
- src/util/tools.cc
- src/util/tools.h
This allows us to pass metadata from the import script to the transcoder via the object title.  It's not much, but it's enough to e.g. signal a resume offset for otherwise non-seekable content.
Also, fix a string length bug that was corrupting the range parameter
> Add title param to external transcoder

- doc/config-import.rst
- doc/scripting.rst
config-import:
added taglib and ffmpeg libraries for metadata extraction usage
added example for ffmpeg auxdata configuration
removed tags from the examples that are part of UPnP 
removed tags from the examples that are not part of ID3v2.4
scripting:
added taglib and ffmpeg libraries for metadata extraction usage
fixed some copy/paste, formatting, and spell errors
> doc change: ffmpeg metadata extraction facilites

- src/metadata/ffmpeg_handler.cc
- src/metadata/ffmpeg_handler.h
Had spontaneous crashes / assertions in libc. Fortunately was not a low hanging fruit.
> Fixed use of uninitialized pthread_mutex.

- src/util/string_converter.cc
iconv_t is sometimes a pointer and other times an int. Remove casting
to make it work with the latter.
> remove iconv casting

- src/util/tools.cc
sizeof(struct sockaddr_in6) > sizeof(struct sockaddr)
> Call to getnameinfo needs to use the size of the actual address struct

- src/content_manager.cc
If we ignore these errors, the following can happen:
1. The layout type fails initialization
2. An object is added
3. The object is not added to the virtual layout
After this happens, the object will never again have an opportunity
to be added to the virtual layout unless it is manually deleted
from the database.  This could be observed while developing the
JS import script, for example.
By propagating failure, we ensure that adding the object will fail
and will thus be reattempted later.
> Propagate layout init errors

- doc/compile.rst
- src/upnp_xml.cc
After spending a couple of hours i succeed to build gerbera on Ubuntu 18.04 LTS. I'm not sure if every package is really needed (like g++-8). Compiling with g++-8 runs into errors, clang++ works fine,
> Instructions to build gerbera on Ubuntu 18.04

- src/metadata/ffmpeg_handler.h
error: invalid application of ‘sizeof’ to incomplete type ‘IOHandler’
> Fix incomplete type iohandler with Ninja generator

- src/content_manager.cc
`gsl::not_null` anyone? :D
Looks like handling of this `adir` is just patched up whenever a problem comes... For example, why can `CMRescanDirectoryTask` be constructed with `nullptr` if it will do nothing in `run()`? I don't see anyone touches it...
> getAutoscanDirectory may return nullptr

- src/web/clients.cc
A duration cast is missing.
Fixes: https://github.com/gerbera/gerbera/issues/880
> fix compilation with libcxx

- src/web/clients.cc
Found with clang's -Wrange-loop-analysis:
src/web/clients.cc:58:21: warning: loop variable 'obj' of type
'const ClientCacheEntry' creates a copy from type 'const ClientCacheEntry'
[-Wrange-loop-construct]
> add missing reference for loop

- src/util/process.h
- src/util/process_executor.h
Error with pid_t.
Found with musl + libcxx.
> add missing unistd header

- src/cds_objects.cc
Changing description after object creation was not possible anymore (another issue discover alongside #897). 
== operatior for map should do what we want:
`Checks if the contents of lhs and rhs are equal, that is, they have the same number of elements and each element in lhs compares equal with the element in rhs at the same position`
> Metadata comparison does not work

- src/autoscan_inotify.cc
When renaming a directory the old files where not deleted from the database anymore. Issue was introduced with fs::path. Line 205 was older but makes no sense.
Also cleaned up the log messages (path to string instead of c_str)
> Fix autoscan when renaming a directory

- src/util/string_converter.cc
iconv_t can be a pointer or an int. Normally the former but sometimes
the latter.
Silences warnings about using nullptr.
>  use {} for cd

- src/storage/sql_storage.cc
When exploring how metadata is stored and used found that in a751fea028a025f50a18e658d455e4d49a1a0128 code was torn apart and essentially metadata was compared with aux data.
Also calling `std::equal` without range check is dangerous and just not needed.
> FIxed comparison to wrong object.

- src/scripting/script.cc
When loading of script fails the error message is not shown (fixes #869)
> Show duk script error message on load

- src/metadata/taglib_handler.cc
- src/util/tools.cc
Use toString() method from TagLib to get all item instead of first.
Also contains a fix for url_encode which failed with multi-byte UTF-8 characters.
This should fix #758, #759
> Load multivalue tags if supported instead of first item

- src/util/upnp_headers.cc
This header was introduced with 1.14. The check as is will match on
1.12 versions.
> fix upnp header include

- src/content_manager.cc
- src/serve_request_handler.cc
- src/util/tools.cc
- src/util/tools.h
I noticed (on my systems, at least) that when gerbera is built with `libmagic`, symlinks to files are not followed during the MIME type identification process, even when `CFG_IMPORT_FOLLOW_SYMLINKS` is set. This causes symlinks to media files to be identified as `inode/symlink` rather than the MIME of the target. 
(By contrast, symlinks to directories containing non-symlink files are successfully identified as expected.) 
I've added the `MAGIC_SYMLINK` flag for the `magic_open()` call which causes `libmagic` to follow symlinks when identifying the MIME type of a file. I'm not sure if passing the symlink config setting to `getMIMETypeFromFile()` is the most elegant fix (first time contributor to gerbera here), but I thought I'd offer my solution.
> fixed mime type retrieval for symlinks with libmagic

- src/content_manager.cc
Looks like this has been broken since std::string was introduced and
null/empty behaviour changed a bit.
Thanks to @reffu42 for reporting
Fixes: gerbera/gerbera#986
> UI: Dont update mimetype to empty

- src/metadata/ffmpeg_handler.cc
> FFMPEG-metadata: Ensure date content can be parsed

- src/storage/sql_storage.cc
Has to be true if resources contains at least one item
`error: Exception caught: tried to create object without at least one resource file://home/karl/Source/gerbera/src/storage/sql_storage.cc line:952 function:createObjectFromRow`
> Fix resource_zero_ok

- src/metadata/exiv2_handler.cc
- src/metadata/ffmpeg_handler.cc
- src/metadata/matroska_handler.cc
- src/metadata/metacontent_handler.cc
- src/metadata/metadata_handler.cc
- src/metadata/metadata_handler.h
- src/metadata/taglib_handler.cc
- src/scripting/script.cc
- test/scripting/mock/script_test_fixture.cc
Allows usage of structured binding declarations as well as simplifying
the code slightly.
> convert MT_KEYS and RES_KEYS to std::pair

- CMakeLists.txt
- src/cds_objects.h
- src/content_manager.cc
- src/metadata/exiv2_handler.cc
- src/metadata/ffmpeg_handler.cc
- src/metadata/libexif_handler.cc
- src/metadata/matroska_handler.cc
- src/metadata/metacontent_handler.cc
- src/metadata/metadata_handler.h
- src/metadata/taglib_handler.cc
- src/onlineservice/atrailers_content_handler.cc
- src/onlineservice/sopcast_content_handler.cc
- src/scripting/script.cc
- src/scripting/script_names.h
- src/upnp_xml.cc
- src/web/add_object.cc
- src/web/edit_load.cc
- test/core/test_upnp_xml.cc
- test/scripting/mock/script_test_fixture.cc
Move call to `MetadataHandler::getMetaFieldName` into `CdsObject::get/setMetadata`.
Avoids propagation of internal structure of `mt_keys`.
Additionally move names for scripting variables into separate array.
> Move call to MetadataHandler::getMetaFieldName into CdsObject::get/setMetadata

- src/config/config_manager.h
- src/metadata/metadata_handler.cc
- src/web/clients.cc
convert keys to use std::pair
Small code simplification. Also allows using std::get, which demands
constant expressions.
replace std::map with constexpr std::array 
The map is never modified.
std::string replaced with const char * as the former is not constexpr
until C++20.
And yes I've tested this. Seems to work very well. Maybe because my UPnP client caches some stuff...
> clang warning fixes

- src/config/config_manager.cc
- src/config/config_manager.h
- src/config/config_options.cc
- src/config/config_setup.cc
- src/config/config_setup.h
- src/config/directory_tweak.cc
- src/config/directory_tweak.h
- src/content_manager.h
- src/metadata/ffmpeg_handler.cc
- src/upnp_cds.cc
- src/upnp_cds.h
- src/util/xml_to_json.h
- src/web/clients.cc
- src/web/config_load.cc
- src/web/pages.h
I think https://github.com/gerbera/gerbera/commit/d7c84cc9e967528ae91e62f513c8385248721746 introduced a bunch of clang-tidy fixes.
> run through clang-tidy

- src/autoscan.h
- src/autoscan_inotify.h
- src/cds_objects.h
- src/common.h
Found with bugprone-macro-parentheses
Instead of that, just use a constexpr function. Looks cleaner.
> use parentheses in macros

- src/onlineservice/lastfm_scrobbler.cc
The lastfm scrobbler enabled via cmake option `-DWITH_LASTFM=1` would not build due to mismatches in the function signatures. The scrobbler passed strings but the functions expect enum `metadata_fields_t`
I have yet to test whether the scrobbler actually works, but at least the build succeeds [(openSUSE 15.2 package here)](https://download.opensuse.org/repositories/home:/lineinthesand/openSUSE_Leap_15.2/).
> Fix lastfm scrobbler build

- README.md
FreeBSD 11.0 is since long end of life and all dependencies are available as packages or in ports tree
> Docs: Remove outdated FreeBSD instructions

- cmake/FindSystemd.cmake
- cmake/Findlibuuid.cmake
Include is the old way apparently, not that you would know that as CMake's docs are useless
This should fix warnings like:
The package name passed to `find_package_handle_standard_args` (PkgConfig)
does not match the name of the calling package (Blah).
> CMake: find_package for pkgconfig

- src/cds_objects.cc
- src/cds_objects.h
- src/content_manager.cc
- src/onlineservice/atrailers_content_handler.cc
- src/onlineservice/sopcast_content_handler.cc
- src/web/add_object.cc
- src/web/items.cc
- test/core/test_upnp_xml.cc
Now they are just POCOs
DB access was only used for virtualUrls, and removing that functionality
seems to have no impact.
> Remove database pointer from CDS Objects

- .github/workflows/clang-format.yml
Looks like there were some bugs to allow false passing
See #1073, and #1074 for context
> Actions: Bump clang-format lint action version

- src/config/config_manager.cc
- src/config/config_manager.h
- src/config/config_setup.cc
- src/config/config_setup.h
Found with cppcoreguidelines-avoid-non-const-global-variables
> clang-tidy: add const to several globals

- src/content_manager.cc
- src/server.cc
When UpnpInit2 fails we should should still shutdown cleanly
Replicated by trying to start gerbera without IPv4
Issue #1090
> Shutdown: Check pointers before access

- src/metadata/ffmpeg_handler.cc
- src/metadata/taglib_handler.cc
- src/onlineservice/lastfm_scrobbler.cc
- src/util/tools.cc
- src/util/tools.h
- test/util/test_tools.cc
- avoid using deprecated taglib audioProps->length()
- unify milliseconds to upnp duration string conversion
- remove cap to 999 hours, upnp spec does not enforce this, other services are also not doing this (this was only done in one of our paths)
- rename HMSToSeconds to HMSFToMilliseconds, so it matches millisecondsToHMSF
> improve duration and bitrate calculations

- src/metadata/ffmpeg_handler.cc
I found that DSF files are not sorted by track number on UPNP_CLASS_CONTAINER_MUSIC_ALBUM.
So I propose to update FFmpeg handler to set it if needed. 
I ever see 2 formats of track number on commercial DSF files. One is "[track number]", e.g, "1", and the other is "[track number]/[total tracks]", e.g. "1/10". I confirmed this patch can set track number correctly for both of the 2 formats.
Furthermore, I want to import some more meta data types on FFmpeg handler refer to [FFmpeg Metadata#mp3](https://wiki.multimedia.cx/index.php/FFmpeg_Metadata).
> Set track number if needed and support some more meta data on FFmpeg handler.

- src/server.cc
This binds to all interfaces instead of just one.
ping @medoc92 I haven't actually tested this. I remember an issue with docker where libnpupnp did not work properly. It only bound to an IPv6 interface or something.
Nevertheless I do believe this should work properly based on my reading of the npupnp code.
> pass "*" to UpnpInit2 instead of nullptr

- src/config/client_config.cc
- src/file_request_handler.cc
- src/server.cc
- src/util/upnp_clients.cc
- src/util/upnp_clients.h
- src/web/clients.cc
- test/util/CMakeLists.txt
- test/util/test_upnp_clients.cc
Refactor User-Agent lookup.
Some client do not report the same User-Agent for UPnP services and file request, therefore we use what is cached previously via UpnpActionRequest to keep the code simple.
The main idea here is that before FileRequest (image/video file access) is called, an UPnP service (e.g. doBrowse) is called. From the first call we get the client info and cache it, afterwards we can reuse that info.
VLC example User-Agent info:
- ActionRequest: `Linux/5.9.0-5-amd64, UPnP/1.0, Portable SDK for UPnP devices/1.8.4`
- FileRequest: `VLC/3.0.11.1 LibVLC/3.0.11.1`
Same happens with Samsung TVs:
- ActionRequest: `DLNADOC/1.50 SEC_HHP_[TV] Samsung Q70 Series/1.0 UPnP/1.0`
- FileRequest: `samsung-agent/1.1`
I guess the reason about this is, that clients use different libraries for …
> fix UserAgent lookup, different between UpnP services and file request

- src/iohandler/process_io_handler.cc
- src/util/tools.cc
- src/util/tools.h
gettimeofday is deprecated under POSIX and is not year 2038 safe.
This is C++17. timespec_get should be supported.
> replace gettimeofday with timespec_get

- src/config/config_generator.cc
- test/config/CMakeLists.txt
- test/config/fixtures/mock-config-all.xml
- test/config/fixtures/mock-config-minimal.xml
- test/config/fixtures/mock-import-magic-js-online.xml
- test/config/fixtures/mock-import-magic-js.xml
- test/config/fixtures/mock-import-magic.xml
- test/config/fixtures/mock-import-mappings.xml
- test/config/fixtures/mock-import-none.xml
- test/config/test_configmanager.cc
- test/core/CMakeLists.txt
- test/database/CMakeLists.txt
- test/database/import.cc
- test/database/main.cc
- test/database/mysql_config_fake.h
This should not be needed but LibMagic fails to identify these files
(as of 2021/01).
Reorder the map alphabetically.
Fixes: https://github.com/gerbera/gerbera/issues/1130
Fixes: https://github.com/gerbera/gerbera/issues/1041
> Config: Map .ts files to video/mp2t by default

- src/config/config_generator.cc
`CFG_IMPORT_SCRIPTING_CHARSET` is only defined when JavaScript support
is enabled. Otherwise the build fails with:
```
src/config/config_generator.cc: In static member function ‘static void ConfigGenerator::generateImport(const std::filesystem::__cxx11::path&, const std::filesystem::__cxx11::path&)’:
src/config/config_generator.cc:258:14: error: ‘CFG_IMPORT_SCRIPTING_CHARSET’ was not declared in this scope; did you mean ‘CFG_IMPORT_LIBOPTS_ID3_CHARSET’?
258 |     setValue(CFG_IMPORT_SCRIPTING_CHARSET);
|              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
|              CFG_IMPORT_LIBOPTS_ID3_CHARSET
make[4]: *** [CMakeFiles/libgerbera.dir/build.make:142: CMakeFiles/libgerbera.dir/src/config/config_generator.cc.o] Error
```
> Fix compilation without JavaScript support

- src/content/content_manager.h
Otherwise, build fails with musl-based GCC 9.3.0 toolchain:
```
In file included from src/content/layout/layout.cc:28:
src/content/content_manager.h:320:21: error: ‘ScriptingRuntime’ was not declared in this scope
320 |     std::shared_ptr<ScriptingRuntime> scripting_runtime;
|                     ^~~~~~~~~~~~~~~~
src/content/content_manager.h:320:37: error: template argument 1 is invalid
320 |     std::shared_ptr<ScriptingRuntime> scripting_runtime;
|                                     ^
make[4]: *** [CMakeFiles/libgerbera.dir/build.make:285: CMakeFiles/libgerbera.dir/src/content/layout/layout.cc.o] Error 1
```
> Fix missing forward declaration of ScriptingRuntime

- cmake/Findpugixml.cmake
> cmake/Findpugixml.cmake: fix typo

- src/upnp_xml.cc
- src/upnp_xml.h
- src/util/upnp_quirks.cc
- test/core/test_upnp_xml.cc
Remove unused method
Found this while researching on #1165 
There is still a bit of hardcoding for srt files which should be bypassed for explicit resources already.
> Use subtitle resource for SAMSUNG clients if available

- .github/workflows/docker.yml
By running all the builds in a single job we dont have to worry about building a manifest list ourselves
In the current situation whichever job finishes last overwrites the tag to point at its image, instead of building a multi-arch list.
Practically this means if you run `gerbera/gerbera:master` on amd64 currently, it tries to run the armv8 image :-1:
> Revert docker build matrix

- Dockerfile
The lovely alpine people have now added libupnp and duktape packages
(and gerbera itself!) with 3.13, so we no longer have to build them.
Add git and bash to builder as needed for version and db header gen.
> Docker: Update to Alpine 3.13 base

- src/config/config.h
- src/content/onlineservice/online_service.h
- src/content/scripting/script.h
- src/metadata/metadata_handler.h
- src/transcoding/transcoding.h
typedef enum is meant to give the enum an alternate name. But these are
anonymous enums. Just place the name up top.
Avoids clang-tidy's modernize-use-using checks.
> remove typedef enum

- .github/workflows/docker.yml
- .github/workflows/publish-deb.yml
checkout@v2 fetches only a single commit by default, which makes us unable to generate a version from tag info
> Fix Docker logged version info

- CMakeLists.txt
These properties are not inherited when set at target level, so by
setting them here our targets pick them up.
Also tidy up arguments to use YES/NO and fix alignment.
Fixes: #1175
> CMake: set C++ standard globally

- src/util/upnp_clients.cc
Also avoids uninitialized struct memory.
> Get rid of compiler warning on default constructor.

- src/metadata/matroska_handler.cc
This PR fixes the format for dates of matroska handler. Currently the format is stored as a value.
> Fixed formatting matroska date values

- src/util/mime.cc
Fix the following build failure:
```
/home/fabrice/buildroot/output/build/gerbera-f10c11e8fd6ac9baf6b3d72995e9c6123b7210f1/src/util/mime.cc: In destructor 'virtual Mime::~Mime()':
/home/fabrice/buildroot/output/build/gerbera-f10c11e8fd6ac9baf6b3d72995e9c6123b7210f1/src/util/mime.cc:58:9: error: 'magicCookie' was not declared in this scope
58 |     if (magicCookie) {
|         ^~~~~~~~~~~
/home/fabrice/buildroot/output/build/gerbera-f10c11e8fd6ac9baf6b3d72995e9c6123b7210f1/src/util/mime.cc:59:9: error: 'magic_close' was not declared in this scope
59 |         magic_close(magicCookie);
|         ^~~~~~~~~~~
```
> src/util/mime.cc: fix build without magic

- src/content/layout/layout.h
- src/metadata/matroska_handler.cc
- src/transcoding/transcode_handler.h
- src/web/web_request_handler.h
last commit was done manually. I pay have messed something up.
> clang-tidy stuff

- src/util/tools.h
Fixes build with gcc11
/src/util/tools.h:165:6: error: 'optional' in na
mespace 'std' does not name a template type
|   165 | std::optional<std::vector<std::byte>> readBinaryFile(const fs::path& path);
|       |      ^~~~~~~~
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> include <optional> header

- src/database/sqlite3/sqlite_database.cc
- src/database/sqlite3/sqlite_database.h
fixes #1272: This only happened when you first created the database or after recovery.
> Ensure sqlite is in correct mode for recovery and initialization

- scripts/debian/postinst
This commit removes the '--no-create-homedir' argument from the
adduser command in the postinst script used in the Debian package.
Without an existing homedir the Gerbera service won't start.
This is part of the fix for #1264.
> Do make a homedir for the gerbera user in Debian postinst

- CMakeLists.txt
- scripts/install-pupnp.sh
If control points do not correctly unsubscribe this can result in
libupnp threads hanging.
https://github.com/pupnp/pupnp/discussions/245#discussioncomment-448988
https://github.com/pupnp/pupnp/commit/32cffb5bb55a650b1eb962c6fe2e58e6bf4fe2c5
> Warn if blocking-tcp is not disabled in libupnp

- src/config/config_generator.cc
- src/config/config_generator.h
- src/main.cc
Avoids allocation of objects without need.
> Remove statics from ConfigGenerator elements

- src/database/sql_database.cc
Useless select for every row load without a ref_id
> Stop attempting to load metadata for ID=0

- src/main.cc
- src/util/mime.cc
13 years ago in the original mediatomb, a hack was done to allow printf() of a NULL pointer to print "NULL" rather than crash, on Solaris
That was done by mapping *0=0 behind the scenes, which makes a null dereference no longer an immediate crash, which it otherwise is on Solaroid machines, and quite deliberately
No, just, no - a nullptr dereference is a bug
Removed
And then I rather quickly found a crash which was hiding behind a totally messed up stack otherwise
Mime::fileToMimeType was blindly dereferencing a nullptr to see if it pointed to an empty string
> Fix crash in filetoMimeType and remove ancient Solaris hack

- src/database/mysql/mysql_database.cc
Error during the very first startup when the DB tables should be created:
>Mysql: error while creating db: mysql_error (1065): "Query was empty"
The problem is that after the mysql.sql file content is split by `';'`, during the last loop the `statement` variable will only contain a newline character, which causes the mentioned MySQL error.
https://github.com/gerbera/gerbera/blob/d6e57d1211a813941ef23978f7a6a65c0b8a7cfb/src/database/mysql/mysql_database.cc#L212
> fix MySQL initial setup

- src/cds_objects.h
- src/config/config_generator.cc
- src/config/config_manager.cc
- src/content/layout/builtin_layout.cc
- src/content/onlineservice/online_service_helper.cc
there are several places in the code that implicitly convert an
fs::path to an std::string. This breaks on platforms like Windows
where the paths are wstrings. Remove some of these implicit
conversions and make others explicit.
> fs::path conversions

- .github/workflows/publish-deb.yml
- doc/install.rst
- scripts/debian/build-deb.sh
If you are using bintray, please switch to the new repos at:
- https://gerbera.jfrog.io/artifactory/debian
- https://gerbera.jfrog.io/artifactory/debian-git
Fixes: #1200
> Migrate from Bintray to JFrog Artifactory

- src/web/clients.cc
They are not available under MinGW. It's also easier with fmt.
> web/clients: remove C string functions

- doc/supported-devices.rst
- scripts/js/common.js
- src/content/content_manager.cc
- src/database/search_handler.cc
- src/database/sql_database.cc
- src/upnp_cds.cc
- src/upnp_xml.cc
- test/core/test_searchhandler.cc
Container search is looking for 'dc:title' which has to be set on import
Search operator `derivedfrom` should also match base class (e.g. object.container.album.musicAlbum)
fixes #1287 
fixes #1281
> Allow search for albums and genre and other containers

- doc/install.rst
Changed link to https://gerbera.jfrog.io
> Documentation still points to bintray.com

- src/file_request_handler.cc
Temporary fix until implemented in npupnp (expected in version 4.1.3).
> fix UPNP_USING_CHUNKED breaks npupnp compatibility

- src/main.cc
setresgid() and setresuid() are not present on Illumos systems
Use the OS X codepath in this case
There may be other OSs where this is also an issue, FWIW
> Work around undefined syscalls on solaroid systems

- src/util/thread_runner.h
The default scoping on solaroid systems is in fact PTHREAD_SCOPE_SYSTEM
plus, setting PTHREAD_EXPLICIT_SCHED requires elevated priveleges, thus the default gerbera
behavior would require elevated priveleges, which is poor security practice
fixes #1382 for illumos
> Avoid needless process elevation requirement on illumos

- src/database/database.h
- src/database/search_handler.cc
- src/database/search_handler.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/upnp_cds.cc
- src/upnp_xml.cc
- test/core/test_searchhandler.cc
Reworked select statements in `sql_database.cc` on the way
> Implement UPnP SortCriteria

- src/config/config_setup.cc
> remove std::distance where empty is sufficient

- src/config/config_options.cc
clang-tidy gets confused by this if and recommends using emplace_back,
which is not the best idea. Just reduce to a single push_back.
Also add a reserve for efficiency.
> remove push_back branch

- src/config/client_config.cc
- src/config/config_generator.cc
- src/config/config_manager.cc
- src/config/config_manager.h
- src/config/config_options.cc
- src/config/config_setup.cc
- src/config/config_setup.h
- src/config/directory_tweak.cc
- src/config/directory_tweak.h
- src/content/autoscan_list.cc
- src/content/content_manager.cc
- src/database/search_handler.cc
- src/database/sql_database.cc
- src/web/directories.cc
find() is faster than count as the loop is broken once an item is
encountered. Since all of these are used in boolean context, just revert
to doing find.
Also removed a lambda from a really long find_if.
> Revert "replace find() end() comparisons with count()"

- src/metadata/taglib_handler.cc
Fix: Concatenate multivalue field with entrySeparator and not space
In ID3v2.4 tags multiple values are allowed (see also #1425).
These values are stored as null separated list in the mp3 file tag.
If taglib is called with textFrame->toString() the multiple values are concatenated with a space.
To concatenate these values with the defined entrySeparater this call is changed to textFrame->fieldList().toString(entrySeparator).
For TXXX tags the first element in the fieldList is the subtag name and extracted separately. The other entries are concatenated with the entrySeparator.
Note: Unfortunately I'm not an C++ programmer, so please revise and correct my code if not optimal. Also I just did only a limited test depth regarding mp3 files and taglib versions.
> Concatenate multivalue field with entrySeparator

- src/content/content_manager.cc
- src/content/onlineservice/task_processor.cc
- src/content/update_manager.cc
- src/database/sqlite3/sqlite_database.cc
- src/database/sqlite3/sqlite_database.h
- src/main.cc
- src/server.cc
- src/server.h
- src/upnp_cds.cc
- src/util/thread_runner.h
- src/util/timer.cc
Depending on startup order either `threadRunner` property may be uninitialized
or lock was released before thread blocked on condition.
I hope the witch hunt is over and my random crashes on startup are gone. 
fixes #1405
> Synchronize threads properly

- CMakeLists.txt
- src/main.cc
std needs the GNU variants for kill(), a bunch of netdb.h stuff, fo
functions, and maybe some others.
> add support for Cygwin

- src/metadata/ffmpeg_handler.cc
- src/web/session_manager.cc
This throws -Wctad-maybe-unsupported under clang as gcc's libstdc++
seems to not implement it properly.
> clang: remove CTAD in some places

- src/cds_objects.cc
- src/config/config_setup.cc
- src/content/content_manager.cc
- src/content/onlineservice/atrailers_content_handler.cc
- src/content/onlineservice/sopcast_content_handler.cc
- src/content/scripting/script.cc
- src/database/mysql/mysql_database.cc
- src/database/search_handler.cc
- src/database/sql_database.cc
- src/database/sqlite3/sqlite_database.cc
- src/device_description_handler.cc
- src/file_request_handler.cc
- src/metadata/libexif_handler.cc
- src/metadata/metacontent_handler.cc
- src/serve_request_handler.cc
- src/transcoding/transcode_ext_handler.cc
- src/url_request_handler.cc
- src/util/tools.cc
- src/web/add_object.cc
- src/web/web_request_handler.cc
Found with -Wreturn-std-move-in-c++11
> clang: add missing moves

- src/request_handler.cc
Fixes #1468 
broken in when replacing zmm::string with std::string
https://github.com/gerbera/gerbera/commit/a58d00030fd102b0083e3b133bbff321031134ef
> Search query sign from beginning

- src/database/search_handler.h
There's no need for it to be a const reference. GCC's -fanalyzer also
complains about it when used with make_unique.
> pass SearchLexer by value

- src/config/config_manager.cc
- src/content/onlineservice/online_service.cc
- src/content/onlineservice/online_service.h
vector(x) and vector(); resize() are the same.
Also fixes some GCC -fanalyzer NULL pointer issue.
> move resize option to constructor

- src/action_request.cc
- src/config/config_manager.cc
- src/content/onlineservice/curl_online_service.cc
- src/content/onlineservice/online_service.h
- src/content/update_manager.cc
- src/upnp_xml.cc
GCC's -fanalyzer complains that null pointers are created otherwise.
Some cleanup posibilities showed up.
> initialize several unique_ptrs

- src/config/client_config.h
- src/config/config_setup.h
- src/config/directory_tweak.h
- src/content/autoscan.h
- src/content/onlineservice/online_service.cc
- src/content/onlineservice/online_service.h
- src/database/sqlite3/sqlite_database.h
- src/util/thread_executor.h
- src/util/timer.h
- src/web/directories.cc
- src/web/pages.h
- src/web/session_manager.h
Found with cppcoreguidelines-pro-type-member-init
> clang-tidy: initialize some members

- src/main.cc
Found with modernize-deprecated-headers
> clang-tidy: C to C++ headers

- src/util/xml_to_json.cc
Found with readability-qualified-auto
> clang-tidy: use auto&& to avoid warning

- src/content/autoscan.h
- src/database/database.h
- src/main.cc
Found with cppcoreguidelines-narrowing-conversions
> clang-tidy: fix some narrowing conversions

- src/iohandler/mem_io_handler.cc
- src/util/tools.cc
> clang-tidy: get rid of some long and short

- src/content/onlineservice/atrailers_content_handler.cc
- src/content/onlineservice/atrailers_content_handler.h
- src/content/onlineservice/curl_online_service.cc
- src/content/onlineservice/curl_online_service.h
- src/content/onlineservice/sopcast_content_handler.cc
- src/content/onlineservice/sopcast_content_handler.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/iohandler/buffered_io_handler.cc
- src/iohandler/buffered_io_handler.h
- src/iohandler/io_handler_chainer.cc
- src/iohandler/io_handler_chainer.h
- src/transcoding/transcode_ext_handler.cc
- src/util/upnp_clients.cc
- src/util/upnp_clients.h
- src/util/upnp_quirks.cc
- src/util/upnp_quirks.h
Since the copy stuff is deleted, this is safe to do.
Found with google-runtime-references.
> clang-tidy: pass unique_ptr by value

- src/config/config_generator.cc
- src/config/config_generator.h
- src/content/content_manager.cc
- src/content/content_manager.h
- src/database/search_handler.h
- src/metadata/ffmpeg_handler.cc
- src/metadata/ffmpeg_handler.h
Found with google-runtime-references
> clangh-tidy: non const reference removal

- src/metadata/matroska_handler.cc
Found with Wreturn-std-move-in-c++11
> clang: add missing move

- src/metadata/ffmpeg_handler.cc
It's only used with ffmpegthumbnailer
> avoid unused template warning

- src/cds_objects.h
- src/config/config_options.h
- src/config/config_setup.h
- src/content/layout/layout.h
- src/content/onlineservice/curl_online_service.h
- src/database/search_handler.h
- src/database/sql_database.h
- src/database/sqlite3/sqlite_database.h
- src/metadata/metadata_handler.h
- src/request_handler.h
- src/transcoding/transcode_handler.h
- src/util/generic_task.h
Found with Wnon-virtual-dtor and delete-non-abstract-non-virtual-dtor
These seem to be needed by smart pointers.
> add back several defaulted destructors

- Dockerfile
Allows the container to properly track time instead of using UTC.
> Dockerfile: add tzdata

- src/util/tools.cc
std::accumulate is shorter and generates more efficient assembly.
> replace stringHash with single accumulate call

- src/config/config_setup.h
Found with readability-simplify-boolean-expr
> clang-tidy: simplify boolean expression

- src/metadata/matroska_handler.cc
- test/scripting/test_import_script.cc
> clang-tidy: use auto

- src/content/onlineservice/sopcast_content_handler.h
- src/content/scripting/script.h
- src/database/database.h
- src/util/upnp_clients.h
Found with readability-redundant-access-specifiers
> clang-tidy: remove redundant specifiers

- src/util/upnp_clients.cc
- src/util/upnp_clients.h
Avoids some issue in GCC's -fanalyzer about a null pointer.
> Assign clientInfo in a default constructor

- src/util/tools.cc
UBSan reports a shifting by int error. Looks like auto in this case
evaluates to int, which is not correct.
> fix std::accumulate

- src/util/tools.cc
> replace rand with std::random

- src/content/onlineservice/atrailers_content_handler.cc
- src/content/onlineservice/atrailers_content_handler.h
- src/content/onlineservice/atrailers_service.cc
- src/content/onlineservice/atrailers_service.h
- src/content/onlineservice/curl_online_service.cc
- src/content/onlineservice/curl_online_service.h
- src/content/onlineservice/sopcast_content_handler.cc
- src/content/onlineservice/sopcast_content_handler.h
- src/content/onlineservice/sopcast_service.cc
- src/content/onlineservice/sopcast_service.h
- src/device_description_handler.cc
- src/file_request_handler.cc
- src/serve_request_handler.cc
- src/url_request_handler.cc
- src/web/web_request_handler.cc
The call is in `UpnpFileInfo_set_ContentType` (at least 1.14.0 which is minimum)
Remove several includes that seem to be copy-pasted (search for pugixml resulted these files)
fixes #1583
> Close memory leak by duplicate call to ixmlCloneDOMString

- src/file_request_handler.cc
- src/serve_request_handler.cc
- src/server.cc
- src/url_request_handler.cc
- src/web/web_request_handler.cc
Get rid of the pointless ifdefs and just pass a C string to npupnp. It's
copy constructed anyway.
The overall goal is to reduce the NPUPNP diff to libupnp.
> nppnp changes

- src/server.cc
Otherwise, GCC's -fanalyzer complains about it.
> use a unique_ptr in lambda

- src/config/config_manager.cc
- src/config/config_setup.cc
- src/config/config_setup.h
- src/content/scripting/script.cc
- src/web/config_load.cc
- src/web/edit_load.cc
to_string is shorter and faster.
> replace several usages of format with to_string

- src/metadata/ffmpeg_handler.cc
- src/metadata/libexif_handler.cc
- src/server.cc
Array indeces are typically pointers, which are either 32 or 64 bit. Use
size_t to avoid bad code generation.
> switch several for loops to use size_t

- src/metadata/ffmpeg_handler.h
AVFormatContext is defined as a struct in the ffmpeg header.
Fixes -Wmismatched-tags
> declare AVFormatContext as struct

- src/url_request_handler.cc
These get created and immediately destroyed. No point.
> remove two pointless unique_ptrs

- src/content/content_manager.cc
std::map::erase has an overload that takes a key and erases it if it
exists. No need to do extra work.
> remove pointless find

- src/content/autoscan_inotify.cc
- src/content/update_manager.cc
Without this, fanalyzer complains that make_unique creates a null
pointer. libstdc++ defaults to a size of 0 if unspecified anyway.
> pass 0 to std::unordered_

- src/server.h
Found with cppcoreguidelines-special-member-functions
> clang-tidy: add missing functions

- src/config/config.h
- src/config/config_setup.h
- src/content/scripting/script.cc
- src/util/tools.h
- src/web/config_load.cc
Looks nice to me because it encapsulates begin and end of enum.
Also casts from enum type to int and back are hidden and save because of to_underlying
> Implement EnumIterator

- src/content/scripting/script_names.h
Needed for OBJECT_TYPE_CONTAINER, OBJECT_TYPE_ITEM,
OBJECT_TYPE_ITEM_EXTERNAL_URL
> add missing header

- src/database/search_handler.cc
- src/database/sql_database.cc
Found with readability-else-after-return
> clang-tidy: don't use else after return

- src/util/upnp_clients.cc
- src/util/upnp_clients.h
Initialization can just be moved down.
> remove pointless constructor

- src/metadata/metacontent_handler.cc
- src/metadata/metacontent_handler.h
The parameter is only used to be copied to an std::string.
> convert expandName to string_view

- src/web/web_request_handler.cc
- src/web/web_request_handler.h
> switch xmlDoc to unique_ptr

- src/metadata/libexif_handler.cc
- src/util/tools.cc
Looks like a refactoring oversight. trimString deals with strings, not C
pointers.
> remove pointless const_cast

- src/content/onlineservice/lastfm_scrobbler.cc
- src/content/onlineservice/lastfm_scrobbler.h
Simpler. Also switched to use unique_ptr instead of C pointer.
> lastfm: switch to C++ API

- src/database/database.h
- src/database/sql_database.cc
- src/database/sql_database.h
- test/mock/database_mock.h
Implicit this capture is deprecated.
Also changed to use const reference. Saves size.
> fixup lambda for C++20 compatibility

- .github/workflows/ci.yml
- conanfile.py
conan seems to be fixed now
fixes #1507
Use exact version number for fmt and spdlog because newer versions are not yet stable
> Re-add CI check with clang

- src/content/autoscan_inotify.cc
Looks cleaner.
Also switch to lambda. Shorter.
> use thread constructor

- src/content/update_manager.cc
- src/util/timer.h
- src/util/tools.cc
- src/util/tools.h
This function needed to be like this when using timespec. No longer.
> getTimespecAfterMillis: return ret instead of void

- src/metadata/metadata_handler.cc
- src/metadata/metadata_handler.h
- src/web/edit_load.cc
> return string instead of const char

- src/util/tools.cc
The compiler optimizes it the same anyway.
> replace temp variable with returns

- src/content/content_manager.cc
- src/database/database.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/web/items.cc
- test/mock/database_mock.h
Some background:
Because of -fanalyzer warnings, I changed these make_unique calls such that the function creates the vector or whatever and then moves it into make_unique. But doing that is quite silly as it's more efficient return the object. NRVO is prevented when make_unique is used. Compiled binary sees a small size reduction locally.
Runtime test seems to be fine as well.
> move unique_ptr removals

- src/content/layout/builtin_layout.cc
- src/content/layout/builtin_layout.h
- src/content/layout/js_layout.cc
- src/content/layout/js_layout.h
- src/content/layout/layout.h
- src/content/onlineservice/curl_online_service.cc
- src/content/onlineservice/curl_online_service.h
- src/content/onlineservice/online_service.h
- src/database/database.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/metadata/exiv2_handler.cc
- src/metadata/exiv2_handler.h
- src/metadata/ffmpeg_handler.cc
- src/metadata/ffmpeg_handler.h
- src/metadata/libexif_handler.cc
- src/metadata/libexif_handler.h
- src/metadata/matroska_handler.cc
- src/metadata/matroska_handler.h
- src/metadata/metacontent_handler.cc
- src/metadata/metacontent_handler.h
- src/metadata/metadata_handler.h
- src/metadata/taglib_handler.cc
- src/metadata/taglib_handler.h
- test/mock/database_mock.h
I think clang-tidy can't diagnose these as they're virtual functions.
> const ref conversions

- src/content/onlineservice/atrailers_content_handler.cc
- src/content/onlineservice/sopcast_content_handler.cc
- src/database/sql_database.cc
It's only used as an easier version of strcmp. In that sense,
string_view is more efficient.
> use std::string_view in if statements

- src/database/sql_database.cc
- src/metadata/metacontent_handler.cc
Found with modernize-use-emplace
> clang-tidy: use emplace_back

- src/config/config_setup.cc
- src/database/sql_database.cc
For whatever reason, the latter is more efficient.
Maybe because std::copy internally is implemented as a push_back loop
and insert is done in some other way.
> replace several inserts with std::copy

- src/database/sql_database.cc
pugi XML select_nodes evaluates an xpath expression while children(name) simply uses a filtered iterator, which is faster.
Fixed minor pointer move and explicit emplace (since the if branch is only executed when dynId is not in dynamicContainers)
> prefer xml-node children over xpath

- src/config/config_definition.cc
{} for `const char*` becomes nullptr, which breaks string construction on result of  `mapConfigOption`
> Fix mapConfigOption return

- src/file_request_handler.cc
- src/file_request_handler.h
- src/server.cc
- src/server.h
- src/upnp_xml.cc
- src/upnp_xml.h
- src/web/containers.cc
- src/web/edit_load.cc
- src/web/items.cc
- src/web/pages.cc
- src/web/pages.h
- web/gerbera-config-expert.json
make xmlbuilder object shared_ptr and make it available where needed (instead of static access)
> Make UpnpXMLBuilder::orderedHandler nonstatic

- src/util/upnp_clients.cc
- src/util/upnp_clients.h
Return it instead. This function's usage is commented
out. If uncommented, it fails as you cannot copy a unique_ptr. Fixed
that as well.
> fix bad unique_ptr usage

- src/util/upnp_clients.cc
- src/util/upnp_clients.h
- src/web/clients.cc
It's only copied in a single place. No need for shared_ptr complexity.
> get rid of ClientCacheEntry pointer

- scripts/js/common.js
- src/config/config_definition.cc
- test/config/fixtures/mock-config-all.xml
- test/config/fixtures/mock-config-minimal.xml
- test/config/fixtures/mock-import-magic-js-online.xml
- test/config/fixtures/mock-import-magic-js.xml
- test/config/fixtures/mock-import-magic.xml
- test/config/fixtures/mock-import-mappings.xml
- test/config/fixtures/mock-import-none.xml
- test/scripting/CMakeLists.txt
- test/scripting/test_internal_m3u8_playlist.cc
The M3U8 format allows special characters within the file names and descriptions. It uses an UTF8 BOM to indicate the byte order. This commit strips the BOM in common.js to make sure the rest of the file is interpreted correctly. Without this change the BOM will be part of the first line of the playlist and lead to an error message or a missing playlist entry.
The core of this commit is stripping a BOM from the first line of the playlist if it exists and mapping the m3u8 extension to `audio/x-mpegurl`. I use foobar2000 to generate the playlists and some of my filenames contain characters that can not be encoded correctly within a m3u playlist.
I opted to create a new test for m3u8 playlists that is almost a copy of the m3u case. I opted for a dedicated test because the it's a different …
> Add M3U8 support

- src/config/config_definition.h
- src/config/config_setup.cc
- src/content/autoscan_inotify.cc
- src/content/content_manager.cc
- src/content/scripting/js_functions.cc
- src/content/scripting/script.cc
- src/database/search_handler.cc
- src/database/sql_database.cc
- src/metadata/metacontent_handler.cc
- src/util/tools.cc
The clang-tidy check it seems looks for cases where the types do not
match to suggest emplace_back. Use push_back where they do. Saves some
size.
> replace several emplace_back with push_back

- src/util/upnp_clients.cc
- src/util/upnp_clients.h
> add ClientCacheEntry constructor

- src/cds_resource.h
Found with readability-make-member-function-const
> clang-tidy: make member function const

- src/upnp_xml.cc
- src/upnp_xml.h
Allows forwarding arguments directly.
Also change to struct. It's more accurate anyway.
> add PathBase constructor

- src/util/tools.cc
makes copy elision work properly.
> match return type

- .github/workflows/ci-js.yml
- .github/workflows/ci.yml
makes it easier to rerun js if stuck
> Split CI validation jobs

- CMakeLists.txt
- src/database/database.cc
- src/database/sql_database.cc
- src/database/sql_database.h
- src/database/sql_format.h
- src/database/sqlite3/sqlite_database.cc
I very much like the new fmt-based SQL statement generation code - but the format strings for quoting literals make the statements hard to read.
So I came up with [custom formatters](https://fmt.dev/latest/api.html#formatting-user-defined-types) for a SQLIdentifier struct that encapsulates the identifier name and quotation-traits and allows for a very readable quoted name formatting. One drawdown is that all identifiers need to be outside the SQL template.
There is only one usage example in this PR which I'd like to discuss before changing additional code (also ignore code formatting for now). Is this this a good idea?
On the other hand, why is the current code so pedantic on quoting all identifiers while both MySQL and SQLite should be able to handle all used identifiers without quotes.
> libfmt formatters for quoted SQL identifiers

- src/database/sql_database.cc
small size reduction. fmt seems to like vector.
This also avoids using std::initializer_list, which should not ve used.
> add missing std::vector

- src/database/sql_database.cc
There are several places where there is an unnecessary integer `quote()` call or a simple `fmt::format("{}", value)` which can be simplified to `fmt::to_string(value)`, or removed entirely if value is a `std::string` already.
Sometimes, I added a {:d} format type specifier so the runtime should throw immediately in case someone messes with the #defines.
> Simplify or remove unnecessary fmt::format calls

- CMakeLists.txt
- cmake/FindTaglib.cmake
Avoids using horrible taglib-config, which doesn't work right on Debian
10 without dpkg-architecture.
Taken from upstream:
https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/find-modules/FindTaglib.cmake
> use updated FindTagLib.cmake

- conanfile.py
We rely on the abiity to create ALIAS for non global imported targets
Fixes: #1420
> Conan: Require CMake >=3.18

- CMakeLists.txt
Gerbera requires GCC8 nowadays.
> remove optional check

- CMakeLists.txt
- cmake/FindEBML.cmake
- cmake/FindMatroska.cmake
Reverts gerbera/gerbera#1861
Breaks build with older distos (e.g. Ubuntu 16.04 & 18.04) as no CMake config is provided in their versions of the package.
> Revert "use targets for libmatroska and libebml"

- src/content/content_manager.cc
- src/content/content_manager.h
> move getLocation call down

- src/util/tools.cc
Basic godbolt test shows that assigning to nullptr calls
std::__throw_logic_error
> don't assign nullptr to std::string

- src/web/web_request_handler.h
It's not being done in the constructor. Found with coverity.
> default init mode

- src/database/mysql/mysql_database.cc
- src/database/mysql/mysql_database.h
- src/database/sql_database.h
- src/database/sql_format.h
- src/database/sqlite3/sqlite_database.cc
- src/database/sqlite3/sqlite_database.h
> don't pass string_view by reference

- src/database/database.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/metadata/libexif_handler.cc
- src/upnp_cds.cc
- src/util/jpeg_resolution.cc
- src/util/tools.h
- src/web/containers.cc
- src/web/items.cc
- test/mock/database_mock.h
The parameters to browse/search look odd when a unique_ptr needs to be passed to them. Since both parameter objects are rather small in memory footprint and there is no obvious advantage for dynamic allocation, simply allocate the parameters objects on the caller stack. This increases performance and makes the code more readable.
> Remove unique_ptr objects where stack memory is sufficient

- src/database/mysql/mysql-upgrade.xml
- src/database/mysql/mysql.sql
- src/database/mysql/mysql_database.cc
- src/database/sql_database.cc
- src/database/sql_database.h
- src/database/sqlite3/sqlite3-upgrade.xml
- src/database/sqlite3/sqlite3.sql
- src/database/sqlite3/sqlite_database.cc
I found some sub-optimal database schema settings I want to fix in this PR.
- The index `grb_config_value_item` is redundant as it references only the primary key of `grb_config_value`. It can be removed without side-effects
```SQL
CREATE TABLE "grb_config_value" (
"item" varchar(255) primary key,
"key" varchar(255) NOT NULL,
"item_value" varchar(255) NOT NULL,
"status" varchar(20) NOT NULL)
CREATE INDEX grb_config_value_item ON grb_config_value(item)
```
> Refactor database schema to remove unused indices

- src/server.cc
- src/util/string_converter.cc
length is usually implemented as size_t anyway.
> remove pointless size_t casts

- src/transcoding/transcode_ext_handler.cc
> remove unique_ptr casts to base class

- src/upnp_xml.cc
Just a minor cleanup opportunity I noticed when digging into the search title issue.
- Use a lambda to perform string truncation when over `upnp-string-limit`. This unifies the behavior as one was checking for string::npos,and  the other was only looking for a negative value. According to the documentation "A negative value will disable this feature..." so I took this implementation as correct.
- Apply string truncation to all metadata values, instead of just title and description.
- Removed unnecessary brackets around album art
> Use lambda in UpnpXMLBuilder::renderObject to trim strings

- doc/config-import.rst
- src/metadata/metacontent_handler.cc
Added the `%composer%` pattern for resources. Should be useful for others looking to add composer artwork to their browsing experience.
> Add Composer Tag to Metacontent Handler

- src/database/sql_database.cc
This evaluates to true under C++23.
> use C++ macro to check for to_underlying

- src/util/tools.cc
This evaluates to true under C++20.
> use C++ macro to check for starts_with

- src/content/onlineservice/atrailers_content_handler.cc
- src/content/onlineservice/sopcast_content_handler.cc
- src/device_description_handler.cc
- src/file_request_handler.cc
- src/metadata/libexif_handler.cc
- src/metadata/matroska_handler.cc
- src/serve_request_handler.cc
- src/url_request_handler.cc
- src/web/web_request_handler.cc
If the return type matches the function, copy elision applies. In this
case, since the types don't match, the variables get copied. But because
unique_ptr has copy operations deleted, These types get moved.
This reintroduces the clang warning that this breaks under C++11 but
fixes GCC's -Wredundant-move one. The latter is probably more
applicable.
> remove sort of redundant std::move

- src/database/sql_database.cc
- src/database/sql_database.h
The constructor passes std::map by value. Also make the constructor
rvalue to force moves.
> add std::move for some maps

- src/util/timer.cc
- src/util/timer.h
Removes compiler warnings on ARM regarding changed ABI.
> remove last std::list

- src/database/sql_database.cc
clang-analyzer reports that memory is leaked here. I have no idea why.
Fixes: https://github.com/gerbera/gerbera/issues/1894
> fix some weird memory leak

- src/database/search_handler.cc
- src/database/sql_database.cc
- test/core/test_searchhandler.cc
When performing searches only count rows with distinct IDs for TotalMatches. Close #1852. This fixes the behavior of "Shuffle All" on Hi-Fi Cast and "Random tracks" on BubbleUpnp.
Additionally, eliminate the repeated ` AND "c"."upnp_class" IS NOT NULL`  conditions in the emitted SQL query. I am fairly certain these are redundant as any rows with NULL `upnp_class` will be excluded by the original `LOWER("c"."upnp_class") LIKE ...` condition.
For example. A search from foobar2000 had this WHERE condition
```sql
WHERE (LOWER("c"."upnp_class") LIKE LOWER('object.item.audioItem%')) AND
(
(LOWER("c"."dc_title") LIKE LOWER('%bag%') AND "c"."upnp_class" IS NOT NULL) OR 
("m"."property_name"='upnp:genre' AND LOWER("m"."property_value") LIKE LOWER('%bag%') AND "c"."upnp_class" IS NOT NULL) OR …
```
> Only count items with distinct IDs in TotalMatches search result.

- src/metadata/exiv2_handler.cc
The variable name was changed but this entry was not.
> fix wrong value being assigned

- src/content/content_manager.cc
- src/content/content_manager.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/iohandler/process_io_handler.cc
std::remove expects a reference, not a moved value.
Same with quote().
> clang-tidy: performance fixes

- src/database/mysql/mysql_database.cc
Found with readability-redundant-string-cstr
> clang-tidy: remove redundant c_str

- src/metadata/taglib_handler.cc
> taglib: demote warning to debug

- src/cds_objects.h
- src/content/scripting/script.cc
- src/database/sql_database.cc
- src/metadata/ffmpeg_handler.cc
- src/metadata/libexif_handler.cc
- src/metadata/matroska_handler.cc
- src/metadata/metacontent_handler.cc
- src/metadata/metadata_handler.cc
- src/metadata/taglib_handler.cc
- src/web/add_object.cc
This can't be converted to an rvalue ref to force moves, so make it a
normal ref.
> const ref conversion

- src/database/sql_database.cc
- src/database/sql_database.h
There is no benefit in using shared_ptr for AddUpdateTable objects. This PR simplifies the use of this helper which reduces the code size and removes access-indirections. Dynamically growing the vector of objects is ensured to only use std::move operations.
> Simplify AddUpdateTable vectors without shared_ptr

- src/main.cc
Simply replace std::cout with corresponding fmt::print calls to be consistent with other formatting code
> Replace stdio with fmt calls

- src/database/sql_database.cc
- src/database/sql_database.h
- test/database/CMakeLists.txt
- test/database/test_sql_generators.cc
Simple SQL queries such as INSERT and DELETE often follow the same pattern. Provide simple methods that automatically handle quoting of identifiers and values and remove code redundancy.
Code for UPDATE methods will be added soon.
> Unify simple SQL queries

- src/request_handler.cc
- src/request_handler.h
- src/serve_request_handler.cc
- src/server.cc
- src/util/tools.cc
- src/util/tools.h
- src/web/web_request_handler.cc
- test/core/CMakeLists.txt
- test/core/test_request_handler.cc
I'm going over probably old code that is central to request and URL handling. These methods can strongly benefit from `std::string_view` optimizations to avoid copying string all over the place when dissecting them. While I'm at it, I add unit tests wherever suitable.
> Modernize parts of the request handling with C++17 and add UTs

- src/content/onlineservice/lastfm_scrobbler.cc
It seems there was a function rename.
> fix lastfm compilation

- doc/config-server.rst
- doc/scripting.rst
- src/content/scripting/script_names.h
- src/database/sql_database.cc
- src/metadata/metadata_handler.h
Add M_CREATOR to metadata (with no mapping).
HEOS artist search requires `dc:creator` to be in the SearchCapabilities.
If it not present in SearchCapabilities the app reports "Errorcode -11"
> Add all metadata to search capabilities

- src/metadata/taglib_handler.cc
to8Bit returns an std::string whereas toCString calls to8Bit and
converts it to a const char*. No point in the conversion.
> convert all usages of toCString to to8Bit

- src/database/mysql/mysql-upgrade.xml
- src/database/mysql/mysql.sql
- src/database/mysql/mysql_database.cc
- src/database/sql_database.cc
- src/database/sql_database.h
- src/database/sqlite3/sqlite3-upgrade.xml
- src/database/sqlite3/sqlite3.sql
- src/database/sqlite3/sqlite_database.cc
In database table `grb_cds_resource`, there is a primary key `id` which is not used anywhere in the code. What is actually used is the tuple `(item_id, res_id)` which is perfectly suited as a primary key. `item_id` is a foreign key and `res_id` is always created such that there are only unique `(item_id, res_id)` pairs.
In addition, with the new primary key, we can drop the index on `(item_id, res_id)`.
This change should not change the behavior of the current code but reduce the database size (fewer columns, fewer indices) as well as increase the speed of creating a database (no additional index update).
> Use better primary key for grb_cds_resource 

- src/util/tools.cc
- src/util/tools.h
- src/web/web_request_handler.cc
- test/util/test_tools.cc
std::map::merge() is equivalent.
> remove custom merge function

- src/util/upnp_headers.cc
- src/util/upnp_headers.h
> remove unused parameter

- src/main.cc
Automatically disabled when spdlog detects its not writing to a console
> Enable colour log levels

- src/action_request.cc
Causes a lot of noise in the non-debug log.
> restore log level to debug

- src/metadata/exiv2_handler.h
These are not important for normal operation.
> silence exiv2 warnings

- src/main.cc
It's used in filesystem context.
> convert string to fs::path

- src/metadata/exiv2_handler.cc
- src/metadata/exiv2_handler.h
Replaces the log handler with one that uses log_debug.
Also moved constructor out of line as it should be.
> exiv2: silence messages without debug

- src/web/config_load.cc
- src/web/pages.h
Reselect  node by xpath instead of keeping the object
Avoid segfault reported in #2142
> Avoid storing reference to node

- src/content/autoscan_inotify.cc
- src/util/timer.cc
- src/web/session_manager.cc
It should actually be const. But no need for it.
> remove pointless reference

- src/main.cc
- src/server.cc
LibUPnP will give us another port instead of the one we requested if it
cannot bind. If port has been explictly set this is undesirable
behaviour.
Check the bound port and fail to start in this case, to make it obvious
to the user that there is something awry.
> Validate bound port

- README.md
- src/metadata/matroska_handler.cc
- src/metadata/matroska_handler.h
closes #2045 
It's been more complicated than expected because we don't know in which header segment the searched entry is stored
> Improve matroska parsing speed

- src/config/config_definition.cc
- src/web/web_autoscan.cc
const ref parameter. No move happens.
> remove pointless move

- src/content/autoscan_list.cc
SonarLint reports that this should be const. However adding const,
using auto&&, or removing and replacing with *it everywhere results in a
crash. I'm guessing there's some null reference issue going on. Pass by
copy to avoid any warnings.
No size difference.
> copy shared pointer instead of passing reference

- src/web/web_autoscan.cc
The former allows to avoid reassigning a value. The latter gets rid of
various conversions.
> use lambda and fs::path

- src/upnp_xml.cc
> append with fmt

- src/metadata/matroska_handler.h
> matroska_handler: default init activeFlag

- src/database/sql_database.cc
- src/database/sql_database.h
> return std::pair for stripLocationPrefix

- src/database/search_handler.cc
clang-tidy throws bugprone-implicit-widening-of-multiplication-result
> fix some implicit conversion warnings

- src/metadata/matroska_handler.cc
In the one place where this is used, close() is called anyway.
> remove custom destructor

- src/iohandler/file_io_handler.cc
- src/iohandler/file_io_handler.h
It calls close() which is an empty function. Removing it like this uses
a defaulted destructor.
> remove FileIOHandler destroctor

- src/content/autoscan_inotify.cc
- src/content/autoscan_list.cc
- src/content/content_manager.cc
- src/web/web_autoscan.cc
Avoids unnecessary conversions from fs::path, to std::string, to
std::string_view.
> use operator < instead of startswith

- src/content/layout/builtin_layout.cc
- src/iohandler/file_io_handler.cc
- src/iohandler/file_io_handler.h
Not a good idea with make_shared. Causes memory problems as make_shared
is created into a temporary and then destroyed immediately.
Also pass vector by move. More efficient.
> remove initializer_list usage

- src/config/client_config.h
- src/config/directory_tweak.h
- src/config/dynamic_content.h
- src/content/autoscan_inotify.h
- src/content/autoscan_list.h
- src/content/scripting/scripting_runtime.h
- src/database/sql_database.h
- src/database/sqlite3/sqlite_database.cc
- src/util/thread_runner.h
- src/util/upnp_clients.h
- src/web/session_manager.h
SonarLint reports the latter to be better:
std::scoped_lock basically provides the same feature as std::lock_guard,
but is more generic: It can lock several mutexes at the same time, with a
deadlock prevention mechanism (see {rule:cpp:S5524}). The equivalent code
to perform simultaneous locking with std::lock_guard is significantly more
complex. Therefore, it is simpler to use std::scoped_lock all the time,
even when locking only one mutex (there will be no performance impact).
> replace all lock_guard with scoped_lock

- src/server.cc
requestCookie is const void**. *requestCookie is const void*.
> fix wrong cast

- src/cds_objects.cc
- src/cds_objects.h
> CdsContainer: Comment out overriden function

- src/util/grb_fs.cc
- src/util/grb_fs.h
used std::move
Change return type to uintmax_t as that is the type returned by
file_size().
Switch to fseeko to avoid potential 32-bit problems.
> grb_fs: run through clang-tidy

- src/util/upnp_headers.cc
> remove old libupnp compatibility

- src/util/xml_to_json.cc
- src/util/xml_to_json.h
Avoids having to use a non const ref
> pair conversion

- src/content/content_manager.cc
shared_ptr handles this automatically.
> remove cast with make_shared

- src/main.cc
> simplify shared_ptr assignment

- src/util/tools.cc
- src/util/tools.h
- src/util/xml_to_json.cc
- src/util/xml_to_json.h
Avoids sonarlint warning about using string_view.
> set by move

- src/action_request.cc
- src/server.cc
Avoid early ixmlDocument_free.
Make sure object is not needed anymore.
> Delay release of ixmlDocument

- src/exceptions.h
Gerbera requires very recent compilers.
> remove old PRETTY_FUNCTION define

- src/config/client_config.cc
- src/config/client_config.h
- src/config/directory_tweak.cc
- src/config/directory_tweak.h
- src/config/dynamic_content.cc
- src/config/dynamic_content.h
- src/content/autoscan_inotify.h
- src/content/autoscan_list.cc
- src/content/autoscan_list.h
- src/content/scripting/scripting_runtime.h
- src/database/sql_database.h
- src/database/sqlite3/sqlite_database.h
- src/main.cc
- src/metadata/ffmpeg_handler.h
- src/util/thread_executor.h
- src/util/thread_runner.h
- src/util/upnp_clients.cc
- src/util/upnp_clients.h
- src/web/session_manager.cc
- src/web/session_manager.h
Allows using them in const member functions.
> make all mutexes mutable

- src/content/content_manager.cc
processPlaylistObject may call createSingleItem if a new directory contains files and playlists
fixes #2333
> Avoid locking mutex for too long

- src/transcoding/transcoding.cc
> place it variable in lambda

- src/file_request_handler.cc
- src/file_request_handler.h
- src/iohandler/io_handler_buffer_helper.cc
- src/request_handler.cc
- src/request_handler.h
- src/server.cc
- src/url_request_handler.cc
- src/web/web_request_handler.cc
Reverts the changes to cache stuff across get_info()/open() calls, this
is not feasible because libupnp may not call open() in the case of HEAD
requests, giving us no opportunity to clean up resources.
This sucks because we have to parse/load everything twice per request,
but it should stop transcoding processes being leaked.
Fixes: #2139
> Refactor file_request_handler

- src/cds_resource.h
- src/file_request_handler.cc
- src/file_request_handler.h
- src/metadata/ffmpeg_handler.cc
- src/metadata/metadata_handler.h
- src/upnp_xml.cc
- test/core/test_upnp_xml.cc
Nowadays thanks to Karls great work we no longer have the virtual
resource mess to deal with as things like album art now live in
the DB, so we can simplify this code a bit.
Fixes broken artwork.
In fact with this change the `rct` handler is also ignored, just
`res_id/1` is enough to get the image.
> Drop resourceHandler concept

- src/file_request_handler.cc
Possible fix for https://github.com/gerbera/gerbera/issues/2377
> Only set DNLA headers for resources we know about

- src/upnp_xml.cc
Using unique_ptr with a ternary operator seems to allocate both pointers
and only one ends up getting freed. Changed to lambda to avoid this.
Found with clang-tidy.
> fix memory leak

- src/metadata/ffmpeg_handler.cc
- src/upnp_xml.cc
I found 2 bugs in FfmpegHandler::addFfmpegMetadataFields().
1. Because both propertyMap.second and FFMpeg::metadata->key are `const char *`, we need to use `strcmp()` instead of `==`.
2.  If the metadata which is not included in `propertyMap` is found after this method processed M_TRACKNUMBER (or M_PARTNUMBER), `item->setTrackNumber(stoiString(value));` is called again incorrectly because `field` is still `M_TRACKNUMBER`.
I fixed the bugs and confirmed metadata of DSF file are set to DB correctly.
> fix bugs in addFfmpegMetadataFields()

- .editorconfig
- README.md
- gerbera-web/test/e2e/menu.spec.js
- web/index.html
- web/js/gerbera-menu.module.js
Most users expect the top left logo to go to the web site's main page
and not to the homepage of the application that is used.
Instead link the Gerbera github page in the introduction text
on the home screen.
Resolves: https://github.com/gerbera/gerbera/issues/2316
This PR also contains a README fix and editorconfig adjustments for .js files.
> Web logo link

- src/util/tools.cc
The n variable is completely unused.
> simplify loop

- src/content/content_manager.cc
obj gets changed with these usages.
> Fix bad static_pointer_cast transformation

- src/config/config_definition.cc
- src/metadata/ffmpeg_handler.cc
- test/config/fixtures/mock-config-all.xml
- test/config/fixtures/mock-import-magic-js-online.xml
- test/config/fixtures/mock-import-magic-js.xml
- test/config/fixtures/mock-import-magic.xml
- test/config/fixtures/mock-import-mappings.xml
- test/config/fixtures/mock-import-none.xml
When there are multiple bits per sample we would have reported an
incorrect sample rate. For PCM bits per raw/coded are both 0.
Bug: https://github.com/gerbera/gerbera/issues/2401
> Multiply out sample rate reported by FFMpeg

- src/action_request.h
- src/config/client_config.cc
- src/config/client_config.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/file_request_handler.cc
- src/server.cc
- src/server.h
- src/upnp_cds.cc
- src/upnp_cds.h
- src/upnp_cm.cc
- src/upnp_cm.h
- src/upnp_mrreg.cc
- src/upnp_mrreg.h
- src/util/upnp_clients.cc
- src/util/upnp_quirks.cc
- src/util/upnp_quirks.h
SonarLint reports:
If you use std::unique_ptr<T> const & for a function parameter type, it
means that the function will not be able to alter the ownership of the
pointed-to object by the unique_ptr:
It cannot acquire ownership of the pointed-to object (this would require
a parameter of type std::unique_ptr<T>)
It cannot transfer the object ownership to someone else (this would
require a std::unique_ptr<T> &).
That means the function can only observe the pointed-to object, and in
this case passing a T* (if the unique_ptr can be null) or a T& (if it
cannot) provides the same features, while also allowing the function to
work with objects that are not handled by a unique_ptr (E.G. objects on
the stack, in a vector, or in another kind of smart pointer), thus making
the function more …
> remove const from several unique_ptrs

- test/util/test_upnp_headers.cc
This is never NULL. It also throws an fanalyzer warning. Easier to
remove.
> remove unique_ptr from tests

- doc/install.rst
gerbera has been dropped from Entware since https://github.com/Entware/rtndev/commit/6d6803f1b5fca0f03623c14a4bd924cbe8000166
> doc/install.rst: drop Entware

- .github/workflows/publish-deb.yml
- scripts/debian/build-deb.sh
Bug: https://github.com/gerbera/gerbera/issues/2468
> CI: build-deb: Pass API key to docker env

- .github/workflows/publish-deb.yml
Bug: https://github.com/gerbera/gerbera/issues/2468
> CI: build-deb: Pass API key to docker env, again

- src/database/sql_database.cc
> clang-tidy: replace push with emplace_back

- src/cds_objects.h
It's generally preferred to do a single function passed by value instead
of l and rvalue reference parameters.
> remove reference parameter

- src/util/tools.cc
The former is a BSD function that is not available everywhere.
> replace bzero with {}

- src/util/tools.cc
- src/util/tools.h
clang-tidy suggests const std::string&. Probably better to pass a view.
> string to string_view conversion

- doc/config-import.rst
- gerbera-web/mock-api/edit_load/object_id-39479.json
- src/cds_resource.cc
- src/cds_resource.h
- src/upnp_xml.cc
- src/web/edit_load.cc
- web/assets/theme/gerbera.css
- web/index.html
- web/js/jquery.gerbera.editor.js
Attribute names are mapped to more user friendly texts, values are transformend.
Web ui shows raw and mapped values, dlna profile mapping uses mapped ones (and raw ones).
> Improve readability of attributes

- src/server.cc
: is used to specify port, not the URL.
> fix bad URL

- src/server.cc
Reverts gerbera/gerbera#2549
The documentation says it is appended to the IP to set the port
> Revert "fix bad URL"

- src/database/sql_database.cc
redundant as emplace_back is being used.
> get rid of make_pair

- src/config/config_options.h
clang-tidy suggests placing the size parameter in the initializer list.
> value to ref conversions

- src/content/autoscan_list.cc
- src/content/content_manager.cc
Fixes: https://github.com/gerbera/gerbera/issues/2567
> Handle config sourced autoscans in DB more gracefully

- src/database/sql_database.h
> clang-tidy: use braced init list

- src/config/config_setup.h
> clang-tidy: redundant init

- src/metadata/metadata_handler.h
- src/util/tools.h
Avoids clang-tidy warning about the return value of template being const
V.
> remove const from map

- src/util/string_converter.cc
This implies SOLARIS has been broken for a long time. No idea who uses Solaris.
> fix wrong variable name

- src/database/sql_database.h
- src/util/process_executor.cc
I changed ++apos to apos++ since the latter seems to be the correct thing to do. Please check.
> clang-tidy: use at() instead of []

- src/upnp_cds.cc
Fix regression described in #2590 by always updating the item's title.
> Fix search-item-result regression.

- src/database/sql_database.h
> clang-tidy: remove defaulted constructors

- src/util/jpeg_resolution.cc
Missing headers for throw_std_runtime_error
> fix compilation

- src/cds_objects.h
Found with bugprone-inaccurate-erase
> clang-tidy: fix wrong erase

- src/action_request.cc
- src/action_request.h
- src/common.h
- src/context.cc
- src/context.h
- src/file_request_handler.cc
- src/request_handler.cc
- src/request_handler.h
- src/server.cc
- src/server.h
- src/upnp_cds.cc
- src/upnp_cds.h
- src/upnp_cm.cc
- src/upnp_cm.h
- src/upnp_mrreg.cc
- src/upnp_mrreg.h
- src/upnp_xml.cc
- src/upnp_xml.h
- src/util/upnp_clients.cc
- src/util/upnp_clients.h
- src/util/upnp_quirks.cc
- src/util/upnp_quirks.h
- src/web/containers.cc
- src/web/edit_load.cc
- src/web/items.cc
- test/core/test_ffmpeg_cache_paths.cc
- test/core/test_upnp_xml.cc
- web/js/jquery.gerbera.editor.js
- web/js/jquery.gerbera.items.js
- web/js/jquery.gerbera.tree.js
Single way to get the virtualUrl.
VirtualURL no longer includes the SERVER_VIRTUAL_DIR (content)
component for consistency with configuration and code.
> Server: Clean up virtualURL handling

- src/database/database.h
- src/database/search_handler.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/upnp_cds.cc
Respect ContainerID when performing searches against the database. Close #2364.
This is implemented using a recursive query that finds all children of a given parent_id. The children's ref_id's are then followed to find the actual physical items.
I am a little unclear on the desired styles of this project. There appears to be mix of `snake_case` and `camelCase` for variable names. Some accessors also take the form`getSomeVariable()` while others are `someVariable()`. I will gladly update the changes to match the desired style.
> Respect ContainerID when performing search

- src/cds_resource.cc
Actually this should probably use std::tuple...
> clang-tidy: fix case style of class/structs

- src/database/mysql/mysql-upgrade.xml
- src/database/mysql/mysql_database.cc
- src/database/sqlite3/sqlite3-upgrade.xml
- src/database/sqlite3/sqlite_database.cc
closes #2622 
No new version, because if db was newly created it does not have the `scan_level` column to drop. Users who already updated need to execute the script manually.
> Drop scan_level on update to DB 19

- src/content/scripting/import_script.h
- src/content/scripting/playlist_parser_script.cc
- src/content/scripting/playlist_parser_script.h
- src/content/scripting/script.cc
- src/content/scripting/script.h
> clang-tidy: const string ref conversion

- src/util/mt_inotify.cc
- src/util/upnp_clients.cc
> clang-tidy: use data() instead of pointer magic

- src/upnp_xml.h
These are moved in from the constructor. const prevents moves.
> remove const from member variables

- src/iohandler/io_handler_buffer_helper.cc
- src/iohandler/mem_io_handler.cc
- src/util/grb_net.cc
- src/util/mt_inotify.cc
The latter compiles to the former. It's more restrictive as the types
have to match.
> replace some memcpy by std::copy_n

- CMakeLists.txt
- doc/config-import.rst
- src/content/content_manager.cc
- src/database/mysql/mysql_database.cc
- src/database/mysql/mysql_database.h
- src/database/sql_database.cc
- src/database/sql_database.h
- src/database/sqlite3/sl_task.cc
- src/database/sqlite3/sl_task.h
- src/database/sqlite3/sqlite_database.cc
- src/database/sqlite3/sqlite_database.h
- test/database/test_sql_generators.cc
This handles the problem of deleted entries being referenced
Obviously the task queue already contains the commands so we only can avoid exceptions.
Fixes #2674 
fixes #2680 
Fixes #2605 
Fixes #2699
> Handle deleted objects in sqlite queue

- .github/workflows/codeql-analysis.yml
Avoid deprecation
c.f. https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> CodeQL: Update version

- .github/workflows/docker.yml
Enable [edge tagging](https://github.com/docker/metadata-action#typeedge) for docker builds. Close #2720
> Add edge tag to docker workflow

- CMakeLists.txt
- src/util/string_converter.cc
Make sure ICONV_CONST is defined if the system has const in its iconv prototype definition.
Use the right variable names when calling iconv with const.
> Fix build on systems that have const in second argument to iconv

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/publish-deb.yml
Avoids deprecation of actions https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Workflows: Update actions

- Dockerfile
package `ffmpeg4` does not contain `ffmpeg`
closes #2744
> Docker: Bring back ffmpeg in transcoding image

- .github/workflows/minimal.yml
- Dockerfile
- Dockerfile.debug
- README.md
- scripts/versions.sh
also update in CI workflow.
also update wavpack to 5.6.0
> Docker: Update to alpine 3.17

- doc/config-import.rst
- src/util/grb_net.cc
- test/core/test_searchhandler.cc
> openSuSE: Fix test and inits

- doc/supported-devices.rst
- src/config/client_config.cc
- src/upnp_cds.cc
- src/upnp_xml.cc
- src/upnp_xml.h
- src/util/upnp_clients.cc
- src/util/upnp_clients.h
- src/util/upnp_quirks.cc
- src/util/upnp_quirks.h
- test/core/test_upnp_xml.cc
closes  #2616
But causes clients like FooBar to fail on browse because of double espace `&amp;apos;`
> XML: Allow escaping ticks for some clients

- doc/gerbera.1
In gerbera.1 config/gerbera is an "undefined macro".
Warning message from the current 1.12.1 release in debian:
```shell
troff:<standard input>:90: warning: macro 'config/gerbera' not defined [usr/share/man/man1/gerbera.1.gz:1]
``` 
This change fixes the warning.
> Fix troff warning

- src/content/content_manager.cc
- src/content/import_service.cc
- src/database/database.h
- src/database/sql_database.cc
- src/database/sql_database.h
- test/mock/database_mock.h
not clear how and when it happens, but we can fix it afterwards.
Should fix the "not existing files are still shown" mentioned in https://github.com/gerbera/gerbera/discussions/2864#discussioncomment-7023564
> Clean up unreferenced items

- ChangeLog.md
- ReleaseNotes.md
- scripts/versions.sh
- src/content/autoscan_inotify.cc
- src/content/autoscan_inotify.h
- src/content/content_manager.cc
- src/content/content_manager.h
- src/content/import_service.cc
- src/content/import_service.h
- src/util/mt_inotify.cc
- src/util/mt_inotify.h
Renaming a directory left the new one unmonitored until restart because it kept its inode and therefor no new monitoring was started but the old one was deleted
> Autoscan: Handle renamed directory

- src/content/autoscan_inotify.cc
- src/content/autoscan_inotify.h
Instead of splitting the path string into parts just use parent_path() to navigate
> Autoscan: Use path for handling of non-existing

- scripts/js/audio.js
- scripts/js/common.js
- src/config/config_definition.cc
- src/content/layout/builtin_layout.cc
- test/config/fixtures/mock-config-all.xml
- test/config/fixtures/mock-config-minimal.xml
- test/config/fixtures/mock-example-all.xml
- test/config/fixtures/mock-example-exiv2-all.xml
- test/config/fixtures/mock-example-minimal.xml
- test/config/fixtures/mock-import-magic-js-online.xml
- test/config/fixtures/mock-import-magic-js.xml
- test/config/fixtures/mock-import-magic.xml
- test/config/fixtures/mock-import-none.xml
- test/scripting/test_import_script.cc
Add an artist chronology container (similar to album container, but sorted by date instead of name)
> Add artist chronology container

- src/content/import_service.cc
Fixes crash if file name has only one character (without extension)
> Import: Handle really short file names correctly

- src/metadata/ffmpeg_handler.cc
- src/metadata/ffmpeg_handler.h
On ffmpeg_handler.cc there is a issue in meta data processing for M_DATE and M_CREATION_DATE. 
https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.cc#L135-L138
https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.cc#L143-L145
`if (emptyProperties[M_DATE])` and `if (emptyProperties[M_CREATION_DATE])` are always **false**.
Because `emptyProperties` are created by `propertyMap`  
https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.cc#L102-L105
that is https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.h#L68-L78
, where both M_DATE and M_CREATION_DATE are not included. …
> Fix processing for M_DATE and M_CREATION_DATE on FFmpeg handler.

- doc/scripting.rst
- scripts/js/common.js
- scripts/js/import.js
- scripts/js/metadata.js
- scripts/js/playlists.js
- src/content/scripting/js_functions.cc
- src/content/scripting/js_functions.h
- src/content/scripting/script.cc
- src/util/logger.h
- test/scripting/mock/common_script_mock.h
- test/scripting/mock/script_test_fixture.cc
- test/scripting/mock/script_test_fixture.h
- test/scripting/test_external_asx_playlist.cc
- test/scripting/test_external_m3u_playlist.cc
- test/scripting/test_external_pls_playlist.cc
- test/scripting/test_import_script.cc
- test/scripting/test_import_struct_script.cc
- test/scripting/test_internal_m3u8_playlist.cc
- test/scripting/test_internal_m3u_playlist.cc
- test/scripting/test_internal_pls_playlist.cc
- test/scripting/test_nfo_metafile.cc
> Scripting: print2 function with log level support

- doc/install.rst
- doc/troubleshooting.rst
Add a new Firewall section to the Troubleshooting page.
Expand the Port section of the Troubleshooting page to complement the new Firewall section.
Add info about Fedora Server edition on the Installing Gerbera page. The existing Fedora section was ok for the Workstation edition. The added info should save a user a bunch of troubleshooting if they install on the Server edition.
> Expand firewall advice in docs (#2993)

- Dockerfile
- Dockerfile.debug
- README.Docker.md
- scripts/docker/docker-entrypoint.sh
Hi!
This is my first contribution to Gerbera. It aims at making the Gerbera Docker image more customizable for users who do not want to write their own Dockerfiles:
* simplify adding custom JavaScript code
* add directory `/mnt/customization/js` for custom JavaScript files
* add this directory to `config.xml` on creation
* clarify that content directory will be "mounted" to a directory on the host
* add directory `/content`  to `/mnt/content` and use that by default
* link `/content` to `/mnt/content` for backward compatibility
* ease customization of `config.xml` when it is created
* add directory `/mnt/customization/shell`
* call script `/mnt/customization/shell/gerbera_config.sh` (if existing)
whenever `config.xml` is created
* update documentation
I think that these modifications do …
> Docker image usability

- scripts/js/common.js
Per issue #2998  -- this change updates the Dates section of the Video box setup to check if the parameter boxSetup['Video/allDates'] is checked instead of boxSetup['Video/allYears']
> BUGFIX: common.js boxSetup check Video/AllDates for Dates

- CMakeLists.txt
- src/content/content_manager.cc
- src/content/import_service.cc
- src/content/import_service.h
- src/file_request_handler.cc
- src/file_request_handler.h
- src/metadata/exiv2_handler.cc
- src/metadata/exiv2_handler.h
- src/metadata/metadata_handler.h
- src/metadata/metadata_service.cc
- src/metadata/metadata_service.h
Use fixed instances instead of recreating for each scanned item.
(Should significantly improve import speed.)
> MetadataHandler: Refactor static methods

- src/metadata/matroska_handler.cc
- src/metadata/matroska_handler.h
Some API have been changed internally but there are some backward compatible macros to make the porting from one version to the other seamless.
All the changes should compile with libmatroska 1.0.0 and above.
> matroska_handler: update API calls to work with libebml/libmatroska 2.0

- .github/workflows/minimal.yml
- src/content/import_service.cc
- src/content/scripting/metafile_parser_script.cc
- src/content/scripting/metafile_parser_script.h
- src/content/scripting/playlist_parser_script.cc
- src/content/scripting/playlist_parser_script.h
- src/content/scripting/script.cc
Multiple instances need unique context
> Metafile: handle instance

- src/file_request_handler.cc
- src/file_request_handler.h
- src/server.cc
- src/server.h
avoid creating MetadataService each time
avoid copying XmlBuilder twice
> Cleanup FileRequestHandler

- ChangeLog.md
- Dockerfile
- Dockerfile.debug
- ReleaseNotes.md
- scripts/install-googletest.sh
- scripts/install-matroska.sh
- scripts/versions.sh
> Docker: update alpine version

- src/metadata/taglib_handler.cc
update calls to File() constructor
allows to hide messages from #2968  but does not fix the root cause (there are several around that: `MP4: Invalid atom type`).
> TagLib: Use DebugListener to suppress messages

- .github/workflows/publish-deb.yml
- scripts/debian/build-deb.sh
Upload to s3 compatible storage with endpoint at pkg.gerbera.io
Will need to update docs once everything is confirmed to work OK.
Tested locally and its fine.
Script changes are to move the dep installs into the conditional, to avoid rebuilding everytime I was trying an upload.
> CI: Upload debs to pkg.gerbera.io

- scripts/js/common.js
Follow up to #3057
Essentially, we check the album artist tag first, if it doesn't exist, we just use the first artist in the list.
> Adding consistent album artist support

- src/server.cc
at least vlc and upnp tools ignore announced path
> Fix discovery

- doc/config-server.rst
- src/metadata/exiv2_handler.cc
- src/metadata/libexif_handler.cc
- src/metadata/libexif_handler.h
- src/util/logger.cc
- src/util/logger.h
Integrate LibExif messages in gerbera log instead of hiding them from the user.
> Libexif: add custom logger

- scripts/debian/build-deb.sh
Somehow the required versions for deb-s3 jump with each build
> Build: Use ruby2.7 for bionic

- src/content/import_service.cc
- src/content/inotify/autoscan_inotify.cc
- src/util/grb_fs.cc
These changes fix application crashes on the freebsd 14.1
1. I removed the use of std::prev with std::filesystem::path objects (see llvm/llvm-project#55521)
2. Fixed typo (at least it looks like typo) in import code that handles `.nomedia` files
After applying these patches I was able to successfully compile and run port of gerbera 2.1.0 on freebsd 14.1 on my NAS, and successfully imported my video folder with recursive flag.
> Fix crashes on freebsd 14.1

- config/config2.xsd
I got an error:
```
$ xmllint --noout --schema config/config2.xsd test/config/fixtures/mock-config-all.xml config/config2.xsd:1183: element choice: Schemas parser error :
Element '{http://www.w3.org/2001/XMLSchema}all': The content is not valid.
Expected is (annotation?, (annotation?, element*).
WXS schema config/config2.xsd failed to compile
```
Maybe github actions should automatically validate the xsd files so that such errors are found.
> Fix config2.xsd

- .github/workflows/publish-deb.yml
System packages are no longer available
> Drop Build Support for Ubuntu 23.10

- .github/workflows/publish-deb.yml
Installation sources are gone now
> Drop Build Support for Ubuntu 23.04

- ChangeLog.md
- cmake/GenCompileInfo.cmake
- cmake/generateDoc.cmake
- test/CMakeLists.txt
- test/config/CMakeLists.txt
- test/config/CTestManip.cmake
- test/core/CMakeLists.txt
- test/core/CTestManip.cmake
- test/database/CMakeLists.txt
- test/database/CTestManip.cmake
- test/scripting/CMakeLists.txt
- test/scripting/CTestManip.cmake
- test/util/CMakeLists.txt
- test/util/CTestManip.cmake
DEPENDS is not supported in custom command:
https://cmake.org/cmake/help/latest/policy/CMP0175.html#policy:CMP0175
Fixtures are copies with each test now: Makes fixing fixtures a lot faster.
Message is not printed with the test but in the beginning.
> Test: Fix CMake commands

- src/content/inotify/inotify_handler.cc
Playlist create and updates can fail due to a race of deleting the existing playlist and making a new one. Make the removeObject synchronous to fix the issue.
When a playlist file is updated, AutoscanInotify::threadProc takes the following actions:
InotifyHandler::doExistingFile
- invokes ContentManager:removeObject with the default aysnc = true
InotifyHandlder::doNewFile
- invokes ContentManager:addFile with the asSetting.async argument set to false
- the doImport processs is started
- eventually a SELECT is done for the mt_cds_object entry for the .m3u file
- the async process has not yet deleted this, so the entry is found
- soon after, the mt_cds_object entry for the .m3u file as well as the two V entries that reference the the .m3u file entry are deleted, causing the exception
The …
> Fix update of playlists

- src/database/sql_database.cc
The current SQL uses an invalid column:
> error (1054): "Unknown column 'obj_id' in 'where clause'";
> query: UPDATE mt_cds_object SET flags = (flags | 8) WHERE obj_id = 4
Since mt_cds_object only has a id column we use that.
Resolves: https://github.com/gerbera/gerbera/issues/3426
> Fix SQL for changing persistent object flag in database
