gerbera/gerbera

CMakeLists.txt, README.md, src/file_request_handler.cc, src/metadata/taglib_handler.cc, src/server.cc, src/subscription_request.cc, src/youtube_video_url.cc
- The 2nd arg should be `time_t *`, not `time_t`
=> Fix upnp library call compiler error

src/autoscan.cc, src/autoscan.h, src/autoscan_inotify.cc, src/autoscan_inotify.h, src/buffered_io_handler.cc, src/cached_url.cc, src/cached_url.h, src/curl_io_handler.cc, src/io_handler_buffer_helper.cc, src/io_handler_buffer_helper.h, src/layout/fallback_layout.cc, src/request_handler.cc, src/scripting/import_script.h, src/thread_executor.cc, src/thread_executor.h, src/timer.cc, src/tools.cc, src/tools.h
Splitting the work into a few separate merges so that work branch doesn't fall too far behind the master branch.
=> Replace custom sync with STL - Part 1

README.md
So that i can avoid looking at the code each time, I elaborated in the README
Include if you find useful
=> Addition to README.md for external artwork details

.travis.yml, scripts/install-pupnp18.sh, scripts/install-taglib111.sh
Build against:
GCC 4,5,6
clang 4
=> Add Travis CI support

scripts/make_server_icons.sh
Plopped this in scripts, useful for users looking to customize, more importantly perhaps helpful
to you as you deal with #54 
Cheers
=> Script for generating server icons, perhaps useful in the Great Rebranding

src/storage/sql_storage.cc
Resolves: https://github.com/v00d00/gerbera/issues/68
=> Make SQL album art fetching work on MySQL

scripts/launchd/README.md, scripts/launchd/gerbera.io.plist
As a follow up to #87 - Add the launchd script to the `scripts` directory.
=> Add macOS launchd script

README.md
I updated the ubuntu PPA to reflect the project rename.
=> Update link to Ubuntu PPA

web/top.html
=> Fix distorted status icon in Web UI

scripts/solaris/gerbera-smf.xml, scripts/solaris/svc-gerbera
Greetings
Somewhere along the way, I lost my commits/pulls/whatnot for the actual goodies to have gerbera run as a proper managed service under Solaris.  scripts seemed like the right place for them.  There's an
assumption here about where config files etc live, but it should be easy to understand for a Solarian
Cheers
=> Solaris SMF ingredients

README.md, scripts/install-duktape.sh, scripts/install-pupnp18.sh
* Fix #144 - Improve macOS installation
=> Fix #144 - Improve macOS installation

README.md
changed documentation because when installing on FreeBSD -DWITH_SYSTEMD=0 has to be set
=> updated documentation for FreeBSD installation

src/storage/sql_storage.cc
I've tried a number of strategies, which often end up being undone by the SQL scheduler.
Without changing the database schema [additional complicated functional indices] this is the best I've got at the moment.
...I made a mistake at some point and had my database in a non-default state; this works as long as you've not messed around with PRAGMA
Perhaps it will help with #138 
Cheers
=> Optimize album art

README.md
I have added the library version used in the scripts and took the default options from CMakeLists.txt.
=> Fix #210: dependencies and compile-time options details

gerbera-web/mock-api/auth/tests/login.test.requests.json, gerbera-web/mock-api/auth/ui-disabled.json, gerbera-web/package.json, gerbera-web/test/client/fixtures/ui-disabled.json, gerbera-web/test/client/gerbera.app.spec.js, gerbera-web/test/client/gerbera.menu.spec.js, gerbera-web/test/client/gerbera.updates.spec.js, gerbera-web/test/e2e/login.spec.js, gerbera-web/test/e2e/page/home.page.js, gerbera-web/test/e2e/page/login.page.js, web/js/gerbera.app.js, web/js/gerbera.menu.js, web/js/gerbera.updates.js
* Disable UI interations when server UI is disabled
* Hide menu items and login form when UI is disabled
* Reject all non-success responses
=> Improve Disabled UI - Fixes #216

web/left.html, web/right.html, web/top.html, web/topleft.html, web/topright.html
The new UI will be in BETA phase with next release, so it makes sense to fix this.
=> Fix #198 - Rename mediatomb to gerbera

.gitignore, doc/README.md, doc/do_sphinx.sh
* Support python virtualenv for documentation build
* Check for virtualenv to avoid failures
=> Repeatable Sphinx build for documentation

gerbera-web/test/client/gerbera.updates.spec.js, gerbera-web/test/e2e/add.object.spec.js, gerbera-web/test/e2e/autoscan.spec.js, gerbera-web/test/e2e/delete.item.spec.js, gerbera-web/test/e2e/items.spec.js, gerbera-web/test/e2e/login.spec.js, gerbera-web/test/e2e/logout.spec.js, gerbera-web/test/e2e/menu.spec.js, gerbera-web/test/e2e/overlay.spec.js, gerbera-web/test/e2e/page/home.page.js, gerbera-web/test/e2e/page/login.page.js, gerbera-web/test/e2e/toast.spec.js, gerbera-web/test/e2e/trail.spec.js, gerbera-web/test/soak-test.js, web/assets/theme/gerbera.css
The UI E2E tests occasionally fail due to time tolerances with the tests.  When the tests run on remote environment (_TravisCI_) the timing can vary based on resource availability.  The testing variance produced on average a **3%** failure rate.
This PR improves the time variance in the UI tests.
The fixes were tested by running `Xvfb` with Google Chrome through more than 450 iterations (_each iteration included unit test and browser test_).  The last 150 iterations were 100% successful.
=> Improve UI E2E Tests

cmake/GenCompileInfo.cmake, src/main.cc
Update compile info and version info following 71f13e7905800eb436f2cafe83b140a5a39ed1e8
=> Update compile-info and version output options

web/assets/theme/gerbera.css, web/index.html, web/js/gerbera.menu.js
- Orange pills row
- New background shade
- External links not marked active.
- Active links not bold as it made things move
- House icon for home
=> Web UI: Misc improvements

gerbera-web/test/client/jquery.gerbera.trail.spec.js, web/assets/theme/gerbera.css, web/js/jquery.gerbera.trail.js
Split out icon and link classes and fix up unit tests
Obligatory screenshot:
=> Web UI: Add text to label buttons

gerbera-web/test/client/fixtures/index.html, gerbera-web/test/client/gerbera.menu.spec.js, gerbera-web/test/e2e/menu.spec.js, gerbera-web/test/e2e/page/home.page.js, web/js/gerbera.menu.js
Fixes #283 
1. Update code to use `.closest` jQuery selector to find proper menu item
2. Add tests(e2e, unit) to verify click of icon loads menu
3. Update `index.html` fixture to reflect latest `index.html` file.
=> Menu item icon click supports loading menu item

scripts/js/common.js, scripts/js/import.js, scripts/js/import_structured.js
A piece of code I got years ago and modified slightly. I use it to create structured library listings which are comfortable to browse on devices with limited scrolling capabilities.
=> Add abcbox to common.js lib

src/cds_resource_manager.cc, src/common.h, src/file_request_handler.cc, src/tools.cc, src/tools.h
Added contentFeatures.dlna.org field and fixed lengths of D_TR_FLAGS*
Discussion of this patch was conducted here:
https://github.com/gerbera/gerbera/issues/111
=> Improve compatibility with Samsung DTVs via DLNA

config/mappings.xml, src/config/config_generator.cc, src/config_manager.cc, test/test_config/fixtures/mock-config-all.xml, test/test_config/fixtures/mock-config-minimal.xml, test/test_config/fixtures/mock-import-magic-js-online.xml, test/test_config/fixtures/mock-import-magic-js.xml, test/test_config/fixtures/mock-import-magic.xml, test/test_config/fixtures/mock-import-mappings.xml, test/test_config/fixtures/mock-import-none.xml
I think this should work? `gerbera --create-config` seems to show the right value. Fix for #296
=> Add audio/flac to relevant places

gerbera-web/.eslintrc, gerbera-web/test/client/gerbera.app.spec.js, gerbera-web/test/client/gerbera.auth.spec.js, gerbera-web/test/client/gerbera.autoscan.spec.js, gerbera-web/test/client/gerbera.items.spec.js, gerbera-web/test/client/gerbera.menu.spec.js, gerbera-web/test/client/gerbera.trail.spec.js, gerbera-web/test/client/gerbera.tree.spec.js, gerbera-web/test/client/gerbera.updates.spec.js, gerbera-web/test/client/jquery.gerbera.autoscan.spec.js, gerbera-web/test/client/jquery.gerbera.editor.spec.js, gerbera-web/test/client/jquery.gerbera.items.spec.js, gerbera-web/test/client/jquery.gerbera.toast.spec.js, gerbera-web/test/client/jquery.gerbera.trail.spec.js, gerbera-web/test/client/jquery.gerbera.tree.spec.js
* `let` and `const` instead of `var`
* `async + await` instead of `.then(...)`
* `() =>` instead of `function ()`
* Terminate all lines with `;`
=> Update Unit Tests to ES6/7

scripts/js/import.js, src/common.h, src/layout/fallback_layout.cc, src/metadata/taglib_handler.cc, src/metadata_handler.cc, src/metadata_handler.h, src/scripting/script.cc, src/upnp_xml.cc, src/upnp_xml.h, test/test_script/mock/script_test_fixture.cc, test/test_script/test_import_script.cc
Hi all,
First off, awesome project! :) I have a large classical music collection and want to use gerbera. This PR add support for 3 commonly used tags Composer, Conductor, Orchestra. Eventually, I'd add a few more classical music related features if others are interested.
=> Add Classical Music Tag Support.

doc/config-server.rst
=> Add udn specific tag

doc/config-overview.rst
=> gerbera doesn't generate the folder inside config

src/upnp_xml.cc, test/test_upnp/test_upnp_xml.cc
Fixes #426 
* Add conditionals to check for `CdsItemExternalURL`
* Add tests to validate each use case
> This does not address album artwork, as any external reference may not be able to be defaulted as such.  Any ideas on artwork support?
=> Render External URL resource without virtual directory

src/metadata/taglib_handler.cc
AuxData configured in config with the form `<add-data tag="TXXX:FOO"/>` will
now be extracted as expected.
Fixes #421
=> Add support for TXXX AuxData extraction from MP3

gerbera-web/package-lock.json, gerbera-web/package.json
=> Update lodash (#9)

src/storage/sqlite3/sqlite3_storage.cc
=> SQLite: Turn on foreign key support at runtime

cmake/FindINotify.cmake, src/mt_inotify.cc
quick fixes to enable inotify in illumos/OmniOS builds
=> Support inotify kernel driver on illumos/OmniOS

CMakeLists.txt, src/server.cc
This will obviously need revisting when we start using the nice new
request cookeis functionality available in 1.10
Fixes #520
=> Fix the build with LibUPnP 1.10

gerbera-web/package-lock.json, web/assets/theme/gerbera.css, web/index.html
- Make 2nd bar Gray not orange
- Add some padding to left tree, remove scrollbar (auto)
- Tidy home page
=> Minor UI improvements

Dockerfile, scripts/install-duktape.sh, scripts/install-pupnp18.sh
Also, pkg-config to fix the libupnp build
=> Dockerfile: Add MKV support

src/metadata/matroska_handler.cc
i have checked other projects, which use libeml. Nobody is using StdIOCallback directly, they all have their own implementations, so lets do the same and use fseeko + ftello...
=> fix mkv on 32bit

src/metadata/exiv2_handler.cc
We definitely should improve CI.
github itself supports since short also CI via workflows/actions. I have another project where i use it and i am quite happy (https://github.com/pamapa/callblocker/tree/master/.github/workflows). No need for additional account, docker based, perfect integrated into github...
in the meantime, i have installed exiv2 locally too
=> part of #562: include was not adapted when moving config

src/storage/mysql/mysql_storage.cc, src/upnp_xml.cc
=> fix other part of #562

src/config/config_manager.cc, src/file_request_handler.cc, src/mxml/element.cc, src/web/auth.cc, src/web/session_manager.cc
- constructor vs reserve
- nullptr vs std::string
- config vs cfg in json result
found will testing the next replacements
=> fix web ui

src/storage/mysql/mysql_storage.h
=> fix part of #562: mysql_storage.h

.travis.yml
- FFMpeg
- FFMpegThumnailer
- libexif
- MySQL
No lastfm as not available in buster
No Exiv2 as linking betweeen stdc++ and libc++ gives all kinds of issues
=> CI: Enable optional deps

doc/scripting.rst, scripts/js/playlists.js
Update playlist.js script to avoid doing the regex twice
Thanks to @Corin-EU for looking into it.
Fixes #538
=> Docs: Update playlist example

scripts/install-spdlog.sh
Script to download, build and install spdlog from sources
=> spdlog package on openSuSE is outdated

src/autoscan_inotify.cc, src/config/config_manager.cc, src/scripting/playlist_parser_script.cc, src/scripting/script.cc, src/storage/sql_storage.cc, src/upnp_xml.cc, src/util/string_tokenizer.cc, src/util/tools.cc
all returns with std::string should be ok now.
=> #628 fix std::string with return nullptr

CMakeLists.txt, scripts/install-pupnp1_12.sh, src/util/headers.cc
=> Build with libupnp-1.12.0

src/config/config_manager.cc, src/content_manager.cc, src/util/process.cc, src/util/tools.cc
Found with readability-simplify-boolean-expr
=> [clang-tidy] simplify boolean expressions

src/metadata/matroska_handler.cc, src/util/tools.cc
=> [clang-tidy] use auto

.github/workflows/clang-format.yml, src/onlineservice/atrailers_service.cc
Fixes #649, thanks to @kyl416 for reporting
=> Update Apple trailer XML urls

src/main.cc, src/storage/sql_storage.h, src/url.h, src/util/process.h, src/util/string_converter.h, src/util/tools.h
Found with clang's -Wzero-as-null-pointer-constant
=> replace NULL with nullptr

src/cds_objects.h, src/content_manager.h, src/contrib/cxxopts.hpp, src/file_request_handler.h, src/iohandler/buffered_io_handler.h, src/iohandler/curl_io_handler.h, src/iohandler/io_handler_buffer_helper.h, src/iohandler/io_handler_chainer.h, src/iohandler/mem_io_handler.h, src/layout/js_layout.h, src/metadata/fanart_handler.h, src/metadata/libexif_handler.h, src/metadata/matroska_handler.h, src/metadata/taglib_handler.h, src/onlineservice/atrailers_service.h, src/onlineservice/sopcast_service.h, src/scripting/import_script.h, src/scripting/playlist_parser_script.h, src/search_handler.h, src/serve_request_handler.h, src/storage/sql_storage.h, src/storage/sqlite3/sqlite3_storage.h, src/transcoding/transcode_dispatcher.h, src/url_request_handler.h, src/util/process_executor.h, src/util/task_processor.h, src/util/thread_executor.h, src/web/pages.h
Found with gcc's -Wsuggest-override
Found with clang's -Winconsistent-missing-destructor-override
=> switch from virtual to override

src/content_manager.cc, src/metadata/libexif_handler.cc, src/search_handler.cc
Found with clang's -Wmissing-prototypes
=> add missing static

src/config/config_manager.cc, src/content_manager.cc, src/iohandler/io_handler_buffer_helper.cc, src/metadata/fanart_handler.cc, src/scripting/script.cc, src/search_handler.cc, src/util/string_converter.cc, src/util/task_processor.cc, src/util/thread_executor.cc
Found with -Wunreachable-code-return/break
=> remove unreachable returns and breaks

src/config/config_manager.cc
Running a test I got the message "file /etc/gerbera/js does not exists"
=> import script variable lost in copy&paste

src/config/config_manager.h, src/config/config_options.h, src/layout/layout.h, src/search_handler.h, src/storage/sqlite3/sqlite3_storage.h, src/storage/storage.h, src/transcoding/transcode_handler.h, src/transcoding/transcoding_process_executor.cc, src/util/executor.h, src/util/generic_task.h, src/util/thread_executor.h, src/web/pages.h
Found with clang's -Wextra-semi
=> remove extra semicolons elsewhere

src/autoscan.cc, src/iohandler/buffered_io_handler.cc, src/iohandler/file_io_handler.cc, src/iohandler/io_handler_buffer_helper.cc, src/iohandler/process_io_handler.cc, src/metadata/matroska_handler.cc, src/storage/sql_storage.cc
Found with unsignedLessThanZero
=> [cppcheck] do not check unsigned for negative

src/action_request.h, src/autoscan.h, src/autoscan_inotify.h, src/cds_objects.h, src/cds_resource.h, src/config/config_options.h, src/exceptions.h, src/metadata/fanart_handler.h, src/metadata/libexif_handler.h, src/metadata/matroska_handler.h, src/metadata/taglib_handler.h, src/server.h, src/storage/sqlite3/sqlite3_storage.h, src/subscription_request.h, src/web/session_manager.h
Found with noExplicitConstructor
=> [cppcheck] add explicit to single argument constructors

src/storage/storage.cc
=> [cppcheck] move the same condition out of if statement

src/content_manager.cc
lets first see if it help to gather more info for #737
=> WIP: improve log warning

src/autoscan_inotify.cc, src/cds_objects.cc, src/config/config_manager.cc, src/content_manager.cc, src/metadata/fanart_handler.cc, src/metadata/metadata_handler.cc, src/storage/sql_storage.cc, src/transcoding/transcode_ext_handler.cc, src/util/tools.cc, src/util/tools.h, src/web/add_object.cc, src/web/directories.cc, src/web/files.cc
=> workaround is_regular_file for file > 2GB on 32bit systems

src/metadata/metadata_handler.cc, src/util/tools.cc, src/util/tools.h
hopefully last thing we need for #737
=> workaround fs::file_size issue with ARM 32bit

src/config/config_manager.cc, src/metadata/exiv2_handler.cc, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/storage/mysql/mysql_storage.cc, src/storage/mysql/mysql_storage.h
=> add missing cleanups with non-default options

doc/conf.py, doc/scripting.rst, scripts/js/import.js, scripts/js/playlists.js
1. Removed obsolete references to Weborama and DVD.
2. Replaced pasted code snippets with inclusion from actual files to
simplify keeping them up to date.
**NOTE** I saw that some references to Apple Trailers were removed from `script.rst` but there are still some references in the code, so I left it.
=> Minor doc update.

CMakeLists.txt, src/action_request.cc, src/action_request.h, src/metadata/matroska_handler.cc, src/metadata/matroska_handler.h, src/server.cc, src/server.h, src/util/tools.cc, src/util/tools.h, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/util/upnp_quirks.h
next steps would be:
- replace/remove <protocolInfo> from config.xml with hard coded quirk flags (samsung, etc...)
- replace/remove <mappings> from config.xml with hard coded quirk flags (samsung, etc...)
- move quirks to upnp_quirks.cc and apply them according to detected type automatically
=> feat: #752 add client detection code

Dockerfile, config/config.xsd, config/config2.xsd, doc/config-import.rst, gerbera-web/mock-api/autoscan/autoscan-2f6d.json, gerbera-web/mock-api/autoscan/autoscan-3808.json, gerbera-web/mock-api/autoscan/autoscan-7443.json, gerbera-web/mock-api/autoscan/submit-complete-2f6d.json, gerbera-web/mock-api/void/active-check.json, gerbera-web/test/client/fixtures/autoscan-add-response.json, gerbera-web/test/client/fixtures/autoscan-item.json, gerbera-web/test/client/fixtures/index.html, gerbera-web/test/client/fixtures/submit-complete-2f6d.json, gerbera-web/test/client/fixtures/updates-with-task.json, gerbera-web/test/client/gerbera.autoscan.spec.js, gerbera-web/test/client/gerbera.updates.spec.js, gerbera-web/test/client/jquery.gerbera.autoscan.spec.js, gerbera-web/test/e2e/autoscan.spec.js, gerbera-web/test/e2e/page/home.page.js, gerbera-web/test/e2e/screenshot.doc.js, src/autoscan.cc, src/autoscan.h, src/config/config_manager.cc, src/content_manager.cc, src/content_manager.h, src/storage/sql_storage.cc, src/web/web_autoscan.cc, web/index.html, web/js/jquery.gerbera.autoscan.js
=> fix #778 remove ScanLevel, only do what was done in full

src/upnp_xml.cc
=> correctly handle upnp:artist@role[AlbumArtist]

src/upnp_cds.cc
I have always been wondering why my searches never return a result.
=> Add search result to correct container

src/contrib/cxxopts.hpp
=> cxxopts: update to 2.2.0

src/cds_objects.h, src/config/config_manager.cc, src/content_manager.cc, src/content_manager.h, src/exceptions.h, src/search_handler.h, src/server.cc, src/storage/mysql/mysql_storage.h, src/storage/sqlite3/sqlite3_storage.h, src/storage/storage.h, src/transcoding/transcoding.h, src/update_manager.h, src/url.cc, src/util/generic_task.h, src/util/task_processor.cc, src/util/timer.h, src/util/tools.cc, src/util/tools.h, src/web/add_object.cc, src/web/directories.cc, src/web/files.cc, src/web/items.cc, src/web/session_manager.h, src/web/tasks.cc, src/web/web_autoscan.cc, src/web/web_request_handler.cc, src/web/web_request_handler.h
inline doesn't seem useful.
std::string is default allocated to 0. Not needed in many cases.
=> no inline + size savings

src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/util/tools.cc, src/util/tools.h, test/core/CMakeLists.txt, test/core/test_ffmpeg_cache_paths.cc, test/core/test_upnp_xml.cc, test/mock/config_mock.h, test/util/test_tools.cc
=> Refactored caching of ffmpeg thumbnails.

scripts/install-duktape.sh, scripts/install-lastfm.sh, scripts/install-pugixml.sh, scripts/install-pupnp.sh, scripts/install-taglib111.sh, scripts/make_server_icons.sh, scripts/update-comment-header.sh, scripts/whitespace_cleanup.sh
=> scripts: run through shellcheck and use /bin/sh for all

src/util/xml_to_json.cc, src/util/xml_to_json.h, src/web/containers.cc, src/web/items.cc, src/web/web_request_handler.cc, web/js/gerbera-tree.module.js
… instead of automatic detection of property type. Hint is set to name and type of property.
=> Add Hint to set property type of JSON field to string, bool or number (fixes #879)

src/storage/sqlite3/sqlite3_storage.h
Fixes compilation on FreeBSD 13-CURRENT
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
=> Add missing unistd header

src/web/directories.cc, src/web/files.cc
I'm not sure whether this is the most efficient way, but it works! Fixes #855
=> Sort result of fs::directory_iterator

src/config/config_manager.cc
=> Restored option to hide PC directory

src/web/directories.cc, src/web/files.cc
Storing required info in temporary structure creates new objects.
=> Fix pointer to dereferenced objects

gerbera-web/mock-api/auth/config.json, gerbera-web/mock-api/files/parentId-0_start-0_count-25.json, gerbera-web/mock-api/files/tests/default.json, gerbera-web/mock-api/items/parent_id-0-start-0.json, gerbera-web/mock-api/items/parent_id-3808-start-0.json, gerbera-web/mock-api/items/tests/default.json, gerbera-web/mock-api/items/tests/overlay.test.json, gerbera-web/mock-api/mock.responder.js, gerbera-web/test/client/fixtures/config.json, gerbera-web/test/client/fixtures/converted-config.json, gerbera-web/test/client/gerbera.app.spec.js, gerbera-web/test/client/gerbera.auth.spec.js, gerbera-web/test/client/gerbera.autoscan.spec.js, gerbera-web/test/client/gerbera.clients.spec.js, gerbera-web/test/client/gerbera.items.spec.js, gerbera-web/test/client/gerbera.menu.spec.js, gerbera-web/test/client/gerbera.trail.spec.js, gerbera-web/test/client/gerbera.tree.spec.js, gerbera-web/test/client/gerbera.updates.spec.js, gerbera-web/test/client/jquery.gerbera.tree.spec.js, gerbera-web/test/e2e/items.spec.js, gerbera-web/test/e2e/menu.spec.js, gerbera-web/test/e2e/page/home.page.js, gerbera-web/test/e2e/page/test-utils.js, web/js/gerbera-app.module.js, web/js/gerbera-menu.module.js, web/js/gerbera-tree.module.js, web/js/gerbera-updates.module.js
Implemented storage of current item based on localStorage in browser.
Fixes #856
=> Store current item in localstorage and reload it on startup or refresh

doc/supported-devices.rst
Closes: https://github.com/gerbera/gerbera/issues/928
=> Docs: fix outdated information

.github/workflows/ci.yml, .github/workflows/docker.yml, cmake/FindFilesystem.cmake, conan/common, conan/dev, conan/minimal, conan/release, conanfile.py, doc/conan.rst
Example: https://github.com/ytimenkov/gerbera/actions/runs/144089972
=> Some conan fixes and GitHub actions

config/config.xsd, config/config2.xsd
Forgot to do so in #859 and #925
=> Reflect recent config changes in xsd

src/web/edit_load.cc
This may cause trouble in UI. May fix #938
=> Use boolean for title.editable

conanfile.py, scripts/install-spdlog.sh
Compiles and runs smoothly on my side
=> Update SPDLog to 1.7.0

scripts/install-pupnp.sh, src/util/upnp_headers.cc, src/util/upnp_headers.h
=> Update to PUPNP 1.14.0

src/autoscan.cc, src/autoscan.h, src/cds_objects.cc, src/config/config_manager.cc, src/iohandler/process_io_handler.cc, src/util/timer.cc, src/util/tools.cc, src/util/upnp_clients.cc, src/util/upnp_quirks.cc, src/web/session_manager.cc
Did these manually. Not sure how many are correct.
=> std::algorithm conversions

gerbera-web/test/client/jquery.gerbera.tree.spec.js, web/assets/theme/gerbera.css, web/js/jquery.gerbera.tree.js
Also autoscan badges now have full text and icon:
=> Color folders with children instead of badges saying true

src/contrib/cxxopts.hpp
=> cxxopts: update to 2.2.1

doc/install.rst
=> doc: add OpenWrt section

CMakeLists.txt, README.md, doc/compile.rst, src/action_request.cc, src/device_description_handler.cc, src/file_request_handler.cc, src/iohandler/file_io_handler.cc, src/iohandler/io_handler.cc, src/iohandler/mem_io_handler.cc, src/serve_request_handler.cc, src/server.cc, src/transcoding/transcode_ext_handler.cc, src/upnp_cds.cc, src/upnp_cm.cc, src/upnp_mrreg.cc, src/url_request_handler.cc, src/util/upnp_clients.cc, src/util/upnp_headers.cc, src/web/web_request_handler.cc
Same as https://github.com/gerbera/gerbera/pull/818 , just rebased and cleaned up (clang-format, less hacky cmake, etc...).
I'm not too familiar with CMake. No idea if the changes are OK.
find_package doesn't work with libnpupnp. It seems a .cmake file is required.
=> npupnp changes

src/metadata/metadata_handler.h, src/util/upnp_quirks.h
Found with modernize-use-using
=> clang-tidy: use using

test/util/test_upnp_headers.cc
=> Fix tests with npupnp

src/content_manager.cc
This is a pull request fixing issue gerbera/gerbera#985 by applying the change as proposed by Ian Whyman.
=> Fixes gerbera/gerbera#985

src/storage/sql_storage.cc
stream.clear() just clears the error flags but not the content
fixes: #1006
=> fix clearing stream

src/cds_resource.cc, src/config/config_options.h, src/config/config_setup.cc, src/content_manager.cc, src/database/sql_database.cc, src/metadata/metacontent_handler.cc, src/scripting/script.cc, src/upnp_xml.cc, src/web/config_load.cc, src/web/directories.cc, src/web/edit_load.cc, src/web/files.cc
Small readability improvement.
=> use structured binding declarations in for loops

src/transcoding/transcoding.cc, src/upnp_xml.cc
=> switch two loops to structured binding declarations

src/web/config_load.cc
=> Fix string conversion warning

src/autoscan_inotify.cc, src/autoscan_inotify.h, src/cds_objects.h, src/cds_resource.cc, src/config/config_manager.cc, src/config/config_manager.h, src/config/config_setup.cc, src/config/config_setup.h, src/content_manager.cc, src/database/mysql/mysql_database.cc, src/database/sql_database.cc, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h, src/file_request_handler.cc, src/main.cc, src/metadata/libexif_handler.cc, src/server.cc, src/transcoding/transcoding.h, src/update_manager.cc, src/upnp_xml.cc, src/util/tools.cc, src/web/directories.cc, src/web/edit_load.cc
* size_t for array indexes
* unsigned short for ports
* force title to be string in JSON
=> Use correct types

src/cds_resource.cc, src/cds_resource.h, src/content_manager.cc, src/file_request_handler.cc, src/metadata/ffmpeg_handler.cc, src/metadata/libexif_handler.cc, src/metadata/matroska_handler.cc, src/metadata/metacontent_handler.cc, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h, src/metadata/taglib_handler.cc, src/onlineservice/atrailers_content_handler.cc, src/onlineservice/sopcast_content_handler.cc, src/scripting/script.cc, src/scripting/script_names.h, src/upnp_xml.cc, src/web/add_object.cc, src/web/edit_load.cc, test/scripting/mock/script_test_fixture.cc
and move call to this method into get/setAttribute
issue was introduced in #1022
=> Fix wrong return in MetadataHandler::getResAttrName

src/web/config_load.cc, src/web/pages.h
size_t is an unsigned int under 32-bit, causing a redeclaration error.
=> fix compilation under 32-bit

src/config/config_manager.cc, src/content_manager.cc
First is a simplification.
Second is a fix.
=> some small fixes

doc/install.rst
Add instructions on how to install
=> docs: Add FreeBSD install section

src/autoscan.h, src/cds_objects.cc, src/cds_objects.h, src/config/config_generator.cc, src/config/config_setup.cc, src/server.h, src/subscription_request.h, src/upnp_cds.h, src/url.h, src/util/upnp_clients.cc, src/web/session_manager.h, test/config/fixtures/mock-config-all.xml, test/config/fixtures/mock-config-minimal.xml
Forwarded 2 spelling fixes from Debian - and added 11 more while doing it.
=> More minor spelling fixes

src/server.cc, src/server.h, src/util/tools.cc, src/util/tools.h, test/util/test_tools.cc
=> Generate IPv6 url correctly

src/database/mysql/mysql_database.cc, src/database/sql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc
Use DB autoincrement as ID values instead, like sensible people
=> Stop generating our own IDs

src/util/upnp_quirks.cc, src/web/config_load.cc
=> constexpr conversions

.dockerignore, .github/workflows/docker.yml, Dockerfile, scripts/install-duktape.sh, scripts/install-pupnp.sh
Upgrade to v2 of Dockers github actions (uses buildx)
=> Actions: Docker multi-arch build

src/web/directories.cc, src/web/files.cc
Move creation of converter to outer scope
fixes #1081
=> Avoid conversion of filename to integer

src/upnp_cds.cc, src/upnp_cm.cc, src/upnp_mrreg.cc
The improve upnp defines commit left out the npupnp codepath.
=> fix compilation with npupnp

src/file_request_handler.h
=> Fix refactoring leftover. Breaks browsing files.

src/cds_resource.h, src/content/content_manager.cc, src/content/content_manager.h, src/content/layout/builtin_layout.cc, src/content/scripting/js_functions.cc, src/database/sql_database.cc, src/file_request_handler.cc, src/metadata/exiv2_handler.cc, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/metadata/libexif_handler.cc, src/metadata/libexif_handler.h, src/metadata/matroska_handler.cc, src/metadata/matroska_handler.h, src/metadata/metacontent_handler.cc, src/metadata/metacontent_handler.h, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h, src/metadata/taglib_handler.cc, src/metadata/taglib_handler.h, src/upnp_xml.cc, src/util/xml_to_json.cc, src/web/edit_load.cc, web/js/gerbera-trail.module.js, web/js/jquery.gerbera.editor.js
We avoid searching for matching images on browse by adding them as resource on creation. Update is critical because the image would change with each file.
This PR is inspired by #365. The goal is to allow any image as container resource which can be set via config/ui. Also I intend to display the image on the web UI.
fixes #1116
=> Use resources on container and load folder image from container resources if available.

src/action_request.cc, src/action_request.h, src/config/client_config.h, src/config/config_setup.cc, src/context.cc, src/context.h, src/file_request_handler.cc, src/server.cc, src/server.h, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h, src/web/clients.cc, test/core/test_upnp_xml.cc, test/mock/config_mock.h, test/util/test_upnp_clients.cc
now that we have context it is quiet easy....
Saw this when writing unit tests.
=> make Clients class non static

src/database/sqlite3/sqlite_database.cc
fs::copy need option to overwrite files
=> SQLite-Backup not created if file already exists

CMakeLists.txt, test/CMakeLists.txt, test/config/CMakeLists.txt, test/content/CMakeLists.txt, test/content/main.cc, test/content/test_autoscan_timed.cc, test/core/CMakeLists.txt, test/scripting/CMakeLists.txt, test/util/CMakeLists.txt
This means each GTest test is now a CTest case, which is much nicer
=> CTest: discover gtest tests

src/util/tools.cc
=> Fix timespec_get return code check

src/iohandler/process_io_handler.cc
=> convert last timeval to timespec and pselect

gerbera-web/test/client/fixtures/container-data-astree.json, gerbera-web/test/client/fixtures/index.html, gerbera-web/test/client/gerbera.tree.spec.js, src/context.cc, src/context.h, src/request_handler.cc, src/request_handler.h, src/server.cc, src/server.h, src/upnp_xml.cc, src/upnp_xml.h, src/util/upnp_quirks.cc, src/web/containers.cc, src/web/edit_load.cc, test/core/test_upnp_xml.cc, web/index.html, web/js/gerbera-tree.module.js, web/js/jquery.gerbera.editor.js, web/js/jquery.gerbera.tree.js
=> Add images to folders in Web-UI

src/config/config_generator.cc, src/config/config_generator.h, src/config/config_manager.cc, src/config/config_setup.h, test/config/test_configgenerator.cc
Most of the XML tags are gone now, i.e. changes in config layout are reflected in ConfigGenerator.
=> Reworked ConfigGenerator to benefit from definitions in ConfigManager.

src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/upnp_cds.cc, src/upnp_xml.cc
Display thumbs as fanart images also via Upnp.
=> Make Ffmpg thumbs permanent resources

src/config/config_manager.cc, src/config/config_setup.h, src/content/autoscan_inotify.h, src/content/content_manager.cc, src/content/layout/builtin_layout.h, src/content/onlineservice/atrailers_content_handler.h, src/content/onlineservice/atrailers_service.h, src/content/onlineservice/sopcast_content_handler.h, src/content/onlineservice/sopcast_service.h, src/database/database.cc, src/iohandler/io_handler_chainer.cc, src/serve_request_handler.h, src/transcoding/transcode_dispatcher.h, src/transcoding/transcode_ext_handler.cc, src/transcoding/transcode_ext_handler.h, src/upnp_xml.cc, src/url_request_handler.h, src/util/mime.h, src/util/process.cc, src/util/tools.cc, src/util/tools.h, src/util/upnp_clients.h, src/web/pages.h
I'm sure manual review of these is needed.
=> some cleanups

src/metadata/metacontent_handler.cc
=> Metacontent_handler: fix nullptr dereference

.github/workflows/publish-deb.yml
Need to use a PPA for bionic's git because its soooo ooold
=> Actions: Fix deb build with checkout@v2

src/metadata/matroska_handler.cc
=> remove C format function usage

src/content/content_manager.cc, src/content/onlineservice/online_service.cc, src/util/upnp_quirks.cc, src/web/config_load.cc, src/web/directories.cc
=> simplify some std::arrays through CTAD

config/config.xsd, config/config2.xsd, doc/config-server.rst, src/config/config_manager.cc, test/config/test_configmanager.cc
and make it path option to check on config check.
=> Rename init-script option

.github/workflows/docker.yml, Dockerfile, README.Docker.md, README.md, cmake/modules/GenCompileInfo.cmake, scripts/docker/docker-entrypoint.sh
Dont try to create a config file if it exists
Dont put git dirty status into build version
Add npupnp flag to README
Closes: #1109
Closes: #1193
=> Update README, DockerHub Readme

src/util/tools.cc
=> Fix compilation error under debian:stable

src/iohandler/process_io_handler.cc, src/util/tools.cc
Some small build fixes for Haiku
=> Haiku build fixes

src/config/config_manager.cc
=> Activate check for CFG_IMPORT_SCRIPTING_IMPORT_SCRIPT

src/content/content_manager.cc, src/content/onlineservice/atrailers_content_handler.cc, src/content/onlineservice/sopcast_content_handler.cc, src/util/tools.cc
The latter is not available in Haiku for some reason.
=> use clock_gettime instead of timespec_get

src/database/mysql/mysql.sql, src/database/sqlite3/sqlite3.sql
=> Fix initial INSERT statements

src/content/scripting/script.cc, src/metadata/metacontent_handler.cc, src/metadata/metadata_handler.cc, src/web/config_load.cc
=> use some structured bindings

src/config/client_config.cc, src/config/client_config.h, src/util/mt_inotify.cc, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/web/files.cc
=> simplify some struct stuff

web/vendor/popper/popper.js
=> web: Fix popper.js error (use npm version)

scripts/debian/build-deb.sh
=> Build deb files with debug logging support

CMakeLists.txt
5.3 introduced chrono header which we use
Fixes: #1214
=> CMake: set fmt min version

doc/compile.rst
based on #1148 
Thanks to @BobManMasher
=> Add description how to compile under debian buster

src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h, src/util/timer.cc
Also handles race conditions on shutdown.
I'm not sure but it may also remove #1241
=> Interrupt startup when database is already in use

src/util/mime.cc
=> Detect mimetype from extension

scripts/debian/build-deb.sh, scripts/debian/postinst
CPack/Deb: Set CMAKE_INSTALL_PREFIX=/usr
=> deb fixups

src/config/config_manager.cc
=> Avoid unset option CFG_IMPORT_AUTOSCAN_INOTIFY_LIST

src/metadata/taglib_handler.cc
=> Taglib: Extract from mp3 with ID3v1 tags, improve messaging

CMakeLists.txt, src/database/mysql/mysql_database.cc, src/database/sql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc, src/main.cc
- Convert exec to take a string
- Set a minium sqlite version to 3.7.0
- Use SQLite Write Ahead Log mode (https://sqlite.org/wal.html)
- More detailed log timestamps in debug mode
=> DB: Transactions for inserts/updates

src/server.cc
=> Set web ui message depending on virtual url property

src/content/content_manager.cc, src/content/content_manager.h
contributes in my case another 15% to #1272
=> Add cache for containers to improve import speed

src/config/config_setup.cc, src/content/content_manager.cc, src/server.cc, src/util/tools.cc
Fix compliation for Ubuntu:18.04 and debian:stable. Somehow it worked before the merge 😟 
Also fix message for ui when virtual url already contains protocol.
=> Misc fixes

src/database/sql_database.cc
Resolves: https://github.com/gerbera/gerbera/issues/1298
=> Fix transaction start for MySQL

src/database/mysql/mysql_database.cc
Fixes: https://github.com/gerbera/gerbera/issues/1301
=> MySQL: Init: Dont try to execute empty string

src/content/layout/builtin_layout.cc, src/content/layout/builtin_layout.h
This fixes #1310, adding a Directories container under Audio.
=> Add Directories container to Audio in builtin layout (#1310).

gerbera-web/test/e2e/login.spec.js, gerbera-web/test/e2e/page/home.page.js, src/config/client_config.cc, src/config/config_setup.cc, src/config/directory_tweak.cc, src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/content/onlineservice/task_processor.cc, src/database/sql_database.cc, src/iohandler/file_io_handler.cc, src/iohandler/file_io_handler.h, src/iohandler/io_handler_buffer_helper.h, src/iohandler/io_handler_chainer.h, src/iohandler/mem_io_handler.cc, src/metadata/taglib_handler.cc, src/upnp_xml.cc, src/upnp_xml.h, src/web/clients.cc, src/web/items.cc, web/js/gerbera-app.module.js, web/js/gerbera-clients.module.js, web/js/gerbera-config.module.js, web/js/gerbera-items.module.js, web/js/gerbera-menu.module.js, web/js/gerbera-trail.module.js, web/js/gerbera-tree.module.js, web/js/jquery.gerbera.config.js, web/js/jquery.gerbera.editor.js, web/js/jquery.gerbera.items.js, web/js/jquery.gerbera.tweak.js
Improve code quality by addressing CodeQL messages
=> Address CodeQL messages

src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/content/scripting/js_functions.cc, src/content/scripting/playlist_parser_script.cc, src/main.cc, src/web/add.cc
All errors are handled but the messages are misleading
=> Log message from directory_entry constructor

src/cds_objects.cc, src/database/sql_database.cc, src/util/tools.cc, src/util/tools.h
=> Handle parsing of unsigned numbers

src/content/autoscan_inotify.cc, src/content/content_manager.cc
This brings back the permission denied messages from the C code.
Remove handling of . and .. which are not returned by `directory_iterator`.
=> Handle protected directories

src/content/content_manager.cc
=> Remove container if access to directory was removed

src/util/upnp_clients.cc
=> Reverse search clients by agent to prefer configured items

src/config/client_config.cc, src/config/config_generator.cc, src/config/config_manager.cc, src/config/config_manager.h, src/config/config_options.cc, src/config/config_setup.cc, src/config/config_setup.h, src/config/directory_tweak.cc, src/config/directory_tweak.h, src/content/autoscan_list.cc, src/content/content_manager.cc, src/database/sql_database.cc, src/web/directories.cc
=> replace find() end() comparisons with count()

src/config/client_config.cc, src/config/client_config.h, src/config/config_options.cc, src/config/config_setup.cc, src/config/directory_tweak.cc, src/config/directory_tweak.h, src/content/autoscan_list.cc, src/content/autoscan_list.h, src/database/sql_database.cc, src/file_request_handler.cc, src/util/tools.cc
=> change C macros to numeric_limits

CMakeLists.txt, conanfile.py, src/main.cc, src/server.cc, src/util/tools.cc
Tidy up startup and error messaging.
Log IPv6 Addresses/ports too.
Add warning if user is providing an IP instead of interface.
=> Add Upnp Init retry logic.

src/config/config_setup.h, src/content/scripting/script_names.h, src/metadata/metadata_handler.h, src/web/config_save.cc
=> change constexpr in headers to static

src/config/config_setup.h, src/util/thread_runner.h
Found with modernize-use-using
=> clang-tidy: replace typedef with using

src/config/config_manager.cc, src/config/config_setup.cc, src/database/sql_database.cc, src/util/mime.cc, src/web/files.cc
These become errors if fs::path is an std::wstring.
=> fs::path conversions

src/content/content_manager.cc, src/content/content_manager.h
=> Enable ContainerArt for PC Directory

doc/config-import.rst
Added documentation how to add meta data for exiv2 library usage as requested in issue #121 and implemented in PR #122
=> Documentation for exiv2 meta data usage

src/content/content_manager.cc
=> Only use music tracks as container art source

doc/supported-devices.rst, src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, test/core/test_searchhandler.cc
Rework sql statement generation
fixes #1407
=> Add support for Windows Media Player

src/cds_objects.cc, src/cds_objects.h, src/config/client_config.cc, src/config/client_config.h, src/content/autoscan.cc, src/content/autoscan.h, src/content/scripting/script.cc, src/database/mysql/mysql_database.h, src/database/sql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite_database.h, src/metadata/metadata_handler.cc, src/transcoding/transcoding.cc, src/util/jpeg_resolution.cc, src/web/clients.cc, src/web/containers.cc, src/web/edit_load.cc, src/web/items.cc, src/web/web_autoscan.cc, src/web/web_request_handler.cc, src/web/web_request_handler.h
=> string_view conversions

src/cds_objects.h, src/common.h, src/config/config_setup.cc, src/content/autoscan.cc, src/content/autoscan.h, src/content/content_manager.cc, src/content/content_manager.h, src/content/onlineservice/curl_online_service.cc, src/content/onlineservice/online_service.cc, src/content/onlineservice/online_service.h, src/content/onlineservice/task_processor.cc, src/content/scripting/script.cc, src/content/update_manager.cc, src/database/sql_database.cc, src/database/sqlite3/sqlite_database.cc, src/iohandler/buffered_io_handler.cc, src/util/thread_runner.h, src/util/timer.cc, src/util/timer.h, src/util/tools.cc, src/util/tools.h, src/util/upnp_quirks.cc, src/web/clients.cc, src/web/config_load.cc, src/web/edit_load.cc, src/web/session_manager.cc, src/web/session_manager.h, src/web/web_autoscan.cc
=> massive std::chrono conversion

doc/config-import.rst, src/metadata/metacontent_handler.cc
also search locally for matching images
=> Determine container art image from files

doc/compile.rst
Added documentation in the compile.rst how to build a docker container and how to adapt the compile options.
=> Added documentation how to build the docker container

src/config/client_config.cc, src/config/config_manager.cc, src/config/directory_tweak.cc, src/content/autoscan_list.cc, src/metadata/ffmpeg_handler.cc, src/util/tools.cc
In a different branch, I converted most algorithms to use the new ranges library in C++20. These were things I noticed.
=> algorithm cleanups

src/upnp_cds.cc, src/upnp_cds.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h
=> Implement SAMSUNG X_GetFeatureList

src/config/config_manager.cc, src/config/config_options.cc, src/database/search_handler.cc, src/database/sql_database.cc, src/upnp_xml.cc, src/util/timer.cc
The value can be passed directly to find.
=> remove some pointless lambdas

src/util/xml_to_json.cc
These are only used in boolean context.
=> change some size_t to bool

src/content/autoscan.cc, src/content/autoscan.h, src/content/content_manager.cc, src/content/content_manager.h
=> remove several implicit fs::path conversions

src/content/content_manager.cc, src/database/mysql/mysql_database.cc, src/database/sqlite3/sqlite_database.cc, src/metadata/taglib_handler.cc, src/util/string_converter.cc, web/gerbera-config-expert.json
- escape slashes in virtual path
- remove leading TXXX tag
- save last modified for timed_autoscans
- cleanup zlib includes
last weeks' collection 
- fixes #1429
- fixes #1410
=> Misc improvements

src/metadata/ffmpeg_handler.h
=> add missing optional header for GCC11

.github/workflows/ci.yml, src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc, src/util/thread_runner.h, web/gerbera-config-expert.json
=> Make transactions for SQLite thread safe

src/database/sql_database.cc
The statement did not work for ages, now it did the wrong thing.
fixes #1454
=> Generate correct statement for metadata table

scripts/js/playlists.js
fixes #1458 
Extension is already removed in import code
=> Fix double truncation of playlist name

src/cds_objects.h, src/metadata/libexif_handler.h, src/upnp_cds.h, src/upnp_cm.h, src/upnp_mrreg.h, src/util/mime.cc, src/util/mime.h
Added missing virtual and moved one destructor from protected to public,
as it should be.
=> manual destructor changes

src/iohandler/curl_io_handler.cc
=> use C++ cast

gerbera-web/test/client/gerbera.items.spec.js, gerbera-web/test/client/jquery.gerbera.editor.spec.js, src/server.cc, src/util/tools.cc, src/util/tools.h, web/js/jquery.gerbera.editor.js
fixes #1470 
Encoding was missing and decoding was done twice.
=> Encoding of web editor arguments

src/content/content_manager.cc
time_since_epoch can be negative and must be related to time_t 0.
=> Revert last_write_time to seconds since 1970

src/database/sql_database.cc
=> Fix parseSortStatement

src/metadata/exiv2_handler.cc
std::string is being used here.
=> remove pointless const_cast

src/util/tools.cc
=> return std::nullopt for std::optional

src/config/config_definition.cc, src/config/config_setup.h
GCC's -fanalyzer complains about some null pointer allocation.
=> string_view to string conversions

src/database/sql_database.cc
GCC's -fanalyzer complains that null pointers are created otherwise.
Some cleanup posibilities showed up.
=> initialize several unique_ptrs

src/action_request.cc, src/config/config_manager.cc, src/content/onlineservice/curl_online_service.cc, src/content/onlineservice/online_service.h, src/content/update_manager.cc, src/upnp_xml.cc
Reverts gerbera/gerbera#1483
Breaks ubuntu:18.04
https://github.com/gerbera/gerbera/runs/2714005392
=> Revert "initialize several unique_ptrs"

src/cds_objects.cc, src/cds_objects.h, src/content/onlineservice/online_service.h, src/database/database.h, src/util/generic_task.cc, src/util/generic_task.h, src/util/process_executor.cc, src/util/process_executor.h, src/util/string_converter.cc, src/util/string_converter.h, src/util/timer.cc, src/util/timer.h, src/web/session_manager.cc, src/web/session_manager.h, src/web/web_request_handler.cc, src/web/web_request_handler.h
=> move some initializations up

.github/workflows/ci.yml, README.md, src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, src/database/sql_database.h, src/upnp_cds.cc, test/core/test_searchhandler.cc
=> Refactor SearchHandler to use ColumnMapper instead of hard coded texts.

src/database/search_handler.cc
=> manual structured binding conversions

src/main.cc, src/util/thread_runner.h
=> Haiku patches

src/content/content_manager.cc, src/content/content_manager.h, src/server.cc, src/server.h
=> default init some members

src/config/config_definition.cc, test/config/fixtures/mock-config-all.xml, test/config/fixtures/mock-config-minimal.xml, test/config/fixtures/mock-import-magic-js-online.xml, test/config/fixtures/mock-import-magic-js.xml, test/config/fixtures/mock-import-magic.xml, test/config/fixtures/mock-import-mappings.xml, test/config/fixtures/mock-import-none.xml
=> add m4a support for taglib

src/config/client_config.cc, src/config/client_config.h, src/config/config_setup.cc, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/web/clients.cc
=> make bultinClientInfo constexpr

src/upnp_xml.cc, src/util/upnp_clients.cc, src/web/containers.cc
-fanalyzer claims null pointers are allocated otherwise.
=> more make_unique changes

src/config/config_generator.cc
Avoids having to type \n everywhere.
=> use raw strings for multi line ones

src/config/config_setup.cc
=> remove duplicate include

src/content/layout/builtin_layout.cc, src/transcoding/transcode_ext_handler.cc, src/upnp_xml.cc
=> match else and if blocks

src/content/onlineservice/atrailers_content_handler.cc, src/content/onlineservice/curl_online_service.cc, src/content/onlineservice/sopcast_content_handler.cc, src/iohandler/buffered_io_handler.cc, src/main.cc, src/metadata/exiv2_handler.cc, src/metadata/libexif_handler.cc, src/metadata/taglib_handler.cc, src/server.cc, src/upnp_mrreg.cc, src/upnp_xml.cc, src/util/mt_inotify.cc, src/util/process.cc, src/util/tools.cc, src/util/upnp_clients.cc
=> remove pointless blank lines

src/content/content_manager.cc
=> use std::replace instead of replaceAllString

src/action_request.cc, src/action_request.h, src/cds_objects.h, src/config/client_config.cc, src/config/directory_tweak.h, src/content/onlineservice/curl_online_service.cc, src/content/onlineservice/curl_online_service.h, src/content/onlineservice/lastfm_scrobbler.cc, src/content/onlineservice/lastfm_scrobbler.h, src/content/scripting/playlist_parser_script.cc, src/content/scripting/playlist_parser_script.h, src/content/scripting/script.cc, src/content/scripting/script.h, src/upnp_cds.cc, src/upnp_cds.h
=> default member init

src/database/search_handler.cc, src/database/sql_database.cc
=> replace const static with static const

src/request_handler.cc
=> remove const so move can be used

src/content/onlineservice/sopcast_content_handler.cc
=> lambda conversion

src/database/sql_database.cc, src/metadata/metacontent_handler.cc, src/util/tools.cc, src/util/tools.h, src/util/xml_to_json.cc
The original reference is modified. There's no need to return a copy.
=> fix replace string functions

src/main.cc
=> use sizeof for snprintf

src/config/config_setup.h
=> pass by value and std::move

src/metadata/libexif_handler.cc
Reorganize endless if
Simplify other code
Addresses
https://github.com/gerbera/gerbera/security/code-scanning/202?query=ref%3Arefs%2Fheads%2Fmaster
=> Cleanup exifhandler

src/content/autoscan_inotify.cc, src/content/autoscan_list.cc, src/content/content_manager.cc, src/database/sql_database.cc, src/metadata/metacontent_handler.cc, src/util/tools.cc, src/util/tools.h, src/web/directories.cc, src/web/files.cc
Saves size. More efficient too.
=> string ref to string_view conversion

src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
=> default initialize members in mysql

src/content/scripting/playlist_parser_script.cc
=> add missing nullptr check

src/util/tools.cc
=> add missing close

src/iohandler/io_handler_buffer_helper.cc, src/iohandler/io_handler_buffer_helper.h
=> default initialize some io stuff

src/database/mysql/mysql_database.h
=> add missing default initialization

src/server.h
=> server: default init some variables

src/content/content_manager.cc, src/database/search_handler.cc
Avoids a missing return statement warning.
=> use make_pair

src/util/tools.h
=> Fix lastfm compilation

src/web/files.cc, src/web/web_request_handler.cc
=> remove several {}

src/transcoding/transcode_ext_handler.cc
=> small error handle

src/main.cc
As of C++17, fopen supports an x flag which is equivalent to O_EXCL,
which fails if file exists.
=> replace POSIX file stuff with C

src/database/mysql/mysql_database.cc
=> Fix MySQL migration

src/config/config_manager.cc, src/metadata/metacontent_handler.cc, src/util/upnp_headers.cc, src/util/upnp_quirks.cc, src/web/config_save.cc
map does not need = to construct.
=> cosmetic map changes

src/cds_resource.h, src/database/sql_database.cc, src/upnp_xml.cc
=> Regression: Samsung Compatibility

src/content/content_manager.cc
=> small lambda conversion

src/database/sql_database.cc
=> remove manual loop

src/database/sql_database.cc
There's no random access being performed here.
=> replace std::list with std::vector

src/content/content_manager.cc, src/database/database.h, src/database/sql_database.cc
Add some missing moves as well.
=> add a missing this->

src/config/dynamic_content.h, src/content/onlineservice/atrailers_service.cc, src/content/onlineservice/atrailers_service.h, src/content/onlineservice/online_service.cc, src/content/onlineservice/online_service.h, src/content/onlineservice/sopcast_service.cc, src/content/onlineservice/sopcast_service.h, src/request_handler.cc, src/request_handler.h, src/server.cc, src/server.h, src/util/upnp_clients.h
=> const member function conversions

src/database/mysql/mysql.sql, src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite3.sql, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
=> SQLDatabase: Refactor init and upgrade

src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
Fixes some narrowing conversions
=> change length parameter to size_t

src/content/autoscan_inotify.h, src/content/autoscan_list.cc, src/content/autoscan_list.h, src/content/onlineservice/atrailers_content_handler.cc, src/content/onlineservice/atrailers_content_handler.h, src/content/onlineservice/sopcast_content_handler.cc, src/content/onlineservice/sopcast_content_handler.h, src/database/database.cc, src/database/database.h, src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h, src/metadata/exiv2_handler.cc, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/metadata/libexif_handler.cc, src/metadata/libexif_handler.h, src/metadata/matroska_handler.cc, src/metadata/matroska_handler.h, src/metadata/metacontent_handler.cc, src/metadata/metacontent_handler.h
Move simple ones to header files.
=> several constructor changes

doc/compile.rst, src/upnp_xml.cc, test/core/test_upnp_xml.cc
=> Subtitle: Add resouce and CaptionInfoEx

src/main.cc
=> simplify pidfile write

CMakeLists.txt, src/config/config_manager.cc, src/upnp_common.h, src/upnp_xml.cc
Device description cannot access quirks, so add it for all devices (hopefully they ignore it)
=> Add ProductCap to please Samsung TVs

src/cds_objects.h
The reference is not modified.
=> add missing const

src/config/config_generator.cc, src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/database/search_handler.cc, src/database/sql_database.cc, src/web/add_object.cc, src/web/auth.cc, src/web/config_save.cc
=> don't default assign nullptr to smart pointers

src/cds_objects.h, src/content/autoscan_inotify.cc, src/content/autoscan_inotify.h, src/content/content_manager.cc, src/content/scripting/script.cc, src/database/sql_database.cc, src/metadata/ffmpeg_handler.cc, src/metadata/libexif_handler.cc, src/metadata/matroska_handler.cc, src/metadata/metacontent_handler.cc, src/metadata/metadata_handler.cc, src/metadata/taglib_handler.cc, src/upnp_xml.cc, src/web/add_object.cc, test/core/test_upnp_xml.cc
push_back with std::move is more efficient.
=> pass by value

src/database/search_handler.cc, src/util/tools.cc
toLower does the same.
Also removed a pointless assignment.
=> remove aslowercase

src/config/config_setup.cc, src/request_handler.cc, src/web/config_load.cc
=> remove std from std::next

doc/compile.rst
=> Add link to database doc

src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, src/database/sql_database.h, src/metadata/taglib_handler.cc, src/metadata/taglib_handler.h, src/web/pages.cc, src/web/pages.h
Format fixes were also done along the way.
=> several string_view conversions

doc/compile.rst, src/cds_resource.cc, src/cds_resource.h, src/database/database.h, src/database/mysql/mysql-upgrade.xml, src/database/mysql/mysql.sql, src/database/mysql/mysql_database.cc, src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite3-upgrade.xml, src/database/sqlite3/sqlite3.sql, src/database/sqlite3/sqlite_database.cc, src/metadata/metadata_handler.h, test/core/test_searchhandler.cc, test/mock/database_mock.h
Columns for attributes are added during startup.
This brings search capability for resource properties.
This is the basis for tracking updates on external resources (like subtitles)
=> Move resources to separate table.

src/util/tools.h
Fixes -Wunused-template warnings.
=> remove wrong static

src/config/config_definition.cc, src/content/scripting/script.cc, src/database/sql_database.cc, src/database/sqlite3/sqlite_database.cc, src/metadata/taglib_handler.cc
not sure about the dynamic_cast commit.
=> small cleanups

src/transcoding/transcode_ext_handler.cc
=> remove pointless temporary

src/web/web_request_handler.cc, src/web/web_request_handler.h
=> more unique_ptr

src/server.cc
=> remove ret variable

src/config/client_config.cc
=> move make_shared outside of initializer list

src/database/sql_database.cc, src/upnp_cds.cc, src/upnp_cds.h, src/upnp_xml.cc, src/upnp_xml.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h, test/database/test_database.cc, web/cds.xml
=> Fix X_GetFeatureList (Samsung)

src/util/tools.cc, src/util/tools.h, src/web/session_manager.cc, src/web/session_manager.h
=> make uiUpdateIDs a unique_ptr

src/iohandler/process_io_handler.cc, src/iohandler/process_io_handler.h
=> use move with shared_ptr

src/database/sql_database.cc
=> move make_unique down

doc/dev-database.rst, gerbera-web/test/client/fixtures/index.html, scripts/js/common.js, scripts/js/playlists.js, src/content/content_manager.cc, src/content/scripting/script.cc, src/database/sql_database.cc, src/web/edit_load.cc, web/assets/theme/gerbera.css, web/index.html, web/js/jquery.gerbera.editor.js
=> Send container updates

src/config/config_definition.cc, src/database/search_handler.cc, src/database/sql_database.cc
It's not needed with class types
=> remove some = {}

src/cds_resource.cc, src/cds_resource.h
=> use map.emplace

src/cds_objects.h, src/config/client_config.h, src/config/directory_tweak.h, src/config/dynamic_content.h, src/content/autoscan.h, src/content/autoscan_list.h, src/content/onlineservice/task_processor.h, src/database/sqlite3/sqlite_database.h, src/transcoding/transcoding.h, src/util/generic_task.h, src/util/process_executor.h, src/util/string_converter.h, src/util/thread_executor.h, src/util/timer.h, src/web/session_manager.h, src/web/web_request_handler.h
These are default constructed.
=> remove pointless {}

src/upnp_xml.cc, src/upnp_xml.h, src/util/upnp_quirks.cc, src/web/containers.cc, src/web/edit_load.cc, src/web/items.cc
Simpler and allows to use structured bindings.
=> replace reference parameter with std::pair

src/content/scripting/script.cc
=> move several variables down

src/util/tools.cc
=> use auto instead of const char*

src/file_request_handler.cc, src/serve_request_handler.cc, src/url_request_handler.cc, src/web/web_request_handler.cc
=> fix wrong define

src/database/mysql/mysql-upgrade.xml, src/database/mysql/mysql_database.cc
fixes #1736 
rework `storeInternalSetting` to use format
=> Fix broken upgrade script

src/config/config_manager.cc, src/config/config_manager.h, src/util/upnp_headers.cc, src/util/upnp_headers.h, test/util/test_upnp_headers.cc
With these,
```
git grep make_unique\<std src
```
returns 0.
=> final unique_ptr removals

src/database/sql_database.cc, src/database/sql_database.h
Hope this fixes the build error on master
=> fmt disallows string_view as format specifier

test/config/fixtures/mock-config-minimal.xml
=> Add dynamic containers setup

src/database/sql_database.cc
=> use auto and CTAD

src/database/mysql/mysql_database.h, src/database/sql_database.h, src/database/sqlite3/sqlite_database.h
The string_view version does the same anyway.
=> remove const char version of quote

src/util/upnp_headers.cc
=> add missing move

src/content/autoscan_inotify.cc, src/content/autoscan_inotify.h
=> remove shared_ptr from vector

src/cds_objects.h, src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/web/containers.cc, src/web/items.cc, src/web/web_autoscan.cc
=> several auto conversions

src/database/search_handler.cc, src/database/search_handler.h, src/iohandler/process_io_handler.cc, src/iohandler/process_io_handler.h
avoids copies and forces moves.
=> rvalue reference conversions

src/upnp_xml.cc, src/upnp_xml.h
deque has a push_front method.
=> convert vector to deque

src/server.cc, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/web/config_save.cc, src/web/pages.cc, src/web/pages.h
=> Refresh Clients config in ClientList after change of config in UI

src/action_request.cc, src/action_request.h, src/upnp_xml.cc, src/upnp_xml.h
=> convert Quirks to unique_ptr

src/database/sql_database.cc, src/serve_request_handler.cc, src/util/tools.cc, src/web/config_load.cc
=> remove single argument std::string

src/config/config_setup.cc
=> remove pointless to_string

src/database/sql_database.cc
=> use some auto and CTAD

src/config/client_config.cc, src/config/client_config.h, src/util/upnp_clients.cc
=> pass ClientInfo by unique_ptr

src/config/config_definition.cc, src/config/dynamic_content.cc, src/config/dynamic_content.h
Avoids empty or duplicate values
Addresses #1726
=> Add validation for DynamicContent::location

src/metadata/matroska_handler.cc
=> change to auto&&

src/util/upnp_quirks.cc
Fixes warnings with WITH_DEBUG=OFF.
=> add variout maybe_unused

src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
=> pass std::string by const reference

src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h
=> get rid of unused variable

src/metadata/taglib_handler.cc
Helps with readability. Also provides a size reduction because of
auto&&.
=> use more auto in taglib

src/config/config_setup.cc, src/content/content_manager.cc, src/content/onlineservice/task_processor.cc, src/metadata/metacontent_handler.cc
=> more move with push_back

src/content/onlineservice/online_service.cc, src/content/onlineservice/online_service.h, src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h
=> manual const conversions

src/database/sql_database.cc, src/web/items.cc
=> avoid doing work in if statements

src/metadata/matroska_handler.cc
=> simplify while loop slightly

src/metadata/matroska_handler.cc
=> use some auto

scripts/debian/build-deb.sh
=> debian::unstable uses libduktape206

scripts/debian/build-deb.sh
News Dome printout to fix unstable build
=> improve debian script

src/config/config_definition.cc, src/config/config_setup.cc, src/config/config_setup.h, src/content/scripting/script.cc, src/web/config_load.cc, web/js/jquery.gerbera.config.js
=> Add support for default values in config UI

src/content/content_manager.cc
=> Fix linkage error in on aarch64 with g++-10

src/metadata/taglib_handler.cc
=> Read flac audio properties even if image does not exist

.github/workflows/publish-deb.yml, scripts/debian/build-deb.sh
Pass build type to build script to detect correct system of container
=> Build debian with arguments

src/upnp_xml.cc
=> some auto&& removals

src/config/config_generator.cc, src/config/config_manager.cc, src/file_request_handler.cc, src/iohandler/process_io_handler.cc, src/metadata/ffmpeg_handler.cc, src/util/tools.cc
=> remove unused assigned values

src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, test/mock/database_mock.h
=> const ref conversion

CMakeLists.txt
CMake includes a FindCURL.cmake
=> use normal libcurl search

src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, src/upnp_cds.cc, test/mock/database_mock.h
=> convert reference to value

src/database/search_handler.h
No point since the lambda can't be removed.
=> replace find_if with any_of

src/database/search_handler.h
=> Ensure EnumMapper creates its own copies

src/util/thread_runner.h
=> add maybe_unused for builds without DEBUG

src/database/search_handler.cc
=> remove return after throw

src/upnp_cds.cc, src/upnp_xml.cc, src/upnp_xml.h, test/core/test_upnp_xml.cc
Simpler. It's never null either.
=> replace pointers with references

src/content/content_manager.cc, src/content/layout/builtin_layout.cc
=> remove unused variables

src/upnp_xml.cc
=> use auto with constexpr

.gitignore
=> gitignore: Add buildconfig

src/util/string_converter.cc, src/util/tools.cc
It's more accurate here than numeric limits.
Also fix port type.
=> use string::npos

src/request_handler.cc, src/request_handler.h
=> splitUrl: use std::string

src/content/scripting/script.cc, src/database/sqlite3/sqlite_database.cc, src/metadata/exiv2_handler.cc
=> rename several shadowed variables

src/util/timer.cc
More readable to have the variable in front.
=> use auto for Timer constructors

src/content/content_manager.cc, src/content/content_manager.h, src/iohandler/process_io_handler.cc
Also removed the lambda and switched to normal std::remove.
=> std::shared_ptr<Executor> value conversions

src/database/sql_database.cc, src/upnp_xml.cc
=> remove some lambdas

scripts/debian/build-deb.sh
realpath seems to remove it in CI calls
=> Ensure Root dir teminates with /

src/cds_objects.h, src/content/content_manager.cc, src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, src/upnp_xml.cc
There is some potential to speed up how objects are created or updated
=> Optimize CdsObject creation/updates

src/util/timer.cc
Add a continue; to get rid of some code duplication.
=> simplify loop

src/content/autoscan_inotify.cc
=> replace loop with std::find

src/config/config_definition.h, src/config/config_setup.h, src/content/onlineservice/sopcast_content_handler.cc, src/upnp_xml.cc
The + operator can be used.
Also added some fmt::format conversions.
=> remove std::insert

src/content/autoscan_inotify.cc
=> remove dead assignments

src/content/autoscan_inotify.cc, src/content/autoscan_list.cc, src/web/session_manager.cc
Add a continue to avoid some code duplication.
=> simplify it loop slightly

src/util/mt_inotify.cc, src/web/config_save.cc
=> move variables down

src/content/content_manager.cc, src/content/content_manager.h, src/web/web_autoscan.cc
moves are cheaper than copies.
=> rvalue conversions

src/database/sql_database.cc, src/web/config_load.cc, src/web/directories.cc, src/web/files.cc
No need to use operator[] aka try_emplace since this is going into an
empty map.
=> more emplace conversions

src/config/config_setup.cc, src/main.cc, src/request_handler.cc, src/upnp_xml.cc
=> use std::strlen

src/util/process.cc
=> use std::system

doc/compile.rst
Make sure we can build gerbera by following the instructions
=> Update instructions to match CMake requirements

src/content/scripting/scripting_runtime.cc
=> use std::abort

src/main.cc
=> use std::exit

src/config/config_setup.cc, src/main.cc
=> replace substr with startswith

src/content/scripting/script.cc, src/content/scripting/script.h, src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, src/util/tools.cc, src/util/upnp_quirks.h
=> use std::int32_t

src/config/config_definition.h, src/config/config_generator.cc, src/config/config_setup.cc, src/database/search_handler.cc, src/metadata/exiv2_handler.cc, src/metadata/taglib_handler.cc
These are used in boolean context.
=> replace several substr calls with startswith

src/config/client_config.cc, src/config/config_definition.cc, src/config/config_options.cc, src/config/directory_tweak.cc, src/config/dynamic_content.cc, src/content/autoscan_list.cc, src/util/upnp_clients.cc, src/util/xml_to_json.cc, src/web/config_load.cc, src/web/files.cc, src/web/session_manager.cc
value is the recommended way to do lambdas. Small size decrease.
=> capture several lambda refs by value

src/content/scripting/playlist_parser_script.cc, src/content/scripting/playlist_parser_script.h, src/iohandler/file_io_handler.cc, src/iohandler/file_io_handler.h, src/main.cc, src/metadata/matroska_handler.cc, src/util/process.cc, src/util/tools.cc
=> std file conversions

src/iohandler/curl_io_handler.cc, src/iohandler/io_handler_buffer_helper.cc, src/iohandler/mem_io_handler.cc, src/metadata/ffmpeg_handler.cc, src/util/mt_inotify.cc, src/util/tools.cc
=> std mem conversions

src/database/sql_database.cc, src/database/sql_database.h, src/database/sql_format.h, test/database/test_sql_generators.cc
Provide an easy to use updateRow method that generates UPDATE statements with a single WHERE filter
More complex filter capabilities planned for a future PR.
=> Update command generator method

src/content/scripting/playlist_parser_script.cc
=> Canonicalize path from playlist file

src/iohandler/curl_io_handler.cc, src/server.cc, src/util/tools.cc, src/util/url.cc, src/util/url.h
=> static_cast conversions

src/content/autoscan_inotify.cc
Not sure if worth. Lambda's a bit big.
=> std::find conversion

src/transcoding/transcode_ext_handler.cc, src/transcoding/transcode_ext_handler.h
split large method and clean up ifdef nesting
Found with CodeQL message. No idea how to solve the FIXMEs
=> Refactor TranscodeExternalHandler

src/metadata/exiv2_handler.cc
=> small fmt::format conversion

src/file_request_handler.cc, src/util/tools.cc, src/web/add.cc, src/web/directories.cc
=> replace some {} with ()

src/content/content_manager.cc, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h
=> Don't erase from empty vector

src/main.cc
=> replace POSIX remove with fs::remove

src/cds_resource.cc, src/cds_resource.h, src/config/config_setup.cc, src/database/sql_database.cc, src/metadata/taglib_handler.cc, src/server.cc, src/transcoding/transcode_ext_handler.cc, src/util/tools.cc, src/util/tools.h, src/web/web_request_handler.cc, test/util/test_tools.cc
Added more unit tests to tool functions, improved some string handling (avoid copying, avoid stringstream for known output size)
=> Tools optimizations

doc/conf.py
=> Replace removed app.add_stylesheet() by app.add_css_file()

src/server.cc, src/server.h
=> replace callbacks with lambdas

src/content/onlineservice/online_service.cc, src/content/scripting/script.cc, src/content/update_manager.cc, src/database/sql_database.cc, src/main.cc, src/metadata/ffmpeg_handler.cc, src/metadata/libexif_handler.cc, src/metadata/metadata_handler.cc, src/upnp_xml.cc, src/util/tools.cc, src/web/auth.cc, src/web/directories.cc, test/core/test_ffmpeg_cache_paths.cc, test/core/test_searchhandler.cc, test/scripting/mock/script_test_fixture.cc, test/scripting/test_external_m3u_playlist.cc, test/scripting/test_external_pls_playlist.cc
=> convert all enum members to upper case

doc/supported-devices.rst, src/config/client_config.cc, src/database/sql_database.cc, src/upnp_cds.cc, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h
=> Block XML Declaration for IRadio based devices

src/file_request_handler.cc
=> Fix detection of content type for thumbnails

src/content/layout/builtin_layout.cc, src/content/layout/builtin_layout.h
Optimization if #1990 was a bit too optimistic
=> Initialize builtin layout properly

src/request_handler.cc, src/util/tools.cc, src/util/tools.h, test/util/test_tools.cc
Added some tests to make sure things mostly work as I would expect.
Fixes: https://github.com/gerbera/gerbera/issues/1993
=> Path to map rework, handle empty values

src/content/scripting/script.cc, src/database/sql_database.cc, src/metadata/matroska_handler.cc, src/upnp_cds.cc, src/util/tools.cc
=> use some type deduction

doc/supported-devices.rst, scripts/js/common.js, scripts/js/playlists.js, src/action_request.cc, src/config/client_config.cc, src/content/scripting/script_names.h, src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, src/metadata/metadata_handler.h, src/upnp_cds.cc, src/upnp_common.h, src/util/upnp_clients.cc, src/util/upnp_quirks.cc, src/util/upnp_quirks.h, test/mock/database_mock.h
search for content folder instead of supplying some id
fixes #2076 
fixes #2064
=> Improve support for Samsung UPnP extension X_GetFeatureList

src/iohandler/curl_io_handler.cc, src/iohandler/io_handler_chainer.cc, src/iohandler/mem_io_handler.cc, src/iohandler/process_io_handler.cc, src/main.cc, src/request_handler.cc, src/util/string_converter.cc, src/web/config_save.cc, test/core/test_searchhandler.cc, test/scripting/mock/script_test_fixture.cc, test/util/test_upnp_clients.cc
=> remove dead assignment

src/upnp_mrreg.h, test/database/sqlite_config_fake.h
=> comment fixes

src/content/scripting/script.cc
Not sure if this is the correct fix (should there be a string here?) but
it makes the import successful.
=> JS: add array check to getArrayProperty

scripts/js/common.js, scripts/js/playlists.js, src/content/layout/builtin_layout.cc
also add missing values for BuildinLayout
this should be the root cause for #2091
=> fix definition of M_CONTENT_CLASS

src/config/config_manager.cc, src/content/content_manager.cc, src/content/update_manager.cc, src/main.cc, src/util/thread_runner.h, src/util/upnp_quirks.h, src/util/url.cc
=> grammar fixes

src/action_request.h, src/cds_objects.h, src/cds_resource.cc, src/cds_resource.h, src/config/client_config.cc, src/config/client_config.h, src/config/config.h, src/config/config_manager.h, src/content/autoscan_inotify.cc, src/content/content_manager.h, src/content/onlineservice/online_service.h, src/database/database.cc, src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, src/server.h, src/upnp_cm.h, src/upnp_mrreg.h, src/upnp_xml.cc, src/upnp_xml.h, src/util/generic_task.h, src/util/tools.cc, src/util/tools.h, test/database/mysql_config_fake.h, test/database/sqlite_config_fake.h, test/mock/config_mock.h, test/mock/database_mock.h
=> remove several unused functions

src/url_request_handler.cc
=> comment out some unused code

src/content/scripting/script.h, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.h
=> add missing defines

src/config/config_setup.cc, src/upnp_xml.cc
=> simplify bool

src/action_request.cc, src/config/config_manager.cc, src/database/database.cc, src/database/mysql/mysql_database.cc, src/device_description_handler.cc, src/iohandler/io_handler.cc, src/metadata/exiv2_handler.cc, src/metadata/ffmpeg_handler.cc, src/transcoding/transcode_dispatcher.cc, test/scripting/mock/script_test_fixture.cc, test/scripting/test_common_script.cc
=> more unneeded headers

src/util/generic_task.h
=> unused enum

src/metadata/taglib_handler.cc
=> don't use else after return

src/metadata/ffmpeg_handler.h
=> fix mismatching declaration

src/content/scripting/js_functions.cc, src/content/scripting/script.cc
Added some structured bindings and fixed wrong index type.
=> several duktake type fixes

src/content/layout/builtin_layout.cc, src/content/onlineservice/task_processor.cc, src/content/scripting/playlist_parser_script.cc, src/database/mysql/mysql_database.cc, src/database/search_handler.cc, src/iohandler/curl_io_handler.cc, src/iohandler/process_io_handler.cc, src/iohandler/process_io_handler.h, src/metadata/libexif_handler.cc, src/metadata/taglib_handler.cc, src/util/jpeg_resolution.cc, src/util/tools.cc, src/util/tools.h, src/util/upnp_headers.cc, src/web/files.cc
Mostly cosmetic. I've tested this locally and found no problems.
=> random sonarlint cleanups

src/util/jpeg_resolution.cc
=> return pair instead of by reference param

src/metadata/taglib_handler.cc, src/metadata/taglib_handler.h
=> convert function to static

src/config/config_setup.h
It prints true or false when given a bool argument.
=> use to_string for bool

src/metadata/exiv2_handler.h
=> Revert "silence exiv2 warnings"

src/config/client_config.cc, src/config/client_config.h, src/config/directory_tweak.cc, src/config/directory_tweak.h, src/config/dynamic_content.cc, src/config/dynamic_content.h, src/content/autoscan_inotify.cc, src/content/autoscan_inotify.h, src/content/autoscan_list.cc, src/content/autoscan_list.h, src/content/scripting/playlist_parser_script.cc, src/content/scripting/script.cc, src/content/scripting/scripting_runtime.h, src/database/mysql/mysql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc, src/util/thread_executor.cc, src/util/thread_runner.h, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/web/session_manager.cc, src/web/session_manager.h
SonarLint reports the latter to be better.
=> replace all lock_guard with scoped_lock

doc/gerbera.1, src/main.cc, test/core/fixtures/mock-help.out
closes #2122
closes #2123 
closes #2126 
Hope I got things right
=> Update man page and help text to reflect the current situation

src/config/client_config.cc, src/config/client_config.h, src/config/directory_tweak.cc, src/config/directory_tweak.h, src/config/dynamic_content.cc, src/config/dynamic_content.h, src/content/autoscan_inotify.cc, src/content/autoscan_inotify.h, src/content/autoscan_list.cc, src/content/autoscan_list.h, src/content/scripting/playlist_parser_script.cc, src/content/scripting/script.cc, src/content/scripting/scripting_runtime.h, src/database/mysql/mysql_database.cc, src/database/sql_database.h, src/database/sqlite3/sqlite_database.cc, src/util/thread_executor.cc, src/util/thread_runner.h, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/web/session_manager.cc, src/web/session_manager.h
=> Revert "replace all lock_guard with scoped_lock"

doc/compile.rst, doc/conf.py, doc/config-clients.rst, doc/config-import.rst, doc/dev-conan.rst, doc/requirements.txt, doc/sections.xsl
Fixes: https://github.com/gerbera/gerbera/issues/2132
=> Docs: sphinx 4.2, pin versions, fix warnings

src/config/config_definition.cc
=> make maps and vectors const

src/cds_objects.h, src/content/content_manager.cc
=> Don't iterate on different copies

src/main.cc
Got lost on the way.
Thanks @druban
=> get logfile from command line

src/cds_objects.cc
=> remove redundant base class init

src/util/tools.cc
=> use braced init list

src/content/scripting/scripting_runtime.cc
=> replace fatalHandler with lambda

doc/compile.rst
Related: https://github.com/gerbera/gerbera/issues/43
=> Mention "gerbera --compile-info" on compilation docs

src/config/config_setup.h, src/content/onlineservice/atrailers_content_handler.h, src/exceptions.h, src/metadata/libexif_handler.h, src/metadata/matroska_handler.h, src/metadata/metacontent_handler.h, src/transcoding/transcode_dispatcher.cc, src/transcoding/transcode_dispatcher.h, src/transcoding/transcode_ext_handler.cc, src/transcoding/transcode_ext_handler.h, src/web/action.cc, src/web/add.cc, src/web/add_object.cc, src/web/clients.cc, src/web/directories.cc, src/web/edit_save.cc, src/web/files.cc, src/web/pages.h, src/web/remove.cc, src/web/tasks.cc, src/web/web_autoscan.cc, src/web/web_request_handler.h
=> replace constructors with using declarations

src/util/tools.h
=> use underlying_type_t

src/config/config_setup.h
=> add another using declaration

src/transcoding/transcode_handler.h
=> remove unused enum

src/content/content_manager.cc, src/content/content_manager.h
=> content manager changes

src/server.cc
SonarLint reports that this is a bad loop. Rework it.
for loops are very flexible in C and C++. Because of that, they can carry
a complexity that can make the code error-prone, difficult to understand,
and hard to maintain.
Many for loops can be written in a way that clearly separates the
iteration process from the content of the iteration. This rule makes sure
that all the code relevant to the iteration is placed in the for-loop
header. The compliant code is then easier to reason about.
A for loop is composed of 4 sub-parts:
 for([initialization]; [condition]; [update])    [body]  
We classify the variables used to control them in three categories:
A loop-counter is a variable modified in the update. It should not be
modified in the body.
A loop-constant is an auxiliary variable declared …
=> rework for loop

src/metadata/ffmpeg_handler.cc
Nothing special is being done here.
=> convert map to simple array

src/transcoding/transcoding.h
=> remove extra semicolon

src/transcoding/transcoding.h
=> remove unused class

src/util/process_executor.cc, src/web/config_load.cc, src/web/directories.cc
=> const auto ref conversion

src/database/mysql/mysql_database.h
=> remove unused friend declaration

src/content/update_manager.cc, src/metadata/metadata_handler.h, src/util/jpeg_resolution.cc
=> remove some unused macros

src/util/timer.cc, src/util/timer.h, src/web/web_request_handler.cc, src/web/web_request_handler.h
=> add const for getter functions

src/config/config_manager.cc, src/config/config_manager.h, src/content/autoscan.cc, src/content/autoscan.h, src/content/autoscan_inotify.h
=> default init some shared pointers

src/util/process_executor.cc
=> remove unused optional header.

src/config/config_manager.cc, src/config/config_manager.h, src/content/content_manager.cc, src/content/content_manager.h, src/iohandler/file_io_handler.cc, src/server.cc, src/server.h, src/util/timer.h, src/web/session_manager.h
=> follow rule of zero with some classes

src/util/mime.cc
const char * is convertable to std::string
=> return function directly

src/transcoding/transcode_ext_handler.cc
=> remove not really used bool

src/config/config_setup.h
=> use std::function

src/cds_objects.h, src/cds_resource.h
=> add explicit

src/device_description_handler.cc
=> small typo

scripts/js/playlists.js, src/content/scripting/script.cc, src/database/sql_database.cc
=> Set refId for playlist container

src/metadata/matroska_handler.cc
=> Free libMatroska memory

src/content/onlineservice/lastfm_scrobbler.cc, src/content/onlineservice/lastfm_scrobbler.h, src/content/onlineservice/task_processor.cc, src/content/onlineservice/task_processor.h, src/content/scripting/import_script.cc, src/content/scripting/import_script.h, src/content/scripting/playlist_parser_script.cc, src/content/scripting/playlist_parser_script.h, src/database/database.cc, src/database/database.h, src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h, src/exceptions.cc, src/exceptions.h
Avoids -Wweak-vtables. Small size reduction.
=> move several methods out of line

src/config/config_definition.cc, src/config/config_setup.h
=> move std::function stuff

src/metadata/ffmpeg_handler.cc
=> find_if conversion

src/url_request_handler.cc, src/url_request_handler.h
=> replace constructor with using

src/main.cc
=> fix wrong case

test/util/test_upnp_headers.cc
=> test_upnp_headers: init changes

src/metadata/exiv2_handler.cc
=> const exiv2 exception

src/config/config_definition.cc, src/exceptions.cc, src/exceptions.h
=> fix variable names to WebKit style

src/config/config_setup.h
=> add parentheses to macros

src/metadata/ffmpeg_handler.cc
=> remove stat include

src/content/update_manager.cc, src/server.cc, src/web/auth.cc
=> remove some chrono includes

src/content/autoscan_inotify.cc, src/content/onlineservice/task_processor.cc, src/content/scripting/js_functions.cc
=> merge some if statements

src/database/sqlite3/sqlite_database.cc
=> fs::path conversion

src/metadata/matroska_handler.cc
=> use dynamic cast for derived classes

src/iohandler/file_io_handler.cc
=> early exit

src/device_description_handler.cc, src/device_description_handler.h, src/server.cc, src/upnp_cds.cc, src/upnp_cds.h, src/upnp_cm.cc, src/upnp_cm.h, src/upnp_mrreg.cc, src/upnp_mrreg.h
=> remove get() calls and match types

src/util/timer.h, src/web/session_manager.cc
=> remove defaulted parameter.

src/upnp_cds.h, src/util/timer.h, src/web/session_manager.cc
=> default initialize some fields in the constructor

CMakeLists.txt, src/content/autoscan_inotify.cc, src/content/scripting/playlist_parser_script.cc, src/content/scripting/script.cc, src/database/mysql/mysql_database.cc, src/database/sqlite3/sqlite_database.cc, src/iohandler/file_io_handler.cc, src/iohandler/file_io_handler.h, src/main.cc, src/metadata/ffmpeg_handler.cc, src/metadata/matroska_handler.cc, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h, src/server.cc, src/util/grb_fs.cc, src/util/grb_fs.h, src/util/tools.cc, src/util/tools.h, test/database/test_database.cc, test/scripting/mock/script_test_fixture.cc, test/scripting/test_common_script.cc, test/util/test_tools.cc
=> Move filesystem function to grb_fs

src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h
=> ffmpeg: const additions

doc/scripting.rst
Resolves: https://github.com/gerbera/gerbera/issues/2181
=> Import script hints

src/util/grb_fs.cc, src/util/tools.cc
Seems the rng stuff was removed at some point.
=> remove random header

src/util/jpeg_resolution.cc
=> use std::byte

src/transcoding/transcode_ext_handler.cc, src/util/grb_fs.cc
=> remove some more headers

src/util/jpeg_resolution.cc, src/util/mt_inotify.cc, src/util/string_converter.cc, src/util/tools.cc, src/util/upnp_headers.cc, src/util/url.cc, src/web/edit_load.cc
=> remove some uninitialized variables

src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h
Closes: https://github.com/gerbera/gerbera/issues/2175
=> MySQL fix warnings with glibc 2.34, pass a real pointer

src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, src/database/sql_database.h, test/core/test_searchhandler.cc
=> Implement sort on metadata

src/server.cc
=> cast to proper type

src/cds_objects.h, src/config/config_manager.cc, src/config/config_setup.cc, src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/content/onlineservice/task_processor.cc, src/content/scripting/import_script.cc, src/content/scripting/js_functions.cc, src/content/scripting/playlist_parser_script.cc
Mostly unused exception variables.
=> various fixes

src/content/content_manager.cc, src/content/content_manager.h
=> Add mutext to lock access to layout

src/util/upnp_clients.cc
CLion reports that the lambda is too big. Slim it down slightly.
=> reduce lambda size slightly

src/metadata/exiv2_handler.cc
=> Free XMP namespaces

src/database/sql_database.cc
ContentManager::addContainer creates additional container / from this
Happens when adding new containers in web ui
=> Remove root from container path

src/content/autoscan_inotify.cc, src/content/autoscan_list.cc, src/content/content_manager.cc
Rework #2150 which broke, e.g. autoscan
=> Handle path comparison correctly

src/metadata/libexif_handler.cc, src/metadata/libexif_handler.h
=> const pointer

src/file_request_handler.cc
=> use std::pair for checkFileAndSubtitle

src/database/search_handler.cc
=> replace insert with emplace

src/content/onlineservice/task_processor.cc, src/content/onlineservice/task_processor.h, src/content/scripting/script.cc, src/content/scripting/script.h, src/iohandler/process_io_handler.cc, src/iohandler/process_io_handler.h, src/metadata/metacontent_handler.cc, src/metadata/metacontent_handler.h
=> add const to various get functions

src/util/process_executor.cc
=> ProcessExecutor: small std::array conversion

src/database/sql_database.cc
=> Add two moves.

src/database/search_handler.cc
=> avoid some shared_ptr copies

src/database/search_handler.cc, src/database/search_handler.h
=> shared to unique_ptr conversions

src/content/scripting/script.cc, src/content/scripting/script.h, src/database/mysql/mysql_database.cc, src/database/sql_database.cc, src/database/sqlite3/sqlite_database.cc, src/server.cc, src/transcoding/transcode_dispatcher.cc, src/transcoding/transcode_dispatcher.h, src/transcoding/transcode_ext_handler.cc, src/transcoding/transcode_ext_handler.h, src/transcoding/transcode_handler.h
=> convert string to fs::path

src/database/sql_database.cc
Avoids bugprone-implicit-widening-of-multiplication-result warning.
=> use auto with cast

doc/supported-devices.rst, src/config/client_config.cc, src/database/database.h, src/database/sql_database.cc, src/upnp_cds.cc, src/util/upnp_clients.cc, src/util/upnp_quirks.h
=> Add flag to hide dynamic content on Samsung devices

src/metadata/matroska_handler.cc
@neheb Can you verify that the memory loss goes down.
=> Free EBML memory

scripts/debian/build-deb.sh
Focal comes with cmake 3.16 only
=> Fix focal build

src/metadata/taglib_handler.cc, src/metadata/taglib_handler.h
=> pointer to reference conversions

src/content/autoscan_inotify.cc
=> use operator< instead of creating temporaries

src/metadata/ffmpeg_handler.cc, src/metadata/libexif_handler.cc, src/upnp_cds.cc, src/upnp_xml.cc
=> simplify some if statements

src/util/upnp_clients.cc, src/util/upnp_clients.h
=> add const to get functions

src/transcoding/transcode_ext_handler.cc
=> avoid some copies

src/file_request_handler.cc, src/iohandler/buffered_io_handler.cc, src/iohandler/curl_io_handler.cc
=> BufferedIOHandler: Fix random exceptions

src/database/search_handler.cc
=> Fix join statement for multiple metadata search

src/server.cc
Based on the comment, it's more appropriate here.
=> use startswith

Dockerfile
Build libupnp with flags `reuseaddr=ON` and `blocking_tcp_connections=OFF`
Docker image size is almost the same.
Resolves #2300 and probably #1847
=> Build libupnp in Dockerfile

src/content/content_manager.cc
=> merge various if statements

src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h
=> mysql: rename variables based on WebKit style

src/content/content_manager.cc, src/content/onlineservice/atrailers_content_handler.cc, src/database/search_handler.cc, src/database/sql_database.cc, src/util/timer.h, src/web/auth.cc
tools has a function for this
confirmed on godbolt the time_ and duration_cast versions have the same assembly.
=> remove some chrono code duplication

src/content/scripting/script.cc, src/util/grb_fs.cc, src/web/items.cc
fixes #2196 
Further improve display of sequence number in web ui.
Includes leftover with file access fixes.
=> Fix playlist numbering

src/content/onlineservice/task_processor.cc, src/content/update_manager.cc, src/database/sqlite3/sqlite_database.cc, src/iohandler/io_handler_buffer_helper.cc, src/util/thread_runner.h, src/util/timer.cc
Also simplified several lambdas.
=> replace C function pointer with std::function

src/transcoding/transcode_ext_handler.cc
=> Fix transcoding regression

src/database/sqlite3/sqlite_database.h
=> get rid of static_pointer_cast

src/transcoding/transcoding.cc, src/transcoding/transcoding.h
=> avoid some shared_ptr copying

src/database/mysql/mysql_database.cc, src/database/sqlite3/sqlite_database.cc
=> rename const variables to WebKit style

src/content/content_manager.cc, src/util/timer.cc, src/util/timer.h
No benefit over vector here. Small size reduction.
=> deque removal

src/file_request_handler.cc
Failed if image was used instead of album art from a media file
=> Fix display of container art

src/iohandler/process_io_handler.cc, src/iohandler/process_io_handler.h, src/transcoding/transcode_ext_handler.cc, src/transcoding/transcode_ext_handler.h
=> unique_ptr conversions

src/content/scripting/script.cc, src/content/scripting/script.h
=> clang-tidy: pass by value

src/util/logger.h
Fixes #2383 
See also https://github.com/fmtlib/fmt/issues/2704 and https://github.com/yuzu-emu/yuzu/commit/b3308830b217cbdd9638b11e8660d079e16b3f01
=> Fix for fmt > 8.0

src/server.cc
https://github.com/gerbera/gerbera/issues/2376
=> Remove trailing slash from URL

.github/workflows/publish-deb.yml, scripts/debian/build-deb.sh
Ubuntu 18.04 not supported by CMake PPA, and 20.04 ARMv7 is broken in the PPA.
=> Build armv7/arm64 deb images

.github/workflows/docker.yml, Dockerfile, README.Docker.md
For now includes ffmpeg, vlc and heic-tools
Adds about about 100MB but saves people having to roll their own.
Fixes: #1498
=> Docker: Add transcoding tag

src/database/database.h
there's nothing special being done here.
=> change class to struct

src/iohandler/curl_io_handler.cc
=> remove pointless void cast

src/file_request_handler.cc, src/file_request_handler.h
=> static function conversion

src/content/layout/builtin_layout.cc, src/content/onlineservice/atrailers_content_handler.cc
=> turn vector to array

src/cds_objects.h, src/content/scripting/script.cc, src/metadata/taglib_handler.cc
detects overflow from taglib
fix #2398
=> Block negative track numbers

doc/compile.rst
https://docs.gerbera.io/en/stable/compile.html#dependencies
=> Fix libary links in compilation docs

src/metadata/ffmpeg_handler.cc
last change left room for improvement
=> Optimize Ffmpeg handler

src/content/content_manager.cc, src/content/layout/builtin_layout.cc, src/content/layout/builtin_layout.h, src/content/layout/js_layout.cc, src/content/layout/js_layout.h, src/content/layout/layout.h, src/content/onlineservice/curl_online_service.cc, src/metadata/ffmpeg_handler.cc, src/metadata/metadata_handler.cc, src/util/upnp_quirks.cc
As a result of the last commit, it is unused.
=> remove mimetype parameter

src/content/content_manager.cc, src/content/onlineservice/curl_online_service.cc, src/content/scripting/script.cc
=> simplify some static_pointer_cast

doc/ui.rst
Information taken from https://github.com/gerbera/gerbera/issues/358
=> Document the special role of "PC Directory"

src/content/autoscan.cc, src/content/autoscan.h, src/content/scripting/script.cc, src/database/sql_database.h, src/web/web_autoscan.cc
It's not clear that it's a good idea.
=> remove string_view quote

web/js/gerbera-items.module.js
Forgot to clean up that function (which broke by fixing the tests)
=> Fix function to change items per page

src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/content/content_manager.h, src/content/onlineservice/task_processor.cc, src/content/onlineservice/task_processor.h, src/content/scripting/playlist_parser_script.cc, src/content/scripting/playlist_parser_script.h, src/database/sqlite3/sqlite_database.cc
=> remove various shared_ptr copies

src/url_request_handler.cc, src/util/url.cc, src/util/url.h
=> remove unique_ptr

src/content/scripting/script.cc, src/database/sql_database.cc, src/util/upnp_clients.cc, src/web/session_manager.cc
Using copy elision results in slightly smaller size.
=> remove some {}.

web/index.html, web/js/gerbera-app.module.js, web/js/gerbera-auth.module.js
Currently it looks like you can do things, when you cant
=> UI: Hide more when not logged in

web/assets/theme/gerbera.css, web/index.html, web/js/jquery.gerbera.items.js
Add margins when collapsed, make stats table prettier
Now looks like this:
and like this when collapsed:
=> UI: Tidy homepage

src/web/directories.cc
=> Also display autoscan badge in filesystem view

src/web/directories.cc, web/assets/theme/gerbera.css, web/js/gerbera-tree.module.js, web/js/jquery.gerbera.items.js, web/js/jquery.gerbera.tree.js
Display small badge if there is a recursive autoscan parent
closes #357
=> Show subdir of recursive autoscan in directory tree

src/database/sql_database.cc, src/util/jpeg_resolution.cc
=> replace for loop with while

web/js/jquery.gerbera.items.js
=> Fix scrolling in item pager

src/content/scripting/playlist_parser_script.cc
=> Fix playlist parser error

src/database/sql_database.cc
=> remove pointless parentheses

src/database/sql_database.cc, src/database/sqlite3/sqlite_database.cc, src/server.cc, src/web/web_autoscan.cc
=> unused parameter for throw

src/cds_objects.cc, src/iohandler/io_handler_buffer_helper.cc, src/web/edit_load.cc
=> bool simplifications

doc/install.rst
=> doc/install.rst: add Buildroot

src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, src/util/tools.cc, test/core/test_searchhandler.cc
=> Fix sorting by composed keys

src/content/scripting/playlist_parser_script.cc, src/content/scripting/playlist_parser_script.h
=> Playlist: Handle end of file properly

src/util/upnp_clients.cc, src/util/upnp_clients.h
=> clang-tidy: use move

src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h, src/util/grb_fs.cc, src/util/grb_fs.h
=> Rework file access

src/util/jpeg_resolution.cc
=> use to_integer

src/database/sql_database.cc
=> Sort containers first

CMakeLists.txt, src/action_request.cc, src/database/sql_database.cc, src/file_request_handler.cc, src/server.cc, src/util/grb_fs.cc, src/util/grb_fs.h, src/util/grb_net.cc, src/util/grb_net.h, src/util/tools.cc, src/util/tools.h, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h, src/web/clients.cc, test/util/test_upnp_clients.cc
Improves readability and avoids pointer handling.
=> Refactor handling of network addresses

gerbera-web/mock-api/auth/config.json, gerbera-web/test/client/fixtures/config.json, gerbera-web/test/client/fixtures/converted-config.json, gerbera-web/test/client/gerbera.app.spec.js, gerbera-web/test/e2e/menu.spec.js, web/index.html, web/js/gerbera-menu.module.js
Fixes #2522
Thanks to @BobManMasher for the report
=> Restore friendly name in UI

.github/codeql/codeql-config.yml
=> Try to fix paths-ignore

src/config/config_options.h, src/config/config_setup.h
=> pass shared_ptr by value

src/content/onlineservice/task_processor.cc, src/content/onlineservice/task_processor.h, src/upnp_xml.cc, src/upnp_xml.h, src/web/session_manager.cc, src/web/session_manager.h
=> clang-tidy: member function const

doc/supported-devices.rst, src/cds_objects.cc, src/config/client_config.cc, src/upnp_cm.cc, src/upnp_mrreg.cc, src/upnp_xml.cc, src/upnp_xml.h, src/util/upnp_clients.cc, src/util/upnp_clients.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h, test/core/test_upnp_xml.cc, test/mock/config_mock.h
second part of solution for #2531
may even help with #2017
=> Add Quirk to block filename in item uri

src/web/add_object.cc, src/web/pages.h
No need for a function parameter.
=> move make_shared into function

test/config/fixtures/mock-config-minimal.xml
=> Minimal: fix test

src/content/autoscan_inotify.cc
=> Autoscan: fix out of range issue

src/content/content_manager.cc, src/content/onlineservice/task_processor.cc
=> add missing moves

src/metadata/metadata_handler.cc
=> simplify bool expression

src/cds_resource.h
=> fix declaration

src/content/content_manager.cc, src/content/onlineservice/online_service.h, src/util/timer.cc, src/util/timer.h
=> manual move conversions

src/action_request.h, src/database/sql_database.h, src/util/grb_fs.h
=> clang-tidy: add special member functions

src/config/config_options.cc, src/config/config_options.h, src/config/config_setup.h, src/config/directory_tweak.h, src/config/dynamic_content.h, src/content/layout/builtin_layout.cc, src/content/layout/builtin_layout.h, src/content/layout/layout.h
Avoids CLion warnings about using string_view.
=> pass std::string by value

src/config/client_config.cc, src/content/onlineservice/atrailers_content_handler.cc, src/content/onlineservice/online_service_helper.cc, src/content/scripting/import_script.cc, src/content/scripting/script.cc, src/content/scripting/script_names.h, src/database/mysql/mysql_database.cc, src/database/sqlite3/sqlite_database.cc, src/metadata/ffmpeg_handler.h, src/metadata/libexif_handler.cc, src/metadata/metacontent_handler.cc, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h, src/upnp_xml.cc, src/util/upnp_clients.cc, src/util/upnp_quirks.cc, src/web/directories.cc, src/web/edit_load.cc
=> remove unused includes

src/metadata/libexif_handler.cc, src/util/jpeg_resolution.cc, src/util/tools.h
=> remove IOHandler unique_ptrs

src/server.cc, src/server.h, src/upnp_cds.cc, src/upnp_cds.h, src/upnp_cm.cc, src/upnp_cm.h, src/upnp_mrreg.cc, src/upnp_mrreg.h
=> manual unique_ptr removals

src/iohandler/buffered_io_handler.cc, src/iohandler/file_io_handler.cc, src/iohandler/file_io_handler.h, src/iohandler/io_handler.cc, src/iohandler/io_handler.h, src/iohandler/io_handler_buffer_helper.cc, src/iohandler/io_handler_buffer_helper.h, src/iohandler/io_handler_chainer.cc, src/iohandler/io_handler_chainer.h, src/iohandler/mem_io_handler.cc, src/iohandler/mem_io_handler.h, src/iohandler/process_io_handler.cc, src/iohandler/process_io_handler.h, src/server.cc, src/util/jpeg_resolution.cc
=> change read/write functions to use std::byte

.github/workflows/ci-js.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/macos.yml, .github/workflows/minimal.yml, src/cds_resource.cc, src/content/autoscan_list.cc, src/content/content_manager.cc, src/content/content_manager.h
=> ContentManager: Single autoscan list

src/transcoding/transcode_ext_handler.h, src/transcoding/transcode_handler.h
=> remove unused upnp header

src/util/jpeg_resolution.cc
Fix for error: 'CHAR_BIT' was not declared in this scope
=> Fix compilation of jpeg_resolution.cc

src/content/autoscan.cc, src/content/content_manager.cc
Otherwise timed autoscan and import does not detect changes.
closes #2602
=> Don't store timestamps in future

src/web/config_load.cc
=> use empty()

src/content/content_manager.cc, src/database/sql_database.cc, src/util/tools.h
=> rename to_seconds to toSeconds

src/config/setup/config_setup_transcoding.cc, src/transcoding/transcode_ext_handler.cc, src/transcoding/transcoding.cc, src/transcoding/transcoding.h, src/upnp_xml.cc, src/web/config_load.cc
=> webkit style for transcoding

src/cds_resource.cc, src/metadata/ffmpeg_handler.cc
Increase HD cutooff to 1920
Limit sample rate tweaks to DSD only - other formats like AAC also set
bitsPerSample and end up with incorrect values set
=> Minor fixes

src/metadata/resolution.cc, src/upnp_xml.cc, src/util/process_executor.cc, src/util/tools.cc, test/content/test_resolution.cc
=> This and that

gerbera-web/test/client/gerbera.dirtweak.spec.js, gerbera-web/test/client/gerbera.tree.spec.js, gerbera-web/test/client/jquery.gerbera.autoscan.spec.js, gerbera-web/test/client/jquery.gerbera.dirtweak.spec.js, web/js/gerbera-app.module.js, web/js/gerbera-auth.module.js, web/js/gerbera-config.module.js, web/js/gerbera-trail.module.js, web/js/gerbera-tree.module.js, web/js/gerbera-updates.module.js, web/js/jquery.gerbera.editor.js
this may solve the CI issues. Sometimes the error message is valid
=> Handle Promise rejection

src/config/dynamic_content.h, src/content/autoscan.h, src/content/autoscan_inotify.cc, src/content/content_manager.cc, src/database/search_handler.cc, src/metadata/resolution.h, src/server.cc, src/subscription_request.cc, src/subscription_request.h
Mostly nullptr deref.
Found with Coverity.
=> Coverity fixes

src/config/config_setup.h, src/config/setup/config_setup_bool.cc, src/config/setup/config_setup_client.cc, src/upnp_xml.cc, src/util/tools.cc, src/util/tools.h
=> sonarlint fixes

.github/workflows/minimal.yml
=> actions: use alpine 3.16 container

src/metadata/metacontent_handler.cc, src/server.cc, src/util/xml_to_json.cc, src/util/xml_to_json.h, src/web/auth.cc, src/web/clients.cc, src/web/config_load.cc, src/web/containers.cc, src/web/directories.cc, src/web/edit_load.cc, src/web/files.cc, src/web/items.cc, src/web/tasks.cc, src/web/web_autoscan.cc, src/web/web_request_handler.cc, src/web/web_request_handler.h
May be a little slower than the stream version but it is readable.
=> Simplify Xml2Json

src/content/content_manager.cc, src/content/content_manager.h, src/upnp_cds.cc, src/upnp_cds.h, src/upnp_cm.cc, src/upnp_cm.h, src/upnp_mrreg.cc, src/upnp_mrreg.h
=> const member functions

src/cds_resource.cc, src/config/setup/config_setup_transcoding.cc, src/metadata/libexif_handler.cc, src/metadata/resolution.cc, src/util/jpeg_resolution.cc, src/util/jpeg_resolution.h
=> Improve error handling for Resolution

src/content/content_manager.cc, src/content/content_manager.h, src/content/scripting/playlist_parser_script.cc, src/content/scripting/script.cc, src/content/scripting/script.h, src/iohandler/curl_io_handler.cc, src/iohandler/curl_io_handler.h, src/iohandler/io_handler_buffer_helper.cc, src/iohandler/io_handler_chainer.cc
=> more sonarlint

src/content/content_manager.cc, src/content/content_manager.h
Ensure that tasks are cleaned up after each object remove
=> Cleanup tasks on removeObject

src/content/content_manager.cc, src/content/content_manager.h, src/upnp_xml.cc, src/web/add_object.cc, web/js/jquery.gerbera.editor.js
=> Transcoding for external items

src/metadata/exiv2_handler.cc
=> fix compilation with latest exiv2 master

gerbera-web/package-lock.json, gerbera-web/package.json
closes https://github.com/gerbera/gerbera/security/dependabot/25
=> Fix npm vulnerabilities

src/iohandler/process_io_handler.cc, src/transcoding/transcode_ext_handler.cc, src/url_request_handler.cc
=> Fix: Remove duplicate open breaking url transcoding

src/database/sql_format.h
Fixes #2681
Tested to build fine with both fmt 9.0 and 8.1.1.
=> Fix build with fmt 9.0

doc/config-clients.rst, src/util/grb_net.cc, test/util/test_upnp_clients.cc
As inspired by @GinTonic99 in #2700
=> Add support for ip subnets in client config

scripts/versions.sh, src/common.h, src/config/config_definition.cc, src/config/config_manager.cc, src/content/content_manager.cc, src/content/content_manager.h, src/content/scripting/script.cc, src/database/sql_database.cc, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h, test/core/test_searchhandler.cc, test/scripting/mock/script_test_fixture.cc
=> Fix static init

src/util/upnp_quirks.cc
Improve and add debugging messages
Also remove restriction to `UPNP_CLASS_VIDEO_ITEM` in `addCaptionInfo`
=> Saveguard Samsung Quirks

CMakeLists.txt, scripts/systemd/gerbera.service.cmake
=> Systemd: Add wants entry

ReleaseNotes.md, doc/gerbera.1, doc/run.rst, scripts/js/common.js, src/content/content_manager.cc, src/content/content_manager.h, src/content/layout/builtin_layout.cc, src/database/sqlite3/sqlite_database.cc, src/main.cc, src/server.cc, src/server.h, src/util/tools.cc, test/core/fixtures/mock-help.out
Layout: Fix handling of dates with full time - cuts off time details after "T" for containers with dates.
=> Import: fix layout and performance issues

src/content/autoscan.cc, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
=> Fix setting autoscan from Web UI

Dockerfile, Dockerfile.debug, README.md, scripts/install-duktape.sh, scripts/install-ebml.sh, scripts/install-ffmpegthumbnailer.sh, scripts/install-fmt.sh, scripts/install-googletest.sh, scripts/install-matroska.sh, scripts/install-pugixml.sh, scripts/install-pupnp.sh, scripts/install-spdlog.sh, scripts/install-taglib.sh, scripts/install-wavpack.sh, scripts/versions.sh
Increase versions for several packages
=> Docker: Improve debugging build

Dockerfile.debug, ReleaseNotes.md, doc/run.rst, src/action_request.cc, src/action_request.h, src/file_request_handler.cc, src/server.cc, src/server.h, src/upnp_cds.cc, src/util/upnp_clients.h, src/util/upnp_quirks.cc, src/util/upnp_quirks.h, web/cds.xml
References from shared_ptr may bypass destruction and usage count
=> Quirks: Avoid passing references

README.md, doc/compile.rst, scripts/versions.sh
Taglib, spdlog and pugixml have new versions
=> libraries: add latest

gerbera-web/package-lock.json
=> Update npm packages

CMakeLists.txt, src/cds_resource.cc, src/cds_resource.h, src/config/config_setup.h, src/content/autoscan.cc, src/database/sql_database.cc, src/metadata/metadata_handler.h, src/metadata/resolution.cc, src/server.cc, src/upnp_xml.cc, src/util/enum_iterator.h, src/util/grb_net.cc, src/util/grb_net.h, src/util/jpeg_resolution.cc, src/util/logger.cc, src/util/tools.cc, src/util/tools.h, src/util/upnp_clients.h, src/util/url_utils.cc, src/util/url_utils.h, src/web/web_request_handler.cc, test/util/test_tools.cc
Reduce amount of function in tools.
=> Clarify integer types handling

src/action_request.cc, src/upnp_cds.cc, src/upnp_cm.cc, src/upnp_mrreg.cc, web/cds.xml
=> Fix Windows Explorer browsing

src/file_request_handler.cc, src/metadata/exiv2_handler.cc, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/metadata/ffmpeg_thumbnailer_handler.cc, src/metadata/ffmpeg_thumbnailer_handler.h, src/metadata/libexif_handler.cc, src/metadata/libexif_handler.h, src/metadata/matroska_handler.cc, src/metadata/matroska_handler.h, src/metadata/metacontent_handler.cc, src/metadata/metacontent_handler.h, src/metadata/metadata_handler.h, src/metadata/taglib_handler.cc, src/metadata/taglib_handler.h, src/metadata/wavpack_handler.cc, src/metadata/wavpack_handler.h
Also avoid opening Null resource
See #2763
=> MetadataHandler: Use resource instead of id

.gitattributes, src/server.cc
=> Server: Don't call handler if null

test/config/fixtures/mock-config-minimal.xml
=> Minimal: fix test fixture

README.Docker.md
To have a fully functional docker-compose.yml example for gerbera within docker-copose - I have expanded/added a volume section part to the docker-compose part within the file README.Docker.md
=> Update README.Docker.md -Add docker volume section

Dockerfile, Dockerfile.debug
=> Docker: Add JPEG libs

src/web/add.cc
when adding item from UI
closes #2806
=> Set defaults for autoscan settings

src/file_request_handler.cc
=> Fix handling transcoding requests

src/content/layout/builtin_layout.cc
Year container was not created for builtin layout
closes #2843
=> Add audio to year container

CMakeLists.txt, README.md, ReleaseNotes.md, doc/_static/css/custom.css, doc/compile.rst, doc/config-server.rst, doc/config-transcode.rst, doc/dev-configuration.rst, doc/install.rst, scripts/install-googletest.sh, scripts/install-libexiv2.sh, scripts/versions.sh
Includes changes of https://github.com/gerbera/gerbera/issues/1591#issuecomment-1634059455
=> Update versions of exiv2, fmt, spdlog, googletest and taglib

src/database/sql_database.cc
=> DB rework playstatus save

CMakeLists.txt, src/config/config_definition.cc, src/config/config_option_enum.h, src/config/config_options.h, src/config/config_setup.h, src/config/setup/config_setup_bool.cc, src/config/setup/config_setup_enum.h, src/config/setup/config_setup_int.cc, src/config/setup/config_setup_string.cc, src/content/import_service.cc, src/database/sqlite3/sqlite_config.cc, src/database/sqlite3/sqlite_config.h, src/util/logger.cc, src/util/logger.h, src/web/config_load.cc, web/gerbera-config-expert.json, web/gerbera-config-minimal.json, web/gerbera-config-standard.json
Adds missing Box-Layout
Fixes missing script-option arguments
Extract SqliteConfig parsing functions
=> Config WebUI: Catch up with all config changes

ChangeLog.md, README.md, ReleaseNotes.md, scripts/versions.sh, src/content/scripting/script_names.h, src/database/sql_database.cc, src/upnp_common.h, src/web/containers.cc, src/web/items.cc
Reported here https://github.com/gerbera/gerbera/discussions/2867#discussioncomment-6866596
=> WebUI: Database View - don't allow deleting dynamic containers

src/content/content_manager.cc, src/content/import_service.cc, src/content/import_service.h, src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, test/mock/database_mock.h
Adds the missing cleanup of physical items in PC directory.
As discussed in https://github.com/gerbera/gerbera/discussions/2864?notification_referrer_id=NT_kwDOAWjxhLM3NDkxMDMwOTE2OjIzNjU0Nzg4#discussioncomment-7242284
=> Clean up physical entries in subdirectories

.github/workflows/ci.yml, src/upnp_cds.cc
=> Samsung: Handle browse for content class correctly

doc/compile.rst
.. otherwise the cmake will warn about that.
=> Doc: Compile libupnp --disable-blocking-tcp-connections

doc/config-transcode.rst, src/upnp_xml.cc
=> Transcode: Wildcards for mime type filter

doc/compile.rst
Resolves: https://github.com/gerbera/gerbera/issues/2903
=> Document dependency installation on Debian 12

src/content/scripting/script.cc
Resolves: https://github.com/gerbera/gerbera/issues/2913
=> Scripting: Log stacktrace on errors

src/content/scripting/script.cc
Sorry for the noise.
Related to #2913 and #2914.
=> Scripting: Remove debugging leftover

doc/compile.rst, doc/config-import.rst, doc/config-overview.rst, doc/config-server.rst, doc/config-transcode.rst, doc/install.rst, doc/scripting.rst, doc/supported-types.rst, doc/troubleshooting.rst, scripts/js/audio.js, scripts/js/common.js, scripts/js/import.js, src/config/setup/config_setup_path.cc, src/content/import_service.cc, src/web/config_load.cc, test/scripting/mock/duk_helper.cc, test/scripting/mock/script_test_fixture.cc, test/scripting/test_import_script.cc, web/assets/theme/gerbera.css, web/js/jquery.gerbera.items.js
#2917
#2919
also found some leftovers from previous commits :-(
=> Fix import and documentation links

src/config/setup/config_setup_path.cc
=> Fix for empty path

ChangeLog.md, README.md, ReleaseNotes.md, scripts/versions.sh, src/cds/cds_objects.h, src/content/autoscan.cc, src/content/autoscan.h, src/content/cm_task.cc, src/content/content_manager.cc, src/content/import_service.cc, src/content/import_service.h, src/content/onlineservice/online_service.h, src/upnp_xml.cc, src/web/pages.h, src/web/session_manager.h
This is hopefully the last chunk of the grb-mode!
Fixes a major issue with non-zero time values
=> Import: Fix LastModified for grb-mode

ChangeLog.md, doc/config-import.rst, scripts/js/audio.js, scripts/js/common.js, src/config/setup/config_setup_path.cc, src/content/content_manager.cc, src/content/content_manager.h, src/content/import_service.cc, src/content/import_service.h, src/content/layout/builtin_layout.cc, src/content/scripting/js_functions.cc, src/util/grb_fs.cc, src/util/grb_fs.h, test/scripting/mock/script_test_fixture.cc
=> Import: Improve handling of thumbnails in mt-mode

doc/config-import.rst
Part of: https://github.com/gerbera/gerbera/issues/2917
=> Fix "virtual-directories" heading level in documentation

ChangeLog.md, scripts/js/audio.js, src/content/import_service.cc, src/content/scripting/script.cc
=> Import: Icon handling and other leftovers

src/content/content_manager.cc
=> Avoid crash when parent was not created yet.

src/content/import_service.cc
=> Import: Safely handle second scan - 2

.github/workflows/publish-deb.yml, CMakeLists.txt, src/content/content_manager.cc, src/content/content_manager.h, src/content/import_service.cc, src/content/import_service.h, src/content/scripting/metafile_parser_script.cc, src/content/scripting/metafile_parser_script.h, src/content/scripting/parser_script.cc, src/content/scripting/parser_script.h, src/content/scripting/playlist_parser_script.cc, src/util/mt_inotify.cc
=> Refactor parser files

ChangeLog.md, ReleaseNotes.md, src/content/content_manager.cc, src/server.cc, src/util/grb_fs.cc, src/util/grb_fs.h, test/util/test_tools.cc
Finally this should close #2976
=> Fix findAutoscanDirectory

scripts/js/common.js
This PR enhances the default javascript files to check the following configuration file options (to enable disable containers in layout)
* *Audio/allAudio* enabled
* *Audio/allTracks* enabled
=> Enhances default javascript files to check config file options

ChangeLog.md, doc/do_sphinx.sh, doc/scripting.rst, scripts/js/audio.js, scripts/js/common.js, scripts/js/playlists.js, src/config/config.h, src/config/config_definition.cc, src/config/result/box_layout.cc, src/config/result/box_layout.h, src/content/layout/builtin_layout.cc, src/content/layout/builtin_layout.h, src/content/scripting/script.cc, src/content/scripting/script_names.h, test/scripting/mock/script_test_fixture.cc
Remove most of the string constants from scripts
=> Provide BoxKeys also for scripts

gerbera-web/test/client/jquery.gerbera.items.spec.js, web/assets/theme/gerbera.css, web/js/gerbera-app.module.js, web/js/gerbera-items.module.js, web/js/jquery.gerbera.items.js
As I am using gerbera to organize all my digital images a single page view for the images comes very handy.
=> WebUI: Add Item View

src/database/mysql/mysql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
Race condition may lead to exceptions.
=> Sqlite: Harden delete

ChangeLog.md, README.md, ReleaseNotes.md, src/content/layout/builtin_layout.cc
=> Builtin layout: fix crash

Dockerfile, Dockerfile.debug, conanfile.py, scripts/versions.sh
finally got googletest to download and build correctly
=> Docker: update alpine version

doc/install.rst
Note that there wont be anything populated in 'stable' until we push the next tagged release
=> Docs: Update Ubuntu/Debian repo instructions

doc/install.rst
Gerbera is the repos now :tada:
=> docs: Update Arch Linux installs

src/config/config_definition.cc, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.h, src/metadata/ffmpeg_thumbnailer_handler.h, src/metadata/metadata_service.h
=> Build: Allow build of ffmpegthumbnailer without ffmpeg

src/metadata/ffmpeg_handler.cc
Integrate FFMpeg messages in gerbera log instead of hiding them from the user.
Must be provided as singleton because avlib does not support multiple loggers.
=> FFMpeg: add custom logger

doc/config-server.rst, src/device_description_handler.cc, src/upnp_desc_handler.cc, src/util/logger.cc, src/util/logger.h
=> Logging: Separate description requests

config/config2.xsd, doc/config-import.rst, doc/config-server.rst
Maybe the CI jobs should run xmllint to make sure everything is valid.
=> config2.xsd fixes

config/config2.xsd
=> Add sample-frequency to config2.xsd

.github/workflows/publish-deb.yml, scripts/debian/build-deb.sh
Just broke by an update to deb-s3
Also build some debian on PR, to see issues earlier
=> Build: Use Ruby2.6 for bionic

scripts/debian/build-deb.sh
=> Build: Upload for focal

scripts/debian/build-deb.sh, scripts/debian/include-Debian.sh, scripts/debian/include-Raspbian.sh, scripts/debian/include-bionic.sh, scripts/debian/include-buster.sh, scripts/debian/include-focal.sh, scripts/debian/include-hirsute.sh, scripts/debian/include-impish.sh, scripts/debian/include-jammy.sh
Don't want to bloat functions with legacy stuff
=> Build: split debian modules

scripts/debian/include-focal.sh, src/device_description_handler.cc, src/ui_handler.cc, src/upnp_desc_handler.cc, src/upnp_desc_handler.h
=> Fix creation of mr_reg.xml

CMakeLists.txt, src/config/grb_runtime.cc, src/config/grb_runtime.h, src/content/cm_task.cc, src/content/content_manager.cc, src/content/content_manager.h, src/content/import_service.cc, src/content/inotify/autoscan_inotify.cc, src/content/inotify/inotify_handler.cc, src/content/inotify/mt_inotify.cc, src/content/layout/builtin_layout.cc, src/content/onlineservice/online_service.cc, src/content/onlineservice/task_processor.cc, src/content/scripting/playlist_parser_script.cc, src/main.cc, src/server.cc, src/server.h, src/util/generic_task.cc, src/util/generic_task.h, src/web/add.cc
This fixes several issues:
- Pidfile is always removed on exit now
- Entries from config file are correctly overwritten by command line arguments on restart
- SIGHUP seems to work as well
=> Extract command line argument handling to Runtime class

scripts/debian/build-deb.sh, src/config/grb_runtime.cc
=> Startup: Always check dirs

src/util/logger.cc
=> Fix logger.cc without DEBUG

src/database/search_handler.cc, src/database/sql_database.cc
Number columns should use number statement
Request to count number of entries
=> Fix database calls for browsing dynamic containers

src/metadata/ffmpeg_handler.cc, src/web/edit_load.cc
encode option values for UI
closes #3143
=> FFMpeg: Reduce logger noise

ChangeLog.md, README.Docker.md, doc/install.rst, src/upnp/compat.h
=> Improve docker instructions

.github/workflows/publish-deb.yml, ChangeLog.md, src/content/scripting/js_functions.cc, src/content/scripting/playlist_parser_script.cc, src/content/scripting/script.cc, src/content/scripting/script.h, src/metadata/ffmpeg_thumbnailer_handler.cc, src/metadata/ffmpeg_thumbnailer_handler.h, test/core/test_ffmpeg_cache_paths.cc
=> Warn about empty script result

ChangeLog.md, ReleaseNotes.md, src/cds/cds_resource.cc, src/cds/cds_resource.h, src/server.cc, src/upnp/upnp_common.h, src/upnp/xml_builder.cc, test/core/test_upnp_xml.cc
Add Image and thumbnail profiles support for PNG image
=> Improve handling of thumbnail profiles

doc/compile.rst
Related: https://github.com/gerbera/gerbera/discussions/3182
=> Mention .m4a in compilation options

ChangeLog.md, ReleaseNotes.md, doc/config-import.rst, src/cds/cds_enums.h, src/cds/cds_objects.cc, src/cds/cds_objects.h, src/config/result/autoscan.cc, src/config/result/autoscan.h, src/content/import_service.cc, src/content/import_service.h, src/content/layout/layout.cc, src/content/scripting/import_script.cc, src/metadata/metadata_service.cc, src/upnp/quirks.cc, src/web/items.cc
(PC Directory) depending on the majority of children
Only available in grb-mode
=> Upnp Classes for containers in physical tree

ChangeLog.md, ReleaseNotes.md, doc/config-import.rst, src/content/autoscan_setting.h, src/content/content_manager.cc, src/content/import_service.cc, src/content/import_service.h, src/content/inotify/autoscan_inotify.cc, src/content/inotify/inotify_handler.cc, src/content/inotify/inotify_handler.h, src/database/database.h, src/database/sql_database.cc, src/web/config_load.cc
=> Import: Fix renaming of file or folder

ChangeLog.md, src/content/inotify/inotify_handler.cc
=> Inotify: Fix deleting files

ChangeLog.md, README.md, ReleaseNotes.md, doc/troubleshooting.rst, src/config/config_definition.cc, src/config/config_manager.cc, src/config/config_setup.cc, src/config/config_setup.h, src/database/sql_database.h, src/database/sqlite3/sqlite_database.h, test/config/test_configmanager.cc
=> Config: Make UDN mandatory

src/upnp/compat.h
=> Fix NPUPnP version

ChangeLog.md, ReleaseNotes.md, src/database/search_handler.cc, src/database/search_handler.h, src/database/sql_database.cc, src/upnp/cont_dir_service.cc, src/util/grb_time.cc, src/util/grb_time.h, test/core/test_searchhandler.cc
=> UPnP Search: Support integer and date comparison

ChangeLog.md, src/database/database.h, src/database/sql_database.cc, src/web/items.cc
=> Restrict dynamic folders to browse flags

ChangeLog.md, ReleaseNotes.md, src/config/config_generator.cc, src/config/config_manager.cc, src/config/grb_runtime.cc, src/content/content_manager.cc, test/core/test_server.cc
some thumbnailer handling was still linked with `HAVE_FFMPEG`
Closes #3230
=> Fix build without ffmpeg

ChangeLog.md, ReleaseNotes.md, src/metadata/ffmpeg_thumbnailer_handler.cc, test/mock/config_mock.h
=> Fix access to cache option if thumbnailer disabled

ChangeLog.md, README.md, ReleaseNotes.md, config/config2.xsd, doc/config-server.rst, gerbera-web/test/e2e/items.spec.js, gerbera-web/test/e2e/page/home.page.js, src/config/config_definition.cc, src/config/config_val.h, src/server.cc, src/upnp/compat.cc, src/upnp/compat.h
=> Increase size of pupnp threadpool

ChangeLog.md, ReleaseNotes.md, gerbera-web/test/client/gerbera.tree.spec.js, src/config/config_definition.cc, src/database/search_handler.h, src/metadata/metadata_enums.cc, src/upnp/upnp_common.h, src/upnp/xml_builder.cc, src/upnp/xml_builder.h, src/web/items.cc, web/assets/gerbera-config-expert.json, web/index.html, web/js/gerbera-menu.module.js
=> Web UI: Fix detail display

src/config/grb_runtime.cc
=> Fix Handling command line options

gerbera-web/test/client/gerbera.items.spec.js, src/content/import_service.cc, src/database/sql_database.cc, src/request_handler/file_request_handler.cc, src/upnp/compat.h
=> Handle broken ContainerImage

.github/workflows/release-drafter.yml
Github App seems to be dead
It was deperated for 5 years: https://github.com/release-drafter/release-drafter/issues/335
=> Add workflow for Release Drafter

CMakeLists.txt, ChangeLog.md, ReleaseNotes.md, src/config/grb_compile_info.cc, src/config/grb_runtime.cc, test/core/test_server.cc
Show library versions where available
=> Improve compile info contents

ChangeLog.md, src/database/mysql/mysql_database.cc, src/database/mysql/mysql_database.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
mysql_server_init is long time deprecated
=> Update and refactor MySQL code

ChangeLog.md, src/config/setup/config_setup_enum.h, src/main.cc
=> Fix parsing enum config values

ChangeLog.md, src/upnp/xml_builder.cc
=> Fix SIMPLE_DATE

ChangeLog.md, src/config/setup/config_setup_int.cc
=> Handle int parse error in config

.github/workflows/xml.yml, ChangeLog.md, config/config2.xsd, doc/dev-configuration.rst, test/config/fixtures/full-example-for-xsd.xml
Ran the check against my private config and added some of the settings to a new example.
=> Enhance xsd

src/content/import_service.cc, src/content/import_service.h
=> Fix Artist Image in Virtual Layout

src/cds/cds_objects.h, src/content/import_service.cc
Close #3350 
Probably should have a test for this...
=> Remap metadata fields when parsing virtual-directories keys

ChangeLog.md, ReleaseNotes.md, doc/scripting.rst, scripts/js/audio.js, scripts/js/common.js, scripts/js/import.js, src/content/layout/builtin_layout.cc, test/scripting/CMakeLists.txt, test/scripting/mock/common_script_mock.h, test/scripting/mock/script_test_fixture.cc, test/scripting/mock/script_test_fixture.h, test/scripting/test_import_initials_script.cc
=> Set more metadata in builtin layout

ChangeLog.md, src/content/import_service.cc, test/config/fixtures/full-example-for-xsd.xml, test/core/CMakeLists.txt, test/core/test_upnp_map.cc, test/scripting/test_import_initials_script.cc
=> Fix UpnpMap logic

src/cds/cds_container.h, src/cds/cds_enums.h, src/database/sql_database.cc, src/util/grb_fs.cc, src/util/grb_fs.h, src/web/containers.cc, src/web/directories.cc, src/web/items.cc, src/web/web_request_handler.cc, src/web/web_request_handler.h, test/util/test_tools.cc
=> Build correct Autoscan Type

ChangeLog.md, src/content/content_manager.cc
=> Fix management auf autoscans in list

ChangeLog.md, gerbera-web/test/client/gerbera.items.spec.js, gerbera-web/test/client/jquery.gerbera.editor.spec.js, src/cds/cds_enums.cc, src/cds/cds_enums.h, src/cds/cds_objects.h, src/cds/cds_resource.cc, src/cds/cds_resource.h, src/content/content.h, src/content/content_manager.cc, src/content/content_manager.h, src/upnp/xml_builder.cc, src/web/add_object.cc, src/web/edit_save.cc, src/web/web_request_handler.cc, src/web/web_request_handler.h, web/assets/theme/gerbera.css, web/js/gerbera-items.module.js, web/js/jquery.gerbera.editor.js
=> Support Resources for External Items

ChangeLog.md, ReleaseNotes.md, doc/ui.rst, src/web/directories.cc, src/web/pages.h, src/web/web_autoscan.cc, web/js/gerbera-autoscan.module.js, web/js/gerbera-trail.module.js, web/js/gerbera-tree.module.js, web/js/gerbera-tweak.module.js, web/js/jquery.gerbera.trail.js, web/js/jquery.gerbera.tree.js, web/js/jquery.gerbera.tweak.js
also fixes missing EditAutoscan action
=> Add Run Scan action in Web UI

ChangeLog.md, gerbera-web/test/client/fixtures/dirtweak-item-new.json, gerbera-web/test/client/fixtures/dirtweak-submit.json, web/js/gerbera-config.module.js, web/js/jquery.gerbera.tree.js, web/js/jquery.gerbera.tweak.js
=> Web UI: properly encode arguments

ChangeLog.md, src/iohandler/mem_io_handler.cc, src/server.cc, src/util/logger.cc, src/util/logger.h, src/web/action.cc, src/web/add.cc, src/web/add_object.cc, src/web/auth.cc, src/web/clients.cc, src/web/config_load.cc, src/web/config_save.cc, src/web/containers.cc, src/web/directories.cc, src/web/edit_load.cc, src/web/edit_save.cc, src/web/files.cc, src/web/items.cc, src/web/page_request.cc, src/web/page_request.h, src/web/pages.h, src/web/remove.cc, src/web/tasks.cc, src/web/web_autoscan.cc, src/web/web_request_handler.cc, src/web/web_update.cc
=> Fix shutdown issue

ChangeLog.md, scripts/js/audio.js, src/database/database.h, src/database/sql_database.cc, src/database/sql_database.h, src/upnp/cont_dir_service.cc, src/upnp/quirks.cc, src/upnp/quirks.h, test/core/test_searchhandler.cc, test/mock/database_mock.h
Got hold of a really old one and captured some logs
=> Tweak for old Samsung TV

ChangeLog.md, ReleaseNotes.md, src/config/config_definition.cc, src/config/config_generator.cc, src/config/grb_compile_info.cc, src/metadata/libexif_handler.cc, test/config/fixtures/full-example-for-xsd.xml, test/config/fixtures/mock-config-all-os.xml, test/config/fixtures/mock-config-all.xml, test/config/fixtures/mock-config-minimal.xml, test/config/fixtures/mock-database-mysql.xml, test/config/fixtures/mock-database-sqlite.xml, test/config/fixtures/mock-example-all-os.xml, test/config/fixtures/mock-example-all.xml, test/config/fixtures/mock-example-exiv2-all-os.xml, test/config/fixtures/mock-example-exiv2-all.xml, test/config/fixtures/mock-example-minimal.xml, test/config/fixtures/mock-server-all.xml
makes sqlite enabled by default
=> Remove legacy compile option SQLITE_BACKUP_ENABLED

ChangeLog.md, Dockerfile, Dockerfile.debug, Dockerfile.opensuse
=> Add missing jsoncpp to `Dockerfile`s

ChangeLog.md, src/metadata/ffmpeg_handler.cc, src/metadata/metadata_handler.cc, src/metadata/metadata_handler.h, src/metadata/taglib_handler.cc, src/request_handler/file_request_handler.cc
Required if there are multiple subtitles
=> Get correct ffmpeg subtitle stream

ChangeLog.md, README.md, ReleaseNotes.md, scripts/versions.sh, src/content/import_service.cc, src/content/scripting/script.cc, src/database/sql_database.cc, src/metadata/ffmpeg_handler.cc, src/upnp/xml_builder.cc, src/util/grb_time.cc, src/util/grb_time.h, src/web/clients.cc, src/web/config_load.cc, src/web/edit_load.cc
Reimplement deprecated fmt::localtime
=> Update spdlog to 1.15.3

ChangeLog.md, ReleaseNotes.md, scripts/js/audio.js, src/config/config_definition.cc, src/metadata/ffmpeg_handler.cc, src/metadata/wavpack_handler.cc, src/metadata/wavpack_handler.h
Also, change handling of resources in ffmpeg handler to resource option like in wavpack handler.
=> Extend details extracted by WavPack handler

ChangeLog.md, Dockerfile, ReleaseNotes.md, src/cds/cds_enums.cc, src/cds/cds_enums.h, src/content/import_service.cc, src/content/layout/layout.cc, src/metadata/exiv2_handler.cc, src/metadata/exiv2_handler.h, src/metadata/ffmpeg_handler.cc, src/metadata/ffmpeg_handler.h, src/metadata/ffmpeg_thumbnailer_handler.cc, src/metadata/ffmpeg_thumbnailer_handler.h, src/metadata/libexif_handler.cc, src/metadata/libexif_handler.h, src/metadata/matroska_handler.cc, src/metadata/matroska_handler.h, src/metadata/metacontent_handler.cc, src/metadata/metacontent_handler.h, src/metadata/metadata_handler.h, src/metadata/metadata_service.cc, src/metadata/taglib_handler.cc, src/metadata/taglib_handler.h, src/metadata/wavpack_handler.cc, src/metadata/wavpack_handler.h, test/core/test_ffmpeg_cache_paths.cc
=> Add taglib and artwork support for dsf files

ChangeLog.md, src/content/content_manager.cc, src/content/import_service.cc, src/content/scripting/playlist_parser_script.cc, src/database/sql_database.cc
Solves part of #3479 and #3366
=> Fix issue with stale objects in autoscan

ChangeLog.md, ReleaseNotes.md, src/config/config_definition.cc, src/config/config_setup.h, src/config/setup/config_setup_autoscan.cc, src/config/setup/config_setup_boxlayout.cc, src/config/setup/config_setup_client.cc, src/config/setup/config_setup_dynamic.cc, src/config/setup/config_setup_enum.h, src/config/setup/config_setup_transcoding.cc, src/config/setup/config_setup_tweak.cc, src/config/setup/setup_util.h
=> Refactor ConfigSetup code for complex types

ChangeLog.md, src/content/import_service.cc, src/content/inotify/inotify_handler.cc, src/metadata/metadata_service.cc
=> Fix subtitle detection in import

ChangeLog.md, ReleaseNotes.md, doc/do_sphinx.sh, src/content/cm_task.h, src/content/inotify/autoscan_inotify.cc, src/content/inotify/inotify_handler.cc, src/content/inotify/inotify_handler.h, src/database/sqlite3/sqlite_database.cc, src/database/sqlite3/sqlite_database.h
=> Fix inotify for files

ChangeLog.md, src/util/grb_fs.cc, test/util/test_tools.cc
=> Fix subdir logic

CMakeLists.txt, ChangeLog.md
Seen in https://github.com/dbry/WavPack/commit/fb0353b2b4bd3e1743784817cda3efb9e6340305
Closes #1661
=> Check for LIBICONV_PLUG

scripts/debian/build-deb.sh
=> ci: fix up pruning old deb packages

.github/workflows/publish-deb.yml, ChangeLog.md, src/metadata/metacontent_handler.cc, test/util/test_tools.cc
=> Fix resource file pattern with braces

ChangeLog.md, src/metadata/ffmpeg_handler.cc, src/metadata/metadata_service.cc
https://github.com/gerbera/gerbera/discussions/3550#discussioncomment-14103524
=> Catch exceptions from metadata handlers

ChangeLog.md, doc/compile.rst, doc/conf.py, doc/config-clients.rst, doc/config-extended.rst, doc/config-general.rst, doc/config-generate.rst, doc/config-import.rst, doc/config-online.rst, doc/config-overview.rst, doc/config-server.rst, doc/config-transcode.rst, doc/requirements.txt, doc/troubleshooting.rst
Use confval to mark and crossreference config items
Use changeset to identify changes in items
=> Introduce sphinx toolbox

test/util/test_tools.cc
=> Add Test for formatSizeValue

ChangeLog.md, src/database/search_handler.cc
=> Fix derivedFrom search handling

ChangeLog.md, README.md, ReleaseNotes.md, doc/config-transcode.rst, scripts/versions.sh
=> Update to pupnp 1.14.25
